zigbeeManufacturer:
  - id: "fp_1a1561d85e"
    manufacturer: "BSEED"
    model: "EC-GL86ZPCRS31"
    deviceProfileName: "covers-cover"
  - id: "fp_0b472efa20"
    manufacturer: "BSEED"
    model: "S-PC86ZPCS11B"
    deviceProfileName: "covers-cover"
  - id: "fp_bff0b974b5"
    manufacturer: "Danor"
    model: "SK-Z802C-US"
    deviceProfileName: "covers-cover"
  - id: "fp_25f7dd32e8"
    manufacturer: "Girier"
    model: "ME168_Girier"
    deviceProfileName: "covers-cover"
  - id: "fp_4a1d114f65"
    manufacturer: "Girier"
    model: "TS130F_GIRIER"
    deviceProfileName: "covers-cover"
  - id: "fp_ba6b6fe2fe"
    manufacturer: "Girier"
    model: "TS130F_GIRIER_DUAL"
    deviceProfileName: "covers-cover"
  - id: "fp_4699c8ed13"
    manufacturer: "IKEA of Sweden"
    model: "FYRTUR block-out roller blind"
    deviceProfileName: "covers-cover-battery"
  - id: "fp_5b9ec3f252"
    manufacturer: "IKEA of Sweden"
    model: "KADRILJ roller blind"
    deviceProfileName: "covers-cover-battery"
  - id: "fp_8fc8a8804c"
    manufacturer: "IKEA of Sweden"
    model: "PRAKTLYSING cellular blind"
    deviceProfileName: "covers-cover-battery"
  - id: "fp_5a3fc5353d"
    manufacturer: "IKEA of Sweden"
    model: "TREDANSEN block-out cellul blind"
    deviceProfileName: "covers-cover-battery"
  - id: "fp_687c27072b"
    manufacturer: "LUMI"
    model: "lumi.curtain.acn018"
    deviceProfileName: "covers-cover"
  - id: "fp_73dc5032f1"
    manufacturer: "LUMI"
    model: "lumi.curtain.acn04"
    deviceProfileName: "covers-cover"
  - id: "fp_55276282a0"
    manufacturer: "Lidl"
    model: "HG09648"
    deviceProfileName: "covers-cover"
  - id: "fp_353f7ed485"
    manufacturer: "LoraTap"
    model: "SC400"
    deviceProfileName: "covers-cover"
  - id: "fp_c91e8169a0"
    manufacturer: "LoraTap"
    model: "SC500ZB"
    deviceProfileName: "covers-cover"
  - id: "fp_1e9978b12b"
    manufacturer: "LoraTap"
    model: "SC500ZB-v4"
    deviceProfileName: "covers-cover"
  - id: "fp_069f3af2c1"
    manufacturer: "Moes"
    model: "ZTS-EUB1"
    deviceProfileName: "covers-cover"
  - id: "fp_4548668b51"
    manufacturer: "Nous"
    model: "B4Z"
    deviceProfileName: "covers-cover"
  - id: "fp_d425b59fcc"
    manufacturer: "Nous"
    model: "L12Z"
    deviceProfileName: "covers-cover"
  - id: "fp_2514307f21"
    manufacturer: "QA"
    model: "QACZ1"
    deviceProfileName: "covers-cover"
  - id: "fp_bd4a038da3"
    manufacturer: "Sunricher"
    model: "HK-ZCC-A"
    deviceProfileName: "covers-cover"
  - id: "fp_ac25a1e80f"
    manufacturer: "Sunricher"
    model: "SR-ZG9080A"
    deviceProfileName: "covers-cover"
  - id: "fp_3dc4baee0d"
    manufacturer: "Third Reality, Inc"
    model: "3RSB015BZ"
    deviceProfileName: "covers-cover-battery"
  - id: "fp_60b42b3f81"
    manufacturer: "Third Reality, Inc"
    model: "3RSB02015Z"
    deviceProfileName: "covers-cover-battery"
  - id: "fp_01940e3ef3"
    manufacturer: "Third Reality, Inc"
    model: "TRZB3"
    deviceProfileName: "covers-cover"
  - id: "fp_ec3399577f"
    manufacturer: "Tuya"
    model: "GM35TEQ-TYZ-2/25"
    deviceProfileName: "covers-cover"
  - id: "fp_45c0f32f70"
    manufacturer: "Yookee"
    model: "D10110_1"
    deviceProfileName: "covers-cover"
  - id: "fp_f40d6111a1"
    manufacturer: "Zemismart"
    model: "TS130F_ZEMISMART"
    deviceProfileName: "covers-cover"
  - id: "fp_fc4fd84203"
    manufacturer: "Zemismart"
    model: "ZM25R3"
    deviceProfileName: "covers-cover"
  - id: "fp_47aa3bbf01"
    manufacturer: "Zemismart"
    model: "ZN-LC1E"
    deviceProfileName: "covers-cover"
  - id: "fp_0a42aa9aa1"
    manufacturer: "_TZ3000_1dd0d5yi"
    model: "TS130F"
    deviceProfileName: "covers-cover"
  - id: "fp_d5aa8aaefb"
    manufacturer: "_TZ3000_5iixzdo7"
    model: "TS130F"
    deviceProfileName: "covers-cover"
  - id: "fp_b2a797eacc"
    manufacturer: "_TZ3000_74hsp7qy"
    model: "TS130F"
    deviceProfileName: "covers-cover"
  - id: "fp_be21837aba"
    manufacturer: "_TZ3000_8h7wgocw"
    model: "TS130F"
    deviceProfileName: "covers-cover"
  - id: "fp_2ec98faed8"
    manufacturer: "_TZ3000_bmhwnl7s"
    model: "TS130F"
    deviceProfileName: "covers-cover-2"
  - id: "fp_e297b11938"
    manufacturer: "_TZ3000_bs93npae"
    model: "TS130F"
    deviceProfileName: "covers-cover"
  - id: "fp_3b0b97d2ab"
    manufacturer: "_TZ3000_dojqjapa"
    model: "TS130F"
    deviceProfileName: "covers-cover"
  - id: "fp_e83d7a08b9"
    manufacturer: "_TZ3000_e3vhyirx"
    model: "TS130F"
    deviceProfileName: "covers-cover"
  - id: "fp_aa65f67d71"
    manufacturer: "_TZ3000_egq7y6pr"
    model: "TS130F"
    deviceProfileName: "covers-cover"
  - id: "fp_3c7b57ce17"
    manufacturer: "_TZ3000_esynmmox"
    model: "TS130F"
    deviceProfileName: "covers-cover-2"
  - id: "fp_0961863dcf"
    manufacturer: "_TZ3000_fccpjz5z"
    model: "TS130F"
    deviceProfileName: "covers-cover"
  - id: "fp_76eb29410e"
    manufacturer: "_TZ3000_femsaaua"
    model: "TS130F"
    deviceProfileName: "covers-cover"
  - id: "fp_54de718637"
    manufacturer: "_TZ3000_j1xl73iw"
    model: "TS130F"
    deviceProfileName: "covers-cover-2"
  - id: "fp_40a8982a73"
    manufacturer: "_TZ3000_jwv3cwak"
    model: "TS130F"
    deviceProfileName: "covers-cover"
  - id: "fp_4edba9824c"
    manufacturer: "_TZ3000_kmsbwdol"
    model: "TS130F"
    deviceProfileName: "covers-cover-2"
  - id: "fp_d99ba354e9"
    manufacturer: "_TZ3000_l6iqph4f"
    model: "TS130F"
    deviceProfileName: "covers-cover-2"
  - id: "fp_ffe04e5651"
    manufacturer: "_TZ3000_vd43bbfq"
    model: "TS130F"
    deviceProfileName: "covers-cover"
  - id: "fp_1e36bc577a"
    manufacturer: "_TZ3000_vw8pawxa"
    model: "TS130F"
    deviceProfileName: "covers-cover"
  - id: "fp_37be451bdd"
    manufacturer: "_TZ3000_xdo0hj1k"
    model: "TS130F"
    deviceProfileName: "covers-cover-2"
  - id: "fp_451e372ccb"
    manufacturer: "_TZ3000_yruungrl"
    model: "TS130F"
    deviceProfileName: "covers-cover"
  - id: "fp_fc4fc09255"
    manufacturer: "_TZ3000_zirycpws"
    model: "TS130F"
    deviceProfileName: "covers-cover"
  - id: "fp_022d63afad"
    manufacturer: "_TZ3210_dwytrmda"
    model: "TS130F"
    deviceProfileName: "covers-cover"
  - id: "fp_3c0add38f1"
    manufacturer: "_TZ3210_ol1uhvza"
    model: "TS130F"
    deviceProfileName: "covers-cover"
  - id: "fp_7b7b2c317e"
    manufacturer: "_TZ3210_xbpt8ewc"
    model: "TS130F"
    deviceProfileName: "covers-cover"
  - id: "fp_6f12069e76"
    manufacturer: "_TZB000_42ha4rsc"
    model: "TS030F"
    deviceProfileName: "covers-cover"
  - id: "fp_b5399c08c9"
    manufacturer: "_TZE200_9caxna4s"
    model: "TS0301"
    deviceProfileName: "covers-cover"
  - id: "fp_e7e7fd2a07"
    manufacturer: "_TZE20C_xbexmf8h"
    model: "TS130F"
    deviceProfileName: "covers-cover"
  - id: "fp_c8974ac4b0"
    manufacturer: "eWeLink"
    model: "AM25C-1-25-ES-E-Z"
    deviceProfileName: "covers-cover"
  - id: "fp_8f075fae6c"
    manufacturer: "eWeLink"
    model: "CK-MG22-Z310EE07DOOYA-01(7015)"
    deviceProfileName: "covers-cover"
  - id: "fp_b7a5822deb"
    manufacturer: "eWeLink"
    model: "MYDY25Z-1"
    deviceProfileName: "covers-cover"
  - id: "fp_f6eced15da"
    manufacturer: "eWeLink"
    model: "ZM25-EAZ"
    deviceProfileName: "covers-cover"
