name: safety-presence-wave11-szr07
components:
  - id: main
    capabilities:
      - {id: presenceSensor, version: 1}
      - {id: illuminanceMeasurement, version: 1}
      - {id: concertmirror08464.szrSevenDetectionDistance, version: 1}
      - {id: concertmirror08464.szrSevenRadarSensitivity, version: 1}
      - {id: concertmirror08464.szrSevenFadingTime, version: 1}
      - {id: concertmirror08464.szrSevenRadarSwitch, version: 1}
      - {id: concertmirror08464.szrSevenIndicator, version: 1}
      - {id: refresh, version: 1}
    categories: [{name: PresenceSensor}]
