zigbeeManufacturer:
  - id: "fp_4834acb58f"
    manufacturer: "MatSee Plus"
    model: "PC321-Z-TY"
    deviceProfileName: "meters-power-energy-voltage-current-clamp3phase"
  - id: "fp_7d8f5b8720"
    manufacturer: "Nous"
    model: "D4Z"
    deviceProfileName: "meters-energy-3phase-nous-d4z"
  - id: "fp_d9dd6b86eb"
    manufacturer: "OWON"
    model: "PC321-Z-TY"
    deviceProfileName: "meters-power-energy-voltage-current-clamp3phase"
  - id: "fp_d527974cdf"
    manufacturer: "Ourtop"
    model: "ATMS100133Z"
    deviceProfileName: "meters-energy-3phase-atms10013z3"
  - id: "fp_1a3d2392d6"
    manufacturer: "Tongou"
    model: "TOSA1-01WXJAT2A"
    deviceProfileName: "meters-power-energy-voltage-current-toqsa1"
  - id: "fp_2cda0814af"
    manufacturer: "Tuya"
    model: "PJ-1203-W"
    deviceProfileName: "meters-power-energy-voltage-current"
  - id: "fp_e50fb7534a"
    manufacturer: "_TZE200_78ioiaml"
    model: "TS0601"
    deviceProfileName: "meters-power-energy-2phase-sdm02v1"
  - id: "fp_7f65e34478"
    manufacturer: "_TZE200_bcusnqt8"
    model: "TS0601"
    deviceProfileName: "meters-energy-1phase-spm01"
  - id: "fp_472d2b289d"
    manufacturer: "_TZE200_d2zfgtij"
    model: "TS0601"
    deviceProfileName: "meters-energy-1phase-spm01v1gt"
  - id: "fp_4dfd56ae47"
    manufacturer: "_TZE200_dikb3dp6"
    model: "TS0601"
    deviceProfileName: "meters-energy-3phase-spm02v3"
  - id: "fp_8893a7945e"
    manufacturer: "_TZE200_gomuk3dc"
    model: "TS0601"
    deviceProfileName: "meters-energy-3phase-sdm01v15"
  - id: "fp_ecea9a71c3"
    manufacturer: "_TZE200_iwn0gpzz"
    model: "TS0601"
    deviceProfileName: "meters-energy-1phase-spm01v25"
  - id: "fp_5870ac9896"
    manufacturer: "_TZE200_nslr42tt"
    model: "TS0601"
    deviceProfileName: "meters-power-energy-voltage-current-clamp3phase"
  - id: "fp_ca03d12bc5"
    manufacturer: "_TZE200_ny94onlb"
    model: "TS0601"
    deviceProfileName: "meters-energy-3phase-spm02v25"
  - id: "fp_988ead0996"
    manufacturer: "_TZE200_qhlxve78"
    model: "TS0601"
    deviceProfileName: "meters-energy-1phase-spm01v2"
  - id: "fp_da8767eeb7"
    manufacturer: "_TZE200_rks0sgb7"
    model: "TS0601"
    deviceProfileName: "meters-power-energy-voltage-current-pc311"
  - id: "fp_74114d9de6"
    manufacturer: "_TZE200_s4sa1mcx"
    model: "TS0601"
    deviceProfileName: "meters-energy-3phase-sdm01v1gt"
  - id: "fp_6ce497d9b3"
    manufacturer: "_TZE200_ugekduaj"
    model: "TS0601"
    deviceProfileName: "meters-power-energy-voltage-current-sdm01"
  - id: "fp_58ffad87c3"
    manufacturer: "_TZE200_v9hkz2yn"
    model: "TS0601"
    deviceProfileName: "meters-energy-3phase-spm02v2"
  - id: "fp_0388b5e111"
    manufacturer: "_TZE200_ves1ycwx"
    model: "TS0601"
    deviceProfileName: "meters-energy-3phase-spm02"
  - id: "fp_79c139f51b"
    manufacturer: "_TZE200_wjk6rurm"
    model: "TS0601"
    deviceProfileName: "meters-energy-3phase-spm02v1gt"
  - id: "fp_f7a45eacdf"
    manufacturer: "_TZE200_x8diwkqb"
    model: "TS0601"
    deviceProfileName: "meters-energy-2phase-sdm02v1gt"
  - id: "fp_f77622b29c"
    manufacturer: "_TZE200_x8fp01wi"
    model: "TS0601"
    deviceProfileName: "meters-switch-power-energy-clamp3phase-relay"
  - id: "fp_e6cf6e66e6"
    manufacturer: "_TZE204_78ioiaml"
    model: "TS0601"
    deviceProfileName: "meters-power-energy-2phase-sdm02v1"
  - id: "fp_728bc5bc5d"
    manufacturer: "_TZE204_81yrt3lo"
    model: "TS0601"
    deviceProfileName: "meters-power-energy-voltage-current-pj1203a"
  - id: "fp_5142424d25"
    manufacturer: "_TZE204_ac0fhfiq"
    model: "TS0601"
    deviceProfileName: "meters-power-energy-voltage-current-bidirectional"
  - id: "fp_7b1538faf2"
    manufacturer: "_TZE204_cjbofhxw"
    model: "TS0601"
    deviceProfileName: "meters-power-energy-voltage-current"
  - id: "fp_73576dbdca"
    manufacturer: "_TZE204_d2zfgtij"
    model: "TS0601"
    deviceProfileName: "meters-energy-1phase-spm01v1gt"
  - id: "fp_9032c85bed"
    manufacturer: "_TZE204_dhotiauw"
    model: "TS0601"
    deviceProfileName: "meters-power-energy-voltage-current-2ct"
  - id: "fp_e8a3c3a505"
    manufacturer: "_TZE204_dikb3dp6"
    model: "TS0601"
    deviceProfileName: "meters-energy-3phase-spm02v3"
  - id: "fp_aa6dde225c"
    manufacturer: "_TZE204_gomuk3dc"
    model: "TS0601"
    deviceProfileName: "meters-energy-3phase-sdm01v15"
  - id: "fp_21276173fe"
    manufacturer: "_TZE204_iwn0gpzz"
    model: "TS0601"
    deviceProfileName: "meters-energy-1phase-spm01v25"
  - id: "fp_d2163464d4"
    manufacturer: "_TZE204_loejka0i"
    model: "TS0601"
    deviceProfileName: "meters-energy-3phase-nous-d4z"
  - id: "fp_8fbc9a545b"
    manufacturer: "_TZE204_ny94onlb"
    model: "TS0601"
    deviceProfileName: "meters-energy-3phase-spm02v25"
  - id: "fp_b9ae5e6695"
    manufacturer: "_TZE204_qhlxve78"
    model: "TS0601"
    deviceProfileName: "meters-energy-1phase-spm01v2"
  - id: "fp_83ea781fe7"
    manufacturer: "_TZE204_s4sa1mcx"
    model: "TS0601"
    deviceProfileName: "meters-energy-3phase-sdm01v1gt"
  - id: "fp_d98dce8a87"
    manufacturer: "_TZE204_ugekduaj"
    model: "TS0601"
    deviceProfileName: "meters-power-energy-voltage-current-sdm01"
  - id: "fp_2ce6096b5f"
    manufacturer: "_TZE204_v9hkz2yn"
    model: "TS0601"
    deviceProfileName: "meters-energy-3phase-spm02v2"
  - id: "fp_8ea4883ea8"
    manufacturer: "_TZE204_ves1ycwx"
    model: "TS0601"
    deviceProfileName: "meters-energy-3phase-spm02"
  - id: "fp_b520ece7f1"
    manufacturer: "_TZE204_wjk6rurm"
    model: "TS0601"
    deviceProfileName: "meters-energy-3phase-spm02v1gt"
  - id: "fp_c75f510cdd"
    manufacturer: "_TZE204_x8diwkqb"
    model: "TS0601"
    deviceProfileName: "meters-energy-2phase-sdm02v1gt"
  - id: "fp_bf9e6c32e6"
    manufacturer: "_TZE204_x8fp01wi"
    model: "TS0601"
    deviceProfileName: "meters-switch-power-energy-clamp3phase-relay"
  - id: "fp_7b94d45b2a"
    manufacturer: "_TZE284_4hdbt6rn"
    model: "TS0601"
    deviceProfileName: "meters-power-energy-voltage-current-toqsa1"
  - id: "fp_747ec89d66"
    manufacturer: "_TZE284_78ioiaml"
    model: "TS0601"
    deviceProfileName: "meters-power-energy-2phase-sdm02v1"
  - id: "fp_82b97d3033"
    manufacturer: "_TZE284_81yrt3lo"
    model: "TS0601"
    deviceProfileName: "meters-power-energy-voltage-current-pj1203a"
  - id: "fp_d14b09e730"
    manufacturer: "_TZE284_a14rjslz"
    model: "TS0601"
    deviceProfileName: "meters-energy-3phase-atms10013z3"
  - id: "fp_87e4581b8b"
    manufacturer: "_TZE284_ac0fhfiq"
    model: "TS0601"
    deviceProfileName: "meters-power-energy-voltage-current-bidirectional"
  - id: "fp_f4c7d5ec93"
    manufacturer: "_TZE284_cjbofhxw"
    model: "TS0601"
    deviceProfileName: "meters-power-energy-voltage-current"
  - id: "fp_154d11aa31"
    manufacturer: "_TZE284_d2zfgtij"
    model: "TS0601"
    deviceProfileName: "meters-energy-1phase-spm01v1gt"
  - id: "fp_c7ca107b6b"
    manufacturer: "_TZE284_dikb3dp6"
    model: "TS0601"
    deviceProfileName: "meters-energy-3phase-spm02v3"
  - id: "fp_3946c7b42b"
    manufacturer: "_TZE284_gomuk3dc"
    model: "TS0601"
    deviceProfileName: "meters-energy-3phase-sdm01v15"
  - id: "fp_02610651c9"
    manufacturer: "_TZE284_iwn0gpzz"
    model: "TS0601"
    deviceProfileName: "meters-energy-1phase-spm01v25"
  - id: "fp_2866efd63d"
    manufacturer: "_TZE284_loejka0i"
    model: "TS0601"
    deviceProfileName: "meters-energy-3phase-nous-d4z"
  - id: "fp_6fd9649800"
    manufacturer: "_TZE284_ny94onlb"
    model: "TS0601"
    deviceProfileName: "meters-energy-3phase-spm02v25"
  - id: "fp_bf7e8c8ba5"
    manufacturer: "_TZE284_pglpvdar"
    model: "TS0601"
    deviceProfileName: "meters-power-energy-voltage-current-toqsa1"
  - id: "fp_77458cb556"
    manufacturer: "_TZE284_qhlxve78"
    model: "TS0601"
    deviceProfileName: "meters-energy-1phase-spm01v2"
  - id: "fp_82bdfc57e4"
    manufacturer: "_TZE284_s4sa1mcx"
    model: "TS0601"
    deviceProfileName: "meters-energy-3phase-sdm01v1gt"
  - id: "fp_aa939dea2b"
    manufacturer: "_TZE284_v9hkz2yn"
    model: "TS0601"
    deviceProfileName: "meters-energy-3phase-spm02v2"
  - id: "fp_9b00656eaa"
    manufacturer: "_TZE284_ves1ycwx"
    model: "TS0601"
    deviceProfileName: "meters-energy-3phase-spm02"
  - id: "fp_093d707bfb"
    manufacturer: "_TZE284_wjk6rurm"
    model: "TS0601"
    deviceProfileName: "meters-energy-3phase-spm02v1gt"
  - id: "fp_8b74ba2735"
    manufacturer: "_TZE284_x8diwkqb"
    model: "TS0601"
    deviceProfileName: "meters-energy-2phase-sdm02v1gt"
  - id: "fp_58c0851770"
    manufacturer: "_TZE28C1000000_81yrt3lo"
    model: "TS0601"
    deviceProfileName: "meters-power-energy-voltage-current-pj1203a"
