-- Generated by source/tools/build_dist.py. Source catalog remains in source/src/core.
local custom_capabilities = {}
local function range(value)
if type(value) ~= "table" then return nil end
return { minimum = value[1], maximum = value[2], step = value[3], unit = value[4], allowed_values = value[5] }
end
local function numeric(row)
return { kind = "numeric", emit_name = row[1], range_key = row[2], capability_id = row[3], attribute_name = row[4], range_attribute_name = row[5], command_name = row[6], argument_name = row[7], mapping_name = row[8], label = row[9], default_range = range(row[10]), event_minimum = row[11], event_maximum = row[12], event_unit = row[13] }
end
local function enum(row)
return { kind = "enum", emit_name = row[1], range_key = row[2], capability_id = row[3], attribute_name = row[4], supported_attribute_name = row[5], command_name = row[6], argument_name = row[7], mapping_name = row[8], label = row[9], supported_values = row[10], default_range = { allowed_values = row[10] } }
end
local function text(row)
return { kind = "text", emit_name = row[1], capability_id = row[2], attribute_name = row[3], command_name = row[4], argument_name = row[5], mapping_name = row[6], label = row[7], maximum_length = row[8] }
end
local function build(rows, factory)
local out = {}
for _, row in ipairs(rows) do out[#out + 1] = factory(row) end
return out
end
custom_capabilities.numeric = build({}, numeric)
custom_capabilities.enum = build({ { "battery_low", "battery_low", "concertmirror08464.batteryLow", "batteryLow", nil, "setBatteryLow", "batteryLow", "battery_low", "Battery low", { "normal", "low" } }, { "indicator_mode", "indicator_mode", "concertmirror08464.indicatorMode", "indicatorMode", "supportedIndicatorModes", "setIndicatorMode", "indicatorMode", "indicator_mode", "Indicator mode", { "off", "off/on", "on/off", "on" } }, { "power_on_behavior", "power_on_behavior", "concertmirror08464.powerOnBehavior", "powerOnBehavior", "supportedPowerOnBehaviors", "setPowerOnBehavior", "powerOnBehavior", "power_on_behavior", "Power on behavior", { "off", "on", "previous" } }, { "switch_mode", "switch_mode", "concertmirror08464.switchMode", "switchMode", "supportedSwitchModes", "setSwitchMode", "switchMode", "switch_mode", "Switch mode", { "switch", "scene" } }, { "operation_mode", "operation_mode", "concertmirror08464.operationMode", "operationMode", "supportedOperationModes", "setOperationMode", "operationMode", "operation_mode", "Operation mode", { "command", "event" } }, { "learn_ir_code", "learn_ir_code", "concertmirror08464.learnIrCode", "learnIrCode", "supportedLearnIrCodes", "setLearnIrCode", "learnIrCode", "learn_ir_code", "Learn IR code", { "start", "stop" } }, { "security_remote_action", "security_remote_action", "concertmirror08464.securityRemoteAction", "securityRemoteAction", "supportedSecurityRemoteActions", "setSecurityRemoteAction", "securityRemoteAction", "security_remote_action", "Security remote action", { "disarm", "arm_day_zones", "arm_night_zones", "arm_all_zones", "exit_delay", "emergency" } } }, enum)
custom_capabilities.text = build({ { "last_power_response_time", "concertmirror08464.lastPowerResponseTime", "lastPowerResponseTime", nil, nil, nil, "Last power response time", 64 }, { "remote_action", "concertmirror08464.remoteAction", "remoteAction", nil, nil, nil, "Remote action", 128 }, { "learned_ir_code", "concertmirror08464.learnedIrCode", "learnedIrCode", nil, nil, nil, "Learned IR code", 2048 }, { "ir_code_to_send", "concertmirror08464.irCodeToSend", "irCodeToSend", "setIrCodeToSend", "irCodeToSend", nil, "IR code to send", 2048 } }, text)
custom_capabilities.driver_message = { ["attribute_name"] = "driverMessage", ["capability_id"] = "concertmirror08464.driverMessage", ["emit_name"] = "driver_message", ["label"] = "Driver message", ["maximum_length"] = 512 }
custom_capabilities.by_range_key = {}
custom_capabilities.by_emit_name = {}
custom_capabilities.by_capability_id = {}
local function index_metadata(definitions)
for _, metadata in ipairs(definitions) do
custom_capabilities.by_emit_name[metadata.emit_name] = metadata
if type(metadata.capability_id) == "string" and metadata.capability_id ~= "" then custom_capabilities.by_capability_id[metadata.capability_id] = metadata end
if type(metadata.range_key) == "string" and metadata.range_key ~= "" then custom_capabilities.by_range_key[metadata.range_key] = metadata end
end
end
index_metadata(custom_capabilities.numeric)
index_metadata(custom_capabilities.enum)
index_metadata(custom_capabilities.text)
custom_capabilities.by_emit_name[custom_capabilities.driver_message.emit_name] = custom_capabilities.driver_message
custom_capabilities.by_capability_id[custom_capabilities.driver_message.capability_id] = custom_capabilities.driver_message
local function clone_allowed_values(allowed_values)
if type(allowed_values) ~= "table" then return nil end
local copied = {}
for index, value in ipairs(allowed_values) do copied[index] = value end
return copied
end
function custom_capabilities.resolve_range(definition, metadata)
if type(metadata) ~= "table" then return nil end
local default_range = type(metadata.default_range) == "table" and metadata.default_range or nil
local ranges = type(definition) == "table" and definition.presence_capability_ranges or nil
local resolved = type(ranges) == "table" and ranges[metadata.range_key] or nil
if type(resolved) ~= "table" then resolved = default_range end
if type(resolved) ~= "table" then return nil end
return {
minimum = type(resolved.minimum) == "number" and resolved.minimum or (default_range and default_range.minimum or nil),
maximum = type(resolved.maximum) == "number" and resolved.maximum or (default_range and default_range.maximum or nil),
step = type(resolved.step) == "number" and resolved.step or (default_range and default_range.step or nil),
unit = type(resolved.unit) == "string" and resolved.unit or (default_range and default_range.unit or nil),
allowed_values = type(resolved.allowed_values) == "table" and clone_allowed_values(resolved.allowed_values) or clone_allowed_values(default_range and default_range.allowed_values or nil),
}
end
return custom_capabilities
