zigbeeManufacturer:
  - id: "fp_377ae2bb4a"
    manufacturer: "Homeetec"
    model: "37022714"
    deviceProfileName: "switches-switch-4-backlight-hewlydpz"
  - id: "fp_fda494136a"
    manufacturer: "Nova Digital"
    model: "FZB-4"
    deviceProfileName: "switches-switch-4-tyg3-sm"
  - id: "fp_41fe7deb88"
    manufacturer: "TZE204_unsxl4ir"
    model: "TS0601"
    deviceProfileName: "switches-switch-4-tyg3-sm"
  - id: "fp_e818c36a8f"
    manufacturer: "_TZE200_0j5jma9b"
    model: "TS0601"
    deviceProfileName: "switches-switch-6-tyg3-sm"
  - id: "fp_dda7343c40"
    manufacturer: "_TZE200_1ozguk6x"
    model: "TS0601"
    deviceProfileName: "switches-switch-4-zts-eu"
  - id: "fp_a0c7996e67"
    manufacturer: "_TZE200_amp6tsvy"
    model: "TS0601"
    deviceProfileName: "switches-switch-1-zts-eu"
  - id: "fp_4c5830b47f"
    manufacturer: "_TZE200_g1ib5ldv"
    model: "TS0601"
    deviceProfileName: "switches-switch-2-zts-eu"
  - id: "fp_47db346fa7"
    manufacturer: "_TZE200_h2rctifa"
    model: "TS0601"
    deviceProfileName: "switches-switch-6-tyg3-sm"
  - id: "fp_3ef44fb33e"
    manufacturer: "_TZE200_hewlydpz"
    model: "TS0601"
    deviceProfileName: "switches-switch-4-backlight-hewlydpz"
  - id: "fp_a0faa5de31"
    manufacturer: "_TZE200_k6jhsr0q"
    model: "TS0601"
    deviceProfileName: "switches-switch-4-tyg3-sm"
  - id: "fp_d02bf0365b"
    manufacturer: "_TZE200_nvodulvi"
    model: "TS0601"
    deviceProfileName: "switches-switch-8-m9-sl"
  - id: "fp_1497c81ac3"
    manufacturer: "_TZE200_rqhnxkqu"
    model: "TS0601"
    deviceProfileName: "switches-switch-6-to6"
  - id: "fp_325dd5f85b"
    manufacturer: "_TZE200_tviaymwx"
    model: "TS0601"
    deviceProfileName: "switches-switch-1-zts-eu"
  - id: "fp_1c67f79467"
    manufacturer: "_TZE200_tz32mtza"
    model: "TS0601"
    deviceProfileName: "switches-switch-3-zts-eu"
  - id: "fp_ab02bbf89e"
    manufacturer: "_TZE200_vhy3iakz"
    model: "TS0601"
    deviceProfileName: "switches-switch-3-tyg3-sm"
  - id: "fp_c410be8fb2"
    manufacturer: "_TZE200_wunufsil"
    model: "TS0601"
    deviceProfileName: "switches-switch-2-tyg3-sm"
  - id: "fp_d621a3ec20"
    manufacturer: "_TZE204_7ytnacie"
    model: "TS0601"
    deviceProfileName: "switches-switch-4-colored-backlight"
  - id: "fp_1c6caf5e35"
    manufacturer: "_TZE204_adlblwab"
    model: "TS0601"
    deviceProfileName: "switches-switch-8-adlblwab"
  - id: "fp_f37b2cc9ce"
    manufacturer: "_TZE204_ccgyhbvd"
    model: "TS0601"
    deviceProfileName: "switches-switch-3-touch-panel"
  - id: "fp_0c76b12c72"
    manufacturer: "_TZE204_fhv95pf1"
    model: "TS0601"
    deviceProfileName: "switches-switch-1-stairwell"
  - id: "fp_833fba6b82"
    manufacturer: "_TZE204_gm8h14wy"
    model: "TS0601"
    deviceProfileName: "switches-switch-1-touch-panel"
  - id: "fp_a82bbb1abb"
    manufacturer: "_TZE204_he9apaui"
    model: "TS0601"
    deviceProfileName: "switches-switch-2-touch-panel"
  - id: "fp_3f26c90e11"
    manufacturer: "_TZE204_hewlydpz"
    model: "TS0601"
    deviceProfileName: "switches-switch-4-colored-backlight"
  - id: "fp_f241016f7c"
    manufacturer: "_TZE204_rkbxtclc"
    model: "TS0601"
    deviceProfileName: "switches-switch-3-colored-backlight"
  - id: "fp_945e5813e3"
    manufacturer: "_TZE204_unsxl4ir"
    model: "TS0601"
    deviceProfileName: "switches-switch-4-tyg3-sm"
  - id: "fp_ea74bbac0d"
    manufacturer: "_TZE204_y8ficeai"
    model: "TS0601"
    deviceProfileName: "switches-switch-6-touch-panel"
  - id: "fp_888d998bcf"
    manufacturer: "_TZE204_zqq3cipq"
    model: "TS0601"
    deviceProfileName: "switches-switch-16-pn16"
  - id: "fp_197c215c06"
    manufacturer: "_TZE284_0kihjsys"
    model: "TS0601"
    deviceProfileName: "switches-eyzee-5gang-countdown"
  - id: "fp_d2fe955e54"
    manufacturer: "_TZE284_7e6v8u9f"
    model: "TS0601"
    deviceProfileName: "switches-switch-1-multifunction"
  - id: "fp_7cd96f9cd7"
    manufacturer: "_TZE284_7zazvlyn"
    model: "TS0601"
    deviceProfileName: "switches-switch-4-f3-pro"
  - id: "fp_cb2ebce224"
    manufacturer: "_TZE284_atuj3i0w"
    model: "TS0601"
    deviceProfileName: "switches-switch-4-lcd-panel"
  - id: "fp_6a8bdc8e42"
    manufacturer: "_TZE284_hyssaqjk"
    model: "TS0601"
    deviceProfileName: "switches-switch-6-touch-panel"
  - id: "fp_db15b4ad0b"
    manufacturer: "_TZE284_idn2htgu"
    model: "TS0601"
    deviceProfileName: "switches-switch-4-f3-pro"
  - id: "fp_e2b7ff11c6"
    manufacturer: "_TZE284_iwyqtclw"
    model: "TS0601"
    deviceProfileName: "switches-switch-4-lcd-panel"
  - id: "fp_2c53b37707"
    manufacturer: "_TZE284_nvodulvi"
    model: "TS0601"
    deviceProfileName: "switches-switch-8-m9-sl"
  - id: "fp_3377357ac4"
    manufacturer: "_TZE284_tokhh9pf"
    model: "TS0601"
    deviceProfileName: "switches-switch-6-touch-panel"
  - id: "fp_c64f27d109"
    manufacturer: "_TZE284_yrwmnya3"
    model: "TS0601"
    deviceProfileName: "switches-switch-4-m9-sl"
  - id: "fp_352699b417"
    manufacturer: "_TZE284_zpvusbtv"
    model: "TS0601"
    deviceProfileName: "switches-switch-2-colored-backlight"
  - id: "fp_a2d01cd7c4"
    manufacturer: "_TZE284_zqq3cipq"
    model: "TS0601"
    deviceProfileName: "switches-switch-16-pn16"
