zigbeeManufacturer:
  - id: "fp_2ee8b67227"
    manufacturer: " Legrand\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00"
    model: " Dimmer switch with neutral\x00\x00\x00\x00"
    deviceProfileName: "lights-dimmer"
  - id: "fp_cb04698fb7"
    manufacturer: "Candeo"
    model: "C-ZB-RD1Pv2-DIM"
    deviceProfileName: "lights-wave19-candeo-rd1pv2-dim"
  - id: "fp_fcd293e2b8"
    manufacturer: "Candeo"
    model: "C-ZB-RD1Pv2-DPM"
    deviceProfileName: "lights-candeo-rd1p-dpm"
  - id: "fp_8167b4acb0"
    manufacturer: "Paulmann Licht GmbH"
    model: "RGBWW"
    deviceProfileName: "lights-paulmann-rgbww"
  - id: "fp_70c6607389"
    manufacturer: "Paulmann lamp "
    model: "Dimmable Light "
    deviceProfileName: "lights-dimmer"
  - id: "fp_c10ba37b09"
    manufacturer: "Shelly"
    model: "Dimmer 0-1/10"
    deviceProfileName: "lights-shelly-dimmer-gen4"
  - id: "fp_7fba058d85"
    manufacturer: "Xiaoyan"
    model: "DIM003"
    deviceProfileName: "lights-wave19-terncy-dim003"
  - id: "fp_1f462e0738"
    manufacturer: "eWeLi\x01\x00\x10"
    model: "ZB-CL01"
    deviceProfileName: "lights-color-temperature-color"
