zigbeeManufacturer:
  - id: fp_b927e6c360
    manufacturer: "AVATTO"
    model: "WT-100-BH"
    deviceProfileName: "thermostats-thermostat-zwt198"
  - id: fp_1a12983664
    manufacturer: "_TZE200_2ekuz3dz"
    model: "TS0601"
    deviceProfileName: "thermostats-thermostat-x5h"
  - id: fp_bcc39de821
    manufacturer: "_TZE200_5toc8efa"
    model: "TS0601"
    deviceProfileName: "thermostats-bht002-fine"
  - id: fp_866e8ef0f1
    manufacturer: "_TZE200_aoclfnxz"
    model: "TS0601"
    deviceProfileName: "thermostats-bht002-fine"
  - id: fp_4ce5c831af
    manufacturer: "_TZE200_edl8pz1k"
    model: "TS0601"
    deviceProfileName: "thermostats-thermostat-floor"
  - id: fp_c08ea98042
    manufacturer: "_TZE200_g9a3awaj"
    model: "TS0601"
    deviceProfileName: "thermostats-thermostat-zwt07"
  - id: fp_a6a5af233c
    manufacturer: "_TZE200_ha0vwoew"
    model: "TS0601"
    deviceProfileName: "thermostats-thermostat-thermosphere"
  - id: fp_bd329c228a
    manufacturer: "_TZE200_u9bfwha0"
    model: "TS0601"
    deviceProfileName: "thermostats-bht002-fine"
  - id: fp_b8e3eee073
    manufacturer: "_TZE200_viy9ihs7"
    model: "TS0601"
    deviceProfileName: "thermostats-thermostat-zwt198"
  - id: fp_996e125111
    manufacturer: "_TZE200_ye5jkfsb"
    model: "TS0601"
    deviceProfileName: "thermostats-bht002-fine"
  - id: fp_1e994f9f1d
    manufacturer: "_TZE200_znzs7yaw"
    model: "TS0601"
    deviceProfileName: "thermostats-thermostat-hy08we"
  - id: fp_fd39d86cf4
    manufacturer: "_TZE200_ztvwu4nk"
    model: "TS0601"
    deviceProfileName: "thermostats-bht002-fine"
  - id: fp_a81a9abe76
    manufacturer: "_TZE204_0hcjew5p"
    model: "TS0601"
    deviceProfileName: "thermostats-thermostat-pilot-wire-no-operating"
  - id: fp_829cf773fc
    manufacturer: "_TZE204_3q3maeoo"
    model: "TS0601"
    deviceProfileName: "thermostats-thermostat-pilot-wire-no-operating"
  - id: fp_0608c18ba5
    manufacturer: "_TZE204_3regm3h6"
    model: "TS0601"
    deviceProfileName: "thermostats-thermostat-pilot-wire-no-operating"
  - id: fp_840c35dc25
    manufacturer: "_TZE204_5toc8efa"
    model: "TS0601"
    deviceProfileName: "thermostats-bht002-half"
  - id: fp_a803438f71
    manufacturer: "_TZE204_6a4vxfnv"
    model: "TS0601"
    deviceProfileName: "thermostats-thermostat-floor"
  - id: fp_baf715bfba
    manufacturer: "_TZE204_6kijc7nd"
    model: "TS0601"
    deviceProfileName: "thermostats-thermostat-tervix"
  - id: fp_01a28cda03
    manufacturer: "_TZE204_6vwfjkcj"
    model: "TS0601"
    deviceProfileName: "thermostats-thermostat-pilot-wire-no-operating"
  - id: fp_6705272397
    manufacturer: "_TZE204_aaeaifez"
    model: "TS0601"
    deviceProfileName: "thermostats-thermostat-zwt100"
  - id: fp_888391382c
    manufacturer: "_TZE204_aoclfnxz"
    model: "TS0601"
    deviceProfileName: "thermostats-bht002-whole"
  - id: fp_13e837de48
    manufacturer: "_TZE204_d6i25bwg"
    model: "TS0601"
    deviceProfileName: "thermostats-thermostat-pilot-wire-no-operating"
  - id: fp_5df3dbde95
    manufacturer: "_TZE204_edl8pz1k"
    model: "TS0601"
    deviceProfileName: "thermostats-thermostat-floor"
  - id: fp_9cfa085bfc
    manufacturer: "_TZE204_gops3slb"
    model: "TS0601"
    deviceProfileName: "thermostats-thermostat-zwt198"
  - id: fp_8d97f97e3c
    manufacturer: "_TZE204_lzriup1j"
    model: "TS0601"
    deviceProfileName: "thermostats-thermostat-zwt198"
  - id: fp_9d8ed4081e
    manufacturer: "_TZE204_oh8y8pv8"
    model: "TS0601"
    deviceProfileName: "thermostats-thermostat-zwt198"
  - id: fp_5f42d0f4ae
    manufacturer: "_TZE204_ouy7vpm1"
    model: "TS0601"
    deviceProfileName: "thermostats-thermostat-pilot-wire-no-operating"
  - id: fp_f5e2360526
    manufacturer: "_TZE204_tagezcph"
    model: "TS0601"
    deviceProfileName: "thermostats-thermostat-pro900z"
  - id: fp_32b6aafcff
    manufacturer: "_TZE204_u9bfwha0"
    model: "TS0601"
    deviceProfileName: "thermostats-bht002-fine"
  - id: fp_243dfec018
    manufacturer: "_TZE204_wc2w9t1s"
    model: "TS0601"
    deviceProfileName: "thermostats-thermostat-bot-r9v"
  - id: fp_14af12e476
    manufacturer: "_TZE204_xnbkhhdr"
    model: "TS0601"
    deviceProfileName: "thermostats-thermostat-zwt198"
  - id: fp_601226a8b6
    manufacturer: "_TZE204_zjhoqbrd"
    model: "TS0601"
    deviceProfileName: "thermostats-thermostat-zwt198"
  - id: fp_22338a0dd7
    manufacturer: "_TZE284_3regm3h6"
    model: "TS0601"
    deviceProfileName: "thermostats-thermostat-pilot-wire-no-operating"
  - id: fp_53db2f51fd
    manufacturer: "_TZE284_6kijc7nd"
    model: "TS0601"
    deviceProfileName: "thermostats-thermostat-tervix"
  - id: fp_9c88784386
    manufacturer: "_TZE284_aaeaifez"
    model: "TS0601"
    deviceProfileName: "thermostats-thermostat-zwt100"
  - id: fp_d088f5a850
    manufacturer: "_TZE284_agcxaw3f"
    model: "TS0601"
    deviceProfileName: "thermostats-thermostat-battery-bot-r15w"
  - id: fp_ec3725f2d0
    manufacturer: "_TZE284_gops3slb"
    model: "TS0601"
    deviceProfileName: "thermostats-thermostat-zwt198"
  - id: fp_484f768ee5
    manufacturer: "_TZE284_khah2lkr"
    model: "TS0601"
    deviceProfileName: "thermostats-thermostat-khah2lkr"
  - id: fp_816093c29b
    manufacturer: "_TZE284_xnbkhhdr"
    model: "TS0601"
    deviceProfileName: "thermostats-thermostat-zwt198"
  - id: fp_3128694696
    manufacturer: "_TZE284_ye5jkfsb"
    model: "TS0601"
    deviceProfileName: "thermostats-bht002-fine"
  - id: fp_2e5fd53d40
    manufacturer: "_TZE284_zjhoqbrd"
    model: "TS0601"
    deviceProfileName: "thermostats-thermostat-zwt198"
  - id: fp_4bdd65e347
    manufacturer: "_TZE28C1000000_aaeaifez"
    model: "TS0601"
    deviceProfileName: "thermostats-thermostat-zwt100"
