zigbeeManufacturer:
  - id: "fp_9d02500ee9"
    manufacturer: "_TYST11_2dpplnsn"
    model: "dpplnsn\x00"
    deviceProfileName: "thermostats-thermostat-etop"
  - id: "fp_f2dba491ee"
    manufacturer: "_TYST11_8daqwrsj"
    model: "daqwrsj\x00"
    deviceProfileName: "thermostats-alecto-smart-heat10"
  - id: "fp_1332c09241"
    manufacturer: "_TYST11_KGbxAXL2"
    model: "GbxAXL2\x00"
    deviceProfileName: "thermostats-thermostat-saswell"
  - id: "fp_e2ecae0cb7"
    manufacturer: "_TYST11_c88teujp"
    model: "88teujp\x00"
    deviceProfileName: "thermostats-thermostat-saswell"
  - id: "fp_c1d8d5391b"
    manufacturer: "_TYST11_caj4jz0i"
    model: "aj4jz0i\x00"
    deviceProfileName: "thermostats-thermostat-saswell"
  - id: "fp_76159f8975"
    manufacturer: "_TYST11_wv90ladg"
    model: "v90ladg\x00"
    deviceProfileName: "thermostats-thermostat-etop"
  - id: "fp_c436590aca"
    manufacturer: "_TYST11_yw7cahqs"
    model: "w7cahqs\x00"
    deviceProfileName: "thermostats-thermostat-saswell"
  - id: "fp_49df39167c"
    manufacturer: "_TYST11_zuhszj9s"
    model: "uhszj9s\x00"
    deviceProfileName: "thermostats-thermostat-saswell"
  - id: "fp_f7c5e645a9"
    manufacturer: "_TZE200_4aijvczq"
    model: "TS0601"
    deviceProfileName: "thermostats-wave6a-avatto-me168"
  - id: "fp_e93a78217a"
    manufacturer: "_TZE200_6y7kyjga"
    model: "TS0601"
    deviceProfileName: "thermostats-wave9-moes-brt100"
  - id: "fp_772003992e"
    manufacturer: "_TZE200_b6wax7g0"
    model: "TS0601"
    deviceProfileName: "thermostats-wave9-moes-brt100"
  - id: "fp_ea3f47ed68"
    manufacturer: "_TZE200_chyvmhay"
    model: "TS0601"
    deviceProfileName: "thermostats-wave9-lidl-368308"
  - id: "fp_6b40883ed5"
    manufacturer: "_TZE200_cxakecfo"
    model: "TS0601"
    deviceProfileName: "thermostats-wave6a-avatto-me168"
  - id: "fp_2f0603de82"
    manufacturer: "_TZE200_dmfguuli"
    model: "TS0601"
    deviceProfileName: "thermostats-wave9-evanell-ez200"
  - id: "fp_ba365f23d7"
    manufacturer: "_TZE200_fhn3negr"
    model: "TS0601"
    deviceProfileName: "thermostats-wave12-moes-sh4"
  - id: "fp_1bd6b72840"
    manufacturer: "_TZE200_i48qyn9s"
    model: "TS0601"
    deviceProfileName: "thermostats-wave12-essentials-trv"
  - id: "fp_798d1e54b1"
    manufacturer: "_TZE200_ivdc0kwl"
    model: "TS0601"
    deviceProfileName: "thermostats-wave15-moes-ztrv-s01"
  - id: "fp_9404815f6c"
    manufacturer: "_TZE200_ne4pikwm"
    model: "TS0601"
    deviceProfileName: "thermostats-wave6a-nedis-zbhtr20wt"
  - id: "fp_a8192aaf57"
    manufacturer: "_TZE200_qsoecqlk"
    model: "TS0601"
    deviceProfileName: "thermostats-wave9-moes-brt100"
  - id: "fp_7f18d3b81d"
    manufacturer: "_TZE200_r5ksy7qo"
    model: "TS0601"
    deviceProfileName: "thermostats-wave6a-avatto-me168"
  - id: "fp_6a4c6e1e42"
    manufacturer: "_TZE200_rxypyjkw"
    model: "TS0601"
    deviceProfileName: "thermostats-wave9-evanell-ez200"
  - id: "fp_3b1491bb88"
    manufacturer: "_TZE200_uiyqstza"
    model: "TS0601"
    deviceProfileName: "thermostats-wave9-lidl-368308"
  - id: "fp_11028df857"
    manufacturer: "_TZE200_wlosfena"
    model: "TS0601"
    deviceProfileName: "thermostats-wave19-immax-07703l"
  - id: "fp_16c37edc2d"
    manufacturer: "_TZE200_wnvhlcgl"
    model: "TS0601"
    deviceProfileName: "thermostats-wave19-woox-r7067"
  - id: "fp_8b705c63eb"
    manufacturer: "_TZE200_ybsqljjg"
    model: "TS0601"
    deviceProfileName: "thermostats-wave6a-avatto-me168"
  - id: "fp_cb2b264eab"
    manufacturer: "_TZE204_k6rdmisz"
    model: "TS0601"
    deviceProfileName: "thermostats-wave9-mazda-tr-m2z"
  - id: "fp_cfaa36aea3"
    manufacturer: "_TZE204_p1qrtljn"
    model: "TS0601"
    deviceProfileName: "thermostats-wave12-tech-v2"
  - id: "fp_2e5d1a5a1d"
    manufacturer: "_TZE204_r7brscr6"
    model: "TS0601"
    deviceProfileName: "thermostats-wave12-tech-v1"
  - id: "fp_8f3b7b9e6f"
    manufacturer: "_TZE204_xdtnpp1a"
    model: "TS0601"
    deviceProfileName: "thermostats-wave6a-avatto-trv26"
  - id: "fp_d266551790"
    manufacturer: "_TZE284_hcs66axl"
    model: "TS0601"
    deviceProfileName: "thermostats-wave6a-nedis-zbhtr20wt"
  - id: "fp_1df0256124"
    manufacturer: "_TZE284_k6rdmisz"
    model: "TS0601"
    deviceProfileName: "thermostats-wave9-mazda-tr-m2z"
  - id: "fp_ee7e0a1df2"
    manufacturer: "_TZE284_ne4pikwm"
    model: "TS0601"
    deviceProfileName: "thermostats-wave6a-nedis-zbhtr20wt"
  - id: "fp_d4e76a34ae"
    manufacturer: "_TZE284_ty5neqqo"
    model: "TS0601"
    deviceProfileName: "thermostats-wave12-avatto-trv60"
  - id: "fp_2b99b5946f"
    manufacturer: "_TZE284_xdtnpp1a"
    model: "TS0601"
    deviceProfileName: "thermostats-wave6a-avatto-trv26"
