name: safety-co-nous-e12
components:
  - id: main
    capabilities:
      - {id: carbonMonoxideDetector, version: 1}
      - {id: carbonMonoxideMeasurement, version: 1}
      - {id: concertmirror08464.nousETwelveWarmingUp, version: 1}
      - {id: concertmirror08464.nousETwelveTest, version: 1}
      - {id: concertmirror08464.nousETwelveTesting, version: 1}
      - {id: hardwareFault, version: 1}
      - {id: concertmirror08464.nousETwelveEndOfLife, version: 1}
      - {id: concertmirror08464.nousETwelveBatteryState, version: 1}
    categories: [{name: GenericSensor}]
deviceConfig:
  dashboard:
    states:
      - {component: main, capability: carbonMonoxideDetector, version: 1, group: main}
      - {component: main, capability: carbonMonoxideMeasurement, version: 1, group: main}
    actions: []
    basicPlus: []
  detailView:
    - {component: main, capability: carbonMonoxideDetector, version: 1}
    - {component: main, capability: carbonMonoxideMeasurement, version: 1}
    - {component: main, capability: concertmirror08464.nousETwelveWarmingUp, version: 1}
    - {component: main, capability: concertmirror08464.nousETwelveTest, version: 1}
    - {component: main, capability: concertmirror08464.nousETwelveTesting, version: 1}
    - {component: main, capability: hardwareFault, version: 1}
    - {component: main, capability: concertmirror08464.nousETwelveEndOfLife, version: 1}
    - {component: main, capability: concertmirror08464.nousETwelveBatteryState, version: 1}
  automation:
    conditions:
      - {component: main, capability: carbonMonoxideDetector, version: 1}
      - {component: main, capability: carbonMonoxideMeasurement, version: 1}
      - {component: main, capability: concertmirror08464.nousETwelveWarmingUp, version: 1}
      - {component: main, capability: concertmirror08464.nousETwelveTest, version: 1}
      - {component: main, capability: concertmirror08464.nousETwelveTesting, version: 1}
      - {component: main, capability: hardwareFault, version: 1}
      - {component: main, capability: concertmirror08464.nousETwelveEndOfLife, version: 1}
      - {component: main, capability: concertmirror08464.nousETwelveBatteryState, version: 1}
    actions:
      - {component: main, capability: concertmirror08464.nousETwelveTest, version: 1}
