local capabilities=require "st.capabilities"
local tuya=require "protocol.tuya"
local emit=require "capabilities.events.all"
local zcl=require "protocol.zcl"
local device_helpers=require "contracts.helpers.family"
local common=require "contracts.helpers.ef00_presence"
local converter=tuya.converter
local device_definitions,register_device_definition=common.isolated_definition_registry(device_helpers.definition_registry)
local function register_presence_definition(definitions_or_table,fingerprint_list,ranges)
return common.register_presence_definition(
register_device_definition,definitions_or_table,fingerprint_list,ranges
)
end
local ts0601_fingerprints=common.ts0601_fingerprints
local on_off_enum1_converter=converter.lookup_from_to({on=1,off=0})
local breaker_mode_converter=converter.lookup_from_to({standard=0,["local"]=1})
local radar_scene_yxz_converter=converter.lookup_from_to({
default=0,bathroom=1,bedroom=2,sleeping=3,unknown=4,
})
local detection_method_converter=converter.lookup_from_to({only_move=0,exist_move=1})
local sensor_state_mode_converter=converter.lookup_from_to({
on=0,off=1,occupied=2,unoccupied=3,
})
local presence_model_zy_m100_24g={
profile="safety-presence-zym10024g-illuminance",
package_group="presence-advanced",
named_datapoints=true,
tuya.dp_numeric(102,{name="illuminance_threshold_max"}),
tuya.dp_numeric(103,{name="illuminance_threshold_min"}),
tuya.dp_illuminance(104,{emit=emit.illuminance()}),
tuya.dp_enum(105,{
name="state",
read_only=true,
emit=emit.zym10024gState(),
converter=converter.lookup_from_to({
none=0,
presence=1,
move=2,
}),
}),
tuya.dp_numeric(106,{
name="move_sensitivity",
emit=emit.zym10024gMoveSensitivity(),
converter=converter.divide_by_from_only(10),
}),
tuya.dp_numeric(107,{
name="max_range",
emit=emit.zym10024gMaxRange(),
converter=converter.divide_by_pair(100),
}),
tuya.dp_numeric(109,{
name="target_distance",
read_only=true,
emit=emit.zym10024gTargetDistance(),
converter=converter.divide_by_from_only(100),
}),
tuya.dp_numeric(110,{name="presence_timeout",emit=emit.zym10024gTimeout()}),
tuya.dp_numeric(111,{
name="presence_sensitivity",
emit=emit.zym10024gSensitivity(),
converter=converter.divide_by_from_only(10),
}),
tuya.dp_presence(112,{emit=emit.presence(),converter=converter.true_false1()}),
}
register_presence_definition(presence_model_zy_m100_24g,ts0601_fingerprints({
"_TZE204_ijxvkhd0",
}))
local presence_model_zy_m100_24gv2={
profile="safety-presence-zym10024gv2-move-range-illuminance",
package_group="presence-advanced",
named_datapoints=true,
datapoints={
tuya.dp_enum(1,{
name="state",
read_only=true,
emit=emit.zym24gv2State(),
converter=converter.from_only(converter.lookup_value({
[0]="none",
[1]="presence",
[2]="move",
})),
}),
tuya.dp_numeric(2,{name="move_sensitivity",emit=emit.zym24gv2MoveSensitivity()}),
tuya.dp_numeric(3,{
name="min_range",
emit=emit.zym24gv2MinRange(),
converter=converter.divide_by_pair(100),
}),
tuya.dp_numeric(4,{
name="max_range",
emit=emit.zym24gv2MaxRange(),
converter=converter.divide_by_pair(100),
}),
tuya.dp_numeric(9,{
name="target_distance",
read_only=true,
emit=emit.zym24gv2TargetDistance(),
converter=converter.divide_by_from_only(10),
}),
tuya.dp_numeric(102,{name="presence_sensitivity",emit=emit.zym24gv2Sensitivity()}),
tuya.dp_illuminance(103,{emit=emit.illuminance()}),
tuya.dp_presence(104,{emit=emit.presence(),converter=converter.true_false1()}),
tuya.dp_numeric(105,{name="presence_timeout",emit=emit.zym24gv2Timeout()}),
},
}
register_presence_definition(presence_model_zy_m100_24gv2,ts0601_fingerprints({
"_TZE204_7gclukjs",
}))
local function zym24gv3_presence_from_state()
local emitter=emit.presence()
return function(device,value,dp_info,mapping_context)
return emitter(device,value=="presence" or value=="move",dp_info,mapping_context)
end
end
local zym24gv3_state_converter=converter.from_only(converter.lookup_value({
[0]="none",
[1]="presence",
[2]="move",
}))
local function build_zym24gv3_datapoints(min_range_emitter,max_range_emitter)
return{
tuya.dp_enum(1,{
name="presence_state",
read_only=true,
emit=emit.all(emit.zym24gv3State(),zym24gv3_presence_from_state()),
converter=zym24gv3_state_converter,
}),
tuya.dp_numeric(2,{name="move_sensitivity",emit=emit.zym24gv3MoveSensitivity()}),
tuya.dp_numeric(3,{
name="min_range",
emit=min_range_emitter,
converter=converter.divide_by_pair(100),
}),
tuya.dp_numeric(4,{
name="max_range",
emit=max_range_emitter,
converter=converter.divide_by_pair(100),
}),
tuya.dp_numeric(9,{
name="target_distance",
read_only=true,
emit=emit.zym24gv3TargetDistance(),
converter=converter.divide_by_from_only(10),
}),
tuya.dp_binary(101,{name="find_switch"}),
tuya.dp_numeric(102,{name="presence_sensitivity",emit=emit.zym24gv3Sensitivity()}),
tuya.dp_illuminance(103,{emit=emit.illuminance()}),
tuya.dp_numeric(105,{name="presence_timeout",emit=emit.zym24gv3Timeout()}),
}
end
local presence_model_zy_m100_24gv3_b={
profile="safety-presence-zym10024gv3-move-range-illuminance",
package_group="presence-advanced",
named_datapoints=true,
datapoints=build_zym24gv3_datapoints(emit.zym24gv3bMinRange(),emit.zym24gv3bMaxRange()),
}
register_presence_definition(presence_model_zy_m100_24gv3_b,ts0601_fingerprints({
"_TZE204_ya4ft0w4",
"_TZE200_ya4ft0w4",
}))
local presence_model_zy_m100_24gv3_a={
profile="safety-presence-zym10024gv3a-move-range-illuminance",
package_group="presence-advanced",
named_datapoints=true,
datapoints=build_zym24gv3_datapoints(emit.zym24gv3aMinRange(),emit.zym24gv3aMaxRange()),
}
register_presence_definition(presence_model_zy_m100_24gv3_a,ts0601_fingerprints({
"_TZE204_gkfbdvyx",
"_TZE200_gkfbdvyx",
}))
local presence_model_yxzbrb58={
profile="safety-presence-yxzbrb58-range-delay-scene-illuminance",
package_group="presence-advanced",
named_datapoints=true,
datapoints={
tuya.dp_presence(1,{emit=emit.presence(),converter=converter.true_false1()}),
tuya.dp_numeric(2,{name="radar_sensitivity",emit=emit.yxzbrb58Sensitivity()}),
tuya.dp_numeric(3,{
name="min_range",
emit=emit.yxzbrb58MinRange(),
converter=converter.divide_by_pair(100),
}),
tuya.dp_numeric(4,{
name="max_range",
emit=emit.yxzbrb58MaxRange(),
converter=converter.divide_by_pair(100),
}),
tuya.dp_illuminance(101,{emit=emit.illuminance()}),
tuya.dp_numeric(102,{
name="detection_delay",
emit=emit.yxzbrb58DetectionDelay(),
converter=converter.divide_by_pair(10),
}),
tuya.dp_numeric(103,{
name="fading_time",
emit=emit.yxzbrb58FadingTime(),
converter=converter.divide_by_pair(10),
}),
tuya.dp_enum(104,{
name="radar_scene",
emit=emit.yxzbrb58RadarScene(),
converter=radar_scene_yxz_converter,
}),
tuya.dp_numeric(105,{
name="target_distance",
read_only=true,
emit=emit.yxzbrb58TargetDistance(),
converter=converter.divide_by_from_only(100),
}),
},
}
register_presence_definition(presence_model_yxzbrb58,ts0601_fingerprints({
"_TZE204_sooucan5",
"_TZE204_oqtpvx51",
}))
local presence_model_ctl_r1_ty_zigbee={
profile="safety-presence-ctlr1-threshold-min-delay-illuminance",
package_group="presence-advanced",
named_datapoints=true,
datapoints={
tuya.dp_presence(1,{emit=emit.presence(),converter=converter.true_false1()}),
tuya.dp_numeric(2,{name="presence_sensitivity",emit=emit.ctlr1Sensitivity()}),
tuya.dp_numeric(4,{
name="detection_range",
emit=emit.ctlr1DetectionRange(),
converter=converter.divide_by_pair(10),
}),
tuya.dp_illuminance(101,{emit=emit.illuminance()}),
tuya.dp_numeric(102,{name="illuminance_threshold_max",emit=emit.ctlr1ThresholdMax()}),
tuya.dp_numeric(103,{name="illuminance_threshold_min",emit=emit.ctlr1ThresholdMin()}),
tuya.dp_numeric(104,{name="detection_delay",emit=emit.ctlr1DetectionDelay()}),
tuya.dp_binary(105,{
name="light_switch",
read_only=true,
emit=emit.ctlr1LightSwitch(),
converter=converter.lookup_from_to({ON=true,OFF=false}),
}),
tuya.dp_enum(106,{
name="light_linkage",
emit=emit.ctlr1LightLinkage(),
converter=on_off_enum1_converter,
}),
tuya.dp_enum(107,{
name="indicator_light",
emit=emit.ctlr1IndicatorLight(),
converter=converter.lookup_from_to({
presence=0,
off=1,
on=2,
}),
}),
tuya.dp_enum(108,{
name="detection_method",
emit=emit.ctlr1DetectionMethod(),
converter=detection_method_converter,
}),
tuya.dp_enum(109,{
name="illuminance_switch",
emit=emit.ctlr1ThresholdSwitch(),
converter=on_off_enum1_converter,
}),
},
}
register_presence_definition(presence_model_ctl_r1_ty_zigbee,ts0601_fingerprints({
"_TZE204_e9ajs4ft",
}))
local presence_model_rt_zcz03z={
profile="safety-presence-rtzcz03z-range-illuminance",
package_group="presence-advanced",
named_datapoints=true,
datapoints={
tuya.dp_presence(1,{emit=emit.presence(),converter=converter.true_false(4)}),
tuya.dp_numeric(101,{
name="target_distance",
read_only=true,
emit=emit.rtzcz03zTargetDistance(),
}),
tuya.dp_illuminance(102,{emit=emit.illuminance()}),
tuya.dp_numeric(103,{name="fading_time",emit=emit.rtzcz03zFadingTime()}),
tuya.dp_binary(104,{
name="indicator",
emit=emit.rtzcz03zIndicator(),
converter=converter.lookup_from_to({ON=true,OFF=false}),
}),
tuya.dp_numeric(107,{name="max_distance",emit=emit.rtzcz03zMaxDistance()}),
tuya.dp_numeric(108,{name="min_distance",emit=emit.rtzcz03zMinDistance()}),
tuya.dp_numeric(111,{name="presence_sensitivity",emit=emit.rtzcz03zSensitivity()}),
},
}
register_presence_definition(presence_model_rt_zcz03z,ts0601_fingerprints({
"_TZE204_uxllnywp",
}))
local presence_model_mtg075_zb_rl={
profile="safety-presence-mtg075-entry-controls-illuminance",
package_group="presence-advanced",
named_datapoints=true,
datapoints={
tuya.dp_presence(1,{emit=emit.presence(),converter=converter.true_false1()}),
tuya.dp_numeric(2,{name="radar_sensitivity",emit=emit.mtg075RadarSensitivity()}),
tuya.dp_numeric(3,{
name="shield_range",
emit=emit.mtg075ShieldRange(),
converter=converter.divide_by_pair(100),
}),
tuya.dp_numeric(4,{
name="detection_range",
emit=emit.mtg075DetectionRange(),
converter=converter.divide_by_pair(100),
}),
tuya.dp_numeric(6,{name="equipment_status",read_only=true}),
tuya.dp_numeric(9,{
name="target_distance",
read_only=true,
emit=emit.mtg075TargetDistance(),
converter=converter.divide_by_from_only(100),
}),
tuya.dp_numeric(101,{
name="entry_filter_time",
emit=emit.mtg075EntryFilterTime(),
converter=converter.divide_by_pair(10),
}),
tuya.dp_numeric(102,{name="departure_delay",emit=emit.mtg075DepartureDelay()}),
tuya.dp_illuminance(104,{emit=emit.illuminance(),scale=10}),
tuya.dp_numeric(105,{name="entry_sensitivity",emit=emit.mtg075EntrySensitivity()}),
tuya.dp_numeric(106,{
name="entry_distance_indentation",
emit=emit.mtg075EntryIndentation(),
converter=converter.divide_by_pair(100),
}),
tuya.dp_enum(107,{
name="breaker_mode",
emit=emit.mtg075BreakerMode(),
converter=breaker_mode_converter,
}),
tuya.dp_enum(108,{
name="breaker_status",
emit=emit.mtg075BreakerStatus(),
converter=converter.lookup_from_to({OFF=0,ON=1}),
}),
tuya.dp_enum(109,{
name="status_indication",
emit=emit.mtg075StatusIndication(),
converter=converter.lookup_from_to({OFF=0,ON=1}),
}),
tuya.dp_numeric(110,{
name="illuminance_threshold",
emit=emit.mtg075IlluminanceThreshold(),
converter=converter.divide_by_pair(10),
}),
tuya.dp_enum(111,{
name="breaker_polarity",
emit=emit.mtg075BreakerPolarity(),
converter=converter.lookup_from_to({NC=0,NO=1}),
}),
tuya.dp_numeric(112,{
name="block_time",
emit=emit.mtg075BlockTime(),
converter=converter.divide_by_pair(10),
}),
tuya.dp_enum(115,{
name="sensor_state",
emit=emit.mtg075SensorState(),
converter=sensor_state_mode_converter,
}),
},
}
register_presence_definition(presence_model_mtg075_zb_rl,ts0601_fingerprints({
"_TZE204_sbyx0lm6",
"_TZE204_clrdrnya",
"_TZE204_dtzziy1e",
"_TZE204_iaeejhvf",
"_TZE204_mtoaryre",
"_TZE200_mp902om5",
"_TZE204_pfayrzcw",
"_TZE284_4qznlkbu",
"_TZE200_clrdrnya",
"_TZE200_sbyx0lm6",
}))
local zym100s3_sensitivity_converter=converter.lookup_from_to({
low=0,
medium=1,
high=2,
})
local zym100s3_keep_time_converter=converter.lookup_from_to({
["30"]=0,
["60"]=1,
["120"]=2,
})
local presence_model_zy_m100_s_3={
profile="safety-presence-zym100s3-keep-illuminance",
package_group="presence-advanced",
named_datapoints=true,
datapoints={
tuya.dp_presence(1,{emit=emit.presence(),converter=converter.true_false0()}),
tuya.dp_enum(9,{
name="sensitivity",
emit=emit.zym100s3Sensitivity(),
converter=zym100s3_sensitivity_converter,
}),
tuya.dp_enum(10,{
name="keep_time",
emit=emit.zym100s3KeepTime(),
converter=zym100s3_keep_time_converter,
}),
tuya.dp_illuminance(12,{emit=emit.illuminance()}),
},
}
register_presence_definition(presence_model_zy_m100_s_3,ts0601_fingerprints({
"_TZE204_nbkshs6k",
}))
local function zg205z_presence_from_state()
local emitter=emit.presence()
return function(device,value,dp_info,mapping_context)
return emitter(device,value ~="none",dp_info,mapping_context)
end
end
local presence_model_zg_205z={
profile="safety-presence-zg205z-illuminance",
package_group="presence-advanced",
named_datapoints=true,
datapoints={
tuya.dp_enum(1,{
name="presence_state",
read_only=true,
emit=emit.all(emit.zg205zPresenceState(),zg205z_presence_from_state()),
converter=converter.from_only(converter.lookup_value({
[0]="none",
[1]="presence",
[2]="peaceful",
[3]="small_movement",
[4]="large_movement",
})),
}),
tuya.dp_numeric(101,{
name="target_distance",
read_only=true,
emit=emit.zg205zTargetDistance(),
converter=converter.divide_by_from_only(100),
}),
tuya.dp_illuminance(102,{emit=emit.illuminance()}),
tuya.dp_numeric(103,{name="none_delay_time",emit=emit.zg205zNoneDelayTime()}),
tuya.dp_binary(104,{
name="indicator",
emit=emit.zg205zIndicator(),
converter=converter.lookup_from_to({ON=true,OFF=false}),
}),
tuya.dp_numeric(107,{
name="move_detection_max",
emit=emit.zg205zMoveMax(),
converter=converter.divide_by_pair(100),
}),
tuya.dp_numeric(108,{
name="move_detection_min",
emit=emit.zg205zMoveMin(),
converter=converter.divide_by_pair(100),
}),
tuya.dp_numeric(109,{
name="breath_detection_max",
emit=emit.zg205zBreathMax(),
converter=converter.divide_by_pair(100),
}),
tuya.dp_numeric(110,{
name="breath_detection_min",
emit=emit.zg205zBreathMin(),
converter=converter.divide_by_pair(100),
}),
tuya.dp_numeric(114,{
name="small_move_detection_max",
emit=emit.zg205zSmallMoveMax(),
converter=converter.divide_by_pair(100),
}),
tuya.dp_numeric(115,{
name="small_move_detection_min",
emit=emit.zg205zSmallMoveMin(),
converter=converter.divide_by_pair(100),
}),
tuya.dp_numeric(116,{name="move_sensitivity",emit=emit.zg205zMoveSensitivity()}),
tuya.dp_numeric(117,{name="small_move_sensitivity",emit=emit.zg205zSmallMoveSensitivity()}),
tuya.dp_numeric(118,{name="breath_sensitivity",emit=emit.zg205zBreathSensitivity()}),
},
}
register_presence_definition(presence_model_zg_205z,ts0601_fingerprints({
"_TZE204_dapwryy7",
}))
local presence_model_zg_205za={
profile="safety-presence-zg205za-illuminance",
package_group="presence-advanced",
named_datapoints=true,
datapoints={
tuya.dp_presence(1,{emit=emit.presence(),converter=converter.true_false1()}),
tuya.dp_numeric(2,{
name="large_motion_sensitivity",
emit=emit.zg205zaLargeSensitivity(),
}),
tuya.dp_numeric(4,{
name="large_motion_distance",
emit=emit.zg205zaLargeDistance(),
converter=converter.divide_by_pair(100),
}),
tuya.dp_enum(101,{
name="motion_state",
read_only=true,
emit=emit.zg205zaMotionState(),
converter=converter.from_only(converter.lookup_value({
[0]="none",
[1]="large",
[2]="medium",
[3]="small",
[4]="far",
[5]="near",
})),
}),
tuya.dp_numeric(102,{name="fading_time",emit=emit.zg205zaFadingTime()}),
tuya.dp_numeric(104,{
name="medium_motion_distance",
emit=emit.zg205zaMediumDistance(),
converter=converter.divide_by_pair(100),
}),
tuya.dp_numeric(105,{
name="medium_motion_sensitivity",
emit=emit.zg205zaMediumSensitivity(),
}),
tuya.dp_illuminance(106,{emit=emit.illuminance()}),
tuya.dp_binary(107,{
name="indicator",
emit=emit.zg205zaIndicator(),
converter=converter.lookup_from_to({ON=true,OFF=false}),
}),
tuya.dp_numeric(108,{
name="small_detection_distance",
emit=emit.zg205zaSmallDistance(),
converter=converter.divide_by_pair(100),
}),
tuya.dp_numeric(109,{
name="small_detection_sensitivity",
emit=emit.zg205zaSmallSensitivity(),
}),
tuya.dp_numeric(122,{
name="target_distance",
read_only=true,
emit=emit.zg205zaTargetDistance(),
converter=converter.divide_by_from_only(100),
}),
tuya.dp_numeric(123,{
name="minimum_range",
emit=emit.zg205zaMinimumRange(),
converter=converter.divide_by_pair(100),
}),
},
}
register_presence_definition(presence_model_zg_205za,{
device_helpers.create_fingerprint("_TZE200_2aaelwxk","TS0225"),
device_helpers.create_fingerprint("_TZE200_crq3r3la","TS0225"),
device_helpers.create_fingerprint("HOBEIAN","CK-BL702-MWS-01(7016)"),
device_helpers.create_fingerprint("_TZE200_crq3r3la","CK-BL702-MWS-01(7016)"),
})
local presence_model_zg_205zl={
profile="safety-presence-zg205zl-illuminance",
package_group="presence-advanced",
named_datapoints=true,
datapoints={
tuya.dp_presence(1,{emit=emit.presence(),converter=converter.true_false1()}),
tuya.dp_enum(11,{
name="motion_state",
read_only=true,
emit=emit.zg205zlMotionState(),
converter=converter.from_only(converter.lookup_value({
[0]="none",
[1]="large",
[2]="small",
[3]="static",
[4]="far",
[5]="near",
})),
}),
tuya.dp_numeric(12,{name="fading_time",emit=emit.zg205zlFadingTime()}),
tuya.dp_numeric(13,{
name="large_motion_distance",
emit=emit.zg205zlLargeDistance(),
converter=converter.divide_by_pair(100),
}),
tuya.dp_numeric(14,{
name="small_motion_distance",
emit=emit.zg205zlSmallDistance(),
converter=converter.divide_by_pair(100),
}),
tuya.dp_numeric(15,{
name="large_motion_sensitivity",
emit=emit.zg205zlLargeSensitivity(),
}),
tuya.dp_numeric(16,{
name="small_motion_sensitivity",
emit=emit.zg205zlSmallSensitivity(),
}),
tuya.dp_illuminance(20,{emit=emit.illuminance()}),
tuya.dp_binary(24,{
name="light_mode",
emit=emit.zg205zlLightMode(),
converter=converter.lookup_from_to({ON=true,OFF=false}),
}),
tuya.dp_numeric(101,{name="alarm_time",emit=emit.zg205zlAlarmTime()}),
tuya.dp_enum(102,{
name="alarm_volume",
emit=emit.zg205zlAlarmVolume(),
converter=converter.lookup_from_to({
low=0,
medium=1,
high=2,
mute=3,
}),
}),
tuya.dp_numeric(103,{
name="static_distance",
emit=emit.zg205zlStaticDistance(),
converter=converter.divide_by_pair(100),
}),
tuya.dp_numeric(104,{
name="static_sensitivity",
emit=emit.zg205zlStaticSensitivity(),
}),
tuya.dp_enum(105,{
name="working_mode",
emit=emit.zg205zlMode(),
converter=converter.lookup_from_to({
arm=0,
off=1,
alarm=2,
doorbell=3,
}),
}),
},
}
register_presence_definition(presence_model_zg_205zl,{
device_helpers.create_fingerprint("_TZE200_hl0ss9oa","TS0225"),
device_helpers.create_fingerprint("ZGAF-205L","CK-BL702-MWS-01(7016)"),
device_helpers.create_fingerprint("_TZE200_y4mdop0b","TS0225"),
})
local sensor_state_mode_mtd085_converter=converter.lookup_from_to({
on=0,
occupied=1,
unoccupied=2,
})
local debug_mode_mtd085_converter=converter.lookup_from_to({
OFF=0,
ON=1,
})
local scene_preset_mtd085_converter=converter.lookup_from_to({
custom=0,
toilet=1,
kitchen=2,
hallway=3,
bedroom=4,
livingroom=5,
meetingroom=6,
factory_default=7,
})
local distance_report_mode_mtd085_converter=converter.lookup_from_to({
normal=0,
occupancy_detection=1,
})
local presence_model_mtd085_zb={
profile="safety-occupancy-mtd085-illuminance",
package_group="presence-advanced",
datapoints={
tuya.dp_numeric(101,{
name="entry_sensitivity",
emit=emit.mtd085EntrySensitivity(),
command_id=tuya.SEND_DATA,
}),
tuya.dp_numeric(102,{
name="entry_distance",
emit=emit.mtd085EntryDistance(),
converter=converter.divide_by_pair(100),
command_id=tuya.SEND_DATA,
}),
tuya.dp_numeric(103,{
name="departure_delay",
emit=emit.mtd085DepartureDelay(),
command_id=tuya.SEND_DATA,
}),
tuya.dp_numeric(104,{
name="entry_filter_time",
emit=emit.mtd085EntryFilterTime(),
converter=converter.divide_by_pair(100),
command_id=tuya.SEND_DATA,
}),
tuya.dp_numeric(105,{
name="block_time",
emit=emit.mtd085BlockTime(),
converter=converter.divide_by_pair(10),
command_id=tuya.SEND_DATA,
}),
tuya.dp_illuminance(107,{
emit=emit.illuminance(),
converter=converter.divide_by_pair(10),
read_only=true,
}),
tuya.dp_enum(108,{
name="debug_mode",
emit=emit.mtd085DebugMode(),
converter=debug_mode_mtd085_converter,
command_id=tuya.SEND_DATA,
}),
tuya.dp_numeric(109,{
name="debug_distance",
emit=emit.mtd085DebugDistance(),
converter=converter.divide_by_pair(100),
read_only=true,
}),
tuya.dp_numeric(110,{
name="debug_countdown",
emit=emit.mtd085DebugCountdown(),
read_only=true,
}),
tuya.dp_enum(111,{
name="scene_preset",
emit=emit.mtd085ScenePreset(),
converter=scene_preset_mtd085_converter,
command_id=tuya.SEND_DATA,
}),
tuya.dp_enum(112,{
name="sensor",
emit=emit.mtd085Sensor(),
converter=sensor_state_mode_mtd085_converter,
command_id=tuya.SEND_DATA,
}),
tuya.dp_numeric(113,{name="cline",read_only=true}),
tuya.dp_enum(114,{
name="status_indication",
emit=emit.mtd085StatusIndication(),
converter=debug_mode_mtd085_converter,
command_id=tuya.SEND_DATA,
}),
tuya.dp_numeric(115,{
name="radar_sensitivity",
emit=emit.mtd085RadarSensitivity(),
command_id=tuya.SEND_DATA,
}),
tuya.dp_numeric(116,{
name="shield_range",
emit=emit.mtd085ShieldRange(),
converter=converter.divide_by_pair(100),
command_id=tuya.SEND_DATA,
}),
tuya.dp_numeric(117,{
name="detection_range",
emit=emit.mtd085DetectionRange(),
converter=converter.divide_by_pair(100),
command_id=tuya.SEND_DATA,
}),
tuya.dp_numeric(118,{name="equipment_status",read_only=true}),
tuya.dp_numeric(119,{
name="target_distance",
emit=emit.mtd085TargetDistance(),
converter=converter.divide_by_pair(100),
read_only=true,
}),
tuya.dp_enum(120,{
name="distance_report_mode",
emit=emit.mtd085DistanceReportMode(),
converter=distance_report_mode_mtd085_converter,
command_id=tuya.SEND_DATA,
}),
},
zcl_clusters={
zcl.occupancy({ias_zone=true,read_only=true}),
},
query_on_configure=false,
}
register_device_definition(presence_model_mtd085_zb,{
device_helpers.create_fingerprint("_TZ321C_fkzihax8","TS0225"),
device_helpers.create_fingerprint("_TZ321C_4slreunp","TS0225"),
})
local presence_model_zp_301z={
profile="safety-presence-zp301z-time-cycle-illuminance-battery",
package_group="presence-advanced",
named_datapoints=true,
datapoints={
tuya.dp_presence(1,{emit=emit.presence(),converter=converter.true_false1()}),
tuya.dp_battery(14,{emit=emit.battery()}),
tuya.dp_illuminance(20,{emit=emit.illuminance()}),
tuya.dp_numeric(100,{name="brightness_value",emit=emit.zp301zBrightnessValue()}),
tuya.dp_numeric(101,{name="illuminance_trigger",emit=emit.zp301zIlluminanceTrigger()}),
tuya.dp_numeric(102,{name="presence_time",emit=emit.zp301zPresenceTime()}),
tuya.dp_numeric(103,{name="presence_delay",emit=emit.zp301zPresenceDelay()}),
tuya.dp_numeric(104,{name="detection_cycle",emit=emit.zp301zDetectionCycle()}),
},
}
register_presence_definition(presence_model_zp_301z,{
device_helpers.create_fingerprint("_TZE284_d4h8j2n6","ZP-301Z"),
device_helpers.create_fingerprint("B3876M9","ZP-301Z"),
})
return{
id="ef00.presence.advanced",
registrations=device_definitions,
}
