local tuya=require "protocol.tuya"
local emit=require "capabilities.events.all"
local device_helpers=require "contracts.helpers.family"
local common=require "contracts.helpers.ef00_din_rail"
local device_definitions,register_device_definition=device_helpers.definition_registry()
local converter=tuya.converter
local emit_metric_bundle=common.emit_metric_bundle
local circuit_breaker_faults_converter=common.circuit_breaker_faults_converter
local BREAKER_EVENT_LOOKUP=common.BREAKER_EVENT_LOOKUP
local IGNORE_ALARM_SETTING={ignore=0,alarm=1}
local power_meter_model_sdm01={
profile="meters-power-energy-voltage-current-sdm01",
package_group="meters",
tuya.dp_energy(1,{emit=emit.energy(),scale=100}),
tuya.dp_energy(2,{name="produced_energy",scale=100}),-- 프로파일 미포함
tuya.dp_power_factor(15,{name="power_factor",emit=emit.powerFactorSdm01Percent()}),
tuya.dp_ac_frequency(101,{name="ac_frequency",emit=emit.acFrequencySdm01()}),
tuya.dp_voltage(102,{name="voltage_a",emit=emit.voltage()}),
tuya.dp_current(103,{name="current_a",emit=emit.current()}),
tuya.dp_power(104,{name="power_a"}),-- 프로파일 미포함
tuya.dp_voltage(105,{name="voltage_b"}),-- 프로파일 미포함
tuya.dp_current(106,{name="current_b"}),-- 프로파일 미포함
tuya.dp_power(107,{name="power_b"}),-- 프로파일 미포함
tuya.dp_voltage(108,{name="voltage_c"}),-- 프로파일 미포함
tuya.dp_current(109,{name="current_c"}),-- 프로파일 미포함
tuya.dp_power(110,{name="power_c"}),-- 프로파일 미포함
tuya.dp_power(111,{emit=emit.power()}),
tuya.dp_energy(112,{name="energy_a",scale=100}),-- 프로파일 미포함
tuya.dp_energy(113,{name="produced_energy_a",scale=100}),-- 프로파일 미포함
tuya.dp_energy(114,{name="energy_b",scale=100}),-- 프로파일 미포함
tuya.dp_energy(115,{name="produced_energy_b",scale=100}),-- 프로파일 미포함
tuya.dp_energy(116,{name="energy_c",scale=100}),-- 프로파일 미포함
tuya.dp_energy(117,{name="produced_energy_c",scale=100}),-- 프로파일 미포함
tuya.dp_power_factor(118,{name="power_factor_a"}),-- 프로파일 미포함
tuya.dp_power_factor(119,{name="power_factor_b"}),-- 프로파일 미포함
tuya.dp_power_factor(120,{name="power_factor_c"}),-- 프로파일 미포함
}
register_device_definition(power_meter_model_sdm01,device_helpers.create_fingerprints("TS0601",{
"_TZE204_ugekduaj",
"_TZE200_ugekduaj",
}))
local power_meter_model_spm02={
profile="meters-energy-3phase-spm02",
package_group="meters",
tuya.dp_energy(1,{emit=emit.energy(),scale=100}),
tuya.dp_energy(2,{
name="produced_energy",
scale=100,
read_only=true,
emit=emit.spm02ProducedEnergy(),
}),
tuya.dp_phase_variant2(6,{
phase="x",
component="l1",
emit=emit_metric_bundle({voltage=true,current=true,power=true}),
}),
tuya.dp_phase_variant2(7,{
phase="y",
component="l2",
emit=emit_metric_bundle({voltage=true,current=true,power=true}),
}),
tuya.dp_phase_variant2(8,{
phase="z",
component="l3",
emit=emit_metric_bundle({voltage=true,current=true,power=true}),
}),
}
register_device_definition(power_meter_model_spm02,device_helpers.create_fingerprints("TS0601",{
"_TZE200_ves1ycwx",
"_TZE204_ves1ycwx",
"_TZE284_ves1ycwx",
}))
local power_meter_model_nous_d4z={
profile="meters-energy-3phase-nous-d4z",
package_group="meters",
tuya.dp_energy(1,{emit=emit.energy(),scale=100}),
tuya.dp_energy(2,{
name="produced_energy",
scale=100,
read_only=true,
emit=emit.nousD4zProducedEnergy(),
}),
tuya.dp_numeric(9,{
name="faults",
read_only=true,
emit=emit.nousD4zFaults(),
converter=circuit_breaker_faults_converter,
}),
tuya.dp_power_factor(15,{
name="power_factor",
read_only=true,
emit=emit.nousD4zPowerFactor(),
}),
tuya.dp_on_off(16,{
name="energy_reset",
emit=emit.nousD4zEnergyReset(),
converter=converter.lookup_from_to({off=false,on=true}),
}),
tuya.dp_raw(17,{name="alarm_set_1"}),
tuya.dp_raw(18,{name="alarm_set_2"}),
tuya.dp_ac_frequency(101,{
name="ac_frequency",
read_only=true,
emit=emit.nousD4zAcFrequency(),
}),
tuya.dp_voltage(102,{name="voltage_a",component="l1",emit=emit.voltage()}),
tuya.dp_current(103,{name="current_a",component="l1",emit=emit.current()}),
tuya.dp_power(104,{name="power_a",component="l1",emit=emit.power()}),
tuya.dp_voltage(105,{name="voltage_b",component="l2",emit=emit.voltage()}),
tuya.dp_current(106,{name="current_b",component="l2",emit=emit.current()}),
tuya.dp_power(107,{name="power_b",component="l2",emit=emit.power()}),
tuya.dp_voltage(108,{name="voltage_c",component="l3",emit=emit.voltage()}),
tuya.dp_current(109,{name="current_c",component="l3",emit=emit.current()}),
tuya.dp_power(110,{name="power_c",component="l3",emit=emit.power()}),
tuya.dp_power(111,{emit=emit.power()}),
tuya.dp_energy(112,{name="energy_a",scale=100,component="l1",emit=emit.energy()}),
tuya.dp_energy(113,{name="energy_produced_a",scale=100}),
tuya.dp_energy(114,{name="energy_b",scale=100,component="l2",emit=emit.energy()}),
tuya.dp_energy(115,{name="energy_produced_b",scale=100}),
tuya.dp_energy(116,{name="energy_c",scale=100,component="l3",emit=emit.energy()}),
tuya.dp_energy(117,{name="energy_produced_c",scale=100}),
tuya.dp_power_factor(118,{name="power_factor_a"}),
tuya.dp_power_factor(119,{name="power_factor_b"}),
tuya.dp_power_factor(120,{name="power_factor_c"}),
}
register_device_definition(power_meter_model_nous_d4z,device_helpers.create_fingerprints("TS0601",{
"_TZE204_loejka0i",
"_TZE284_loejka0i",
}))
register_device_definition(power_meter_model_nous_d4z,{
device_helpers.create_fingerprint("Nous","D4Z"),
})
local power_meter_model_spm02v2={
profile="meters-energy-3phase-spm02v2",
package_group="meters",
tuya.dp_energy(1,{emit=emit.energy(),scale=100}),
tuya.dp_energy(2,{
name="produced_energy",
scale=100,
read_only=true,
emit=emit.spm02v2ProducedEnergy(),
}),
tuya.dp_power_factor(15,{
name="power_factor",
read_only=true,
emit=emit.spm02v2PowerFactor(),
}),
tuya.dp_ac_frequency(101,{
name="ac_frequency",
read_only=true,
emit=emit.spm02v2AcFrequency(),
}),
tuya.dp_voltage(102,{name="voltage_a",component="l1",emit=emit.voltage()}),
tuya.dp_current(103,{name="current_a",component="l1",emit=emit.current()}),
tuya.dp_power(104,{name="power_a",component="l1",emit=emit.power()}),
tuya.dp_voltage(105,{name="voltage_b",component="l2",emit=emit.voltage()}),
tuya.dp_current(106,{name="current_b",component="l2",emit=emit.current()}),
tuya.dp_power(107,{name="power_b",component="l2",emit=emit.power()}),
tuya.dp_voltage(108,{name="voltage_c",component="l3",emit=emit.voltage()}),
tuya.dp_current(109,{name="current_c",component="l3",emit=emit.current()}),
tuya.dp_power(110,{name="power_c",component="l3",emit=emit.power()}),
tuya.dp_power(111,{emit=emit.power()}),
}
register_device_definition(power_meter_model_spm02v2,device_helpers.create_fingerprints("TS0601",{
"_TZE200_v9hkz2yn",
"_TZE204_v9hkz2yn",
"_TZE284_v9hkz2yn",
}))
local power_meter_model_spm02v25={
profile="meters-energy-3phase-spm02v25",
package_group="meters",
tuya.dp_energy(1,{emit=emit.energy(),scale=100}),
tuya.dp_energy(23,{
name="produced_energy",
scale=100,
read_only=true,
emit=emit.spm02v25ProducedEnergy(),
}),
tuya.dp_power(29,{emit=emit.power()}),
tuya.dp_ac_frequency(32,{
name="ac_frequency",
read_only=true,
emit=emit.spm02v25AcFrequency(),
}),
tuya.dp_power_factor(50,{
name="power_factor",
read_only=true,
emit=emit.spm02v25PowerFactor(),
}),
tuya.dp_voltage(102,{name="voltage_a",component="l1",emit=emit.voltage()}),
tuya.dp_current(103,{name="current_a",component="l1",emit=emit.current()}),
tuya.dp_power(104,{name="power_a",component="l1",emit=emit.power()}),
tuya.dp_voltage(105,{name="voltage_b",component="l2",emit=emit.voltage()}),
tuya.dp_current(106,{name="current_b",component="l2",emit=emit.current()}),
tuya.dp_power(107,{name="power_b",component="l2",emit=emit.power()}),
tuya.dp_voltage(108,{name="voltage_c",component="l3",emit=emit.voltage()}),
tuya.dp_current(109,{name="current_c",component="l3",emit=emit.current()}),
tuya.dp_power(110,{name="power_c",component="l3",emit=emit.power()}),
}
register_device_definition(power_meter_model_spm02v25,device_helpers.create_fingerprints("TS0601",{
"_TZE200_ny94onlb",
"_TZE204_ny94onlb",
"_TZE284_ny94onlb",
}))
local power_meter_model_spm02v3={
profile="meters-energy-3phase-spm02v3",
package_group="meters",
tuya.dp_energy(1,{emit=emit.energy(),scale=100}),
tuya.dp_energy(23,{
name="produced_energy",
scale=100,
read_only=true,
emit=emit.spm02v3ProducedEnergy(),
}),
tuya.dp_power(29,{emit=emit.power()}),
tuya.dp_ac_frequency(32,{
name="ac_frequency",
read_only=true,
emit=emit.spm02v3AcFrequency(),
}),
tuya.dp_power_factor(50,{
name="power_factor",
read_only=true,
emit=emit.spm02v3PowerFactor(),
}),
tuya.dp_numeric(102,{name="update_frequency",emit=emit.spm02v3UpdateFrequency()}),
tuya.dp_voltage(103,{name="voltage_a",component="l1",emit=emit.voltage()}),
tuya.dp_current(104,{name="current_a",component="l1",emit=emit.current()}),
tuya.dp_power(105,{name="power_a",component="l1",emit=emit.power()}),
tuya.dp_power_factor(108,{name="power_factor_a"}),-- 프로파일 미포함
tuya.dp_energy(109,{name="energy_a",scale=100,component="l1",emit=emit.energy()}),
tuya.dp_energy(110,{name="energy_produced_a",scale=100}),-- 프로파일 미포함
tuya.dp_voltage(112,{name="voltage_b",component="l2",emit=emit.voltage()}),
tuya.dp_current(113,{name="current_b",component="l2",emit=emit.current()}),
tuya.dp_power(114,{name="power_b",component="l2",emit=emit.power()}),
tuya.dp_power_factor(117,{name="power_factor_b"}),-- 프로파일 미포함
tuya.dp_energy(118,{name="energy_b",scale=100,component="l2",emit=emit.energy()}),
tuya.dp_energy(119,{name="energy_produced_b",scale=100}),-- 프로파일 미포함
tuya.dp_voltage(121,{name="voltage_c",component="l3",emit=emit.voltage()}),
tuya.dp_current(122,{name="current_c",component="l3",emit=emit.current()}),
tuya.dp_power(123,{name="power_c",component="l3",emit=emit.power()}),
tuya.dp_power_factor(126,{name="power_factor_c"}),-- 프로파일 미포함
tuya.dp_energy(127,{name="energy_c",scale=100,component="l3",emit=emit.energy()}),
tuya.dp_energy(128,{name="energy_produced_c",scale=100}),-- 프로파일 미포함
}
register_device_definition(power_meter_model_spm02v3,device_helpers.create_fingerprints("TS0601",{
"_TZE200_dikb3dp6",
"_TZE204_dikb3dp6",
"_TZE284_dikb3dp6",
}))
local power_meter_model_spm02v1gt={
profile="meters-energy-3phase-spm02v1gt",
package_group="meters",
tuya.dp_energy(1,{emit=emit.energy(),scale=100}),
tuya.dp_energy(23,{
name="produced_energy",
scale=100,
read_only=true,
emit=emit.spm02v1gtProducedEnergy(),
}),
tuya.dp_phase_variant2(6,{
phase="a",
component="l1",
emit=emit_metric_bundle({voltage=true,current=true,power=true}),
}),
tuya.dp_phase_variant2(7,{
phase="b",
component="l2",
emit=emit_metric_bundle({voltage=true,current=true,power=true}),
}),
tuya.dp_phase_variant2(8,{
phase="c",
component="l3",
emit=emit_metric_bundle({voltage=true,current=true,power=true}),
}),
tuya.dp_power(29,{emit=emit.power()}),
tuya.dp_ac_frequency(32,{
name="ac_frequency",
read_only=true,
emit=emit.spm02v1gtAcFrequency(),
}),
tuya.dp_power_factor(50,{
name="power_factor",
read_only=true,
emit=emit.spm02v1gtPowerFactor(),
}),
tuya.dp_energy(53,{name="energy_a",scale=100,component="l1",emit=emit.energy()}),
tuya.dp_energy(54,{name="energy_b",scale=100,component="l2",emit=emit.energy()}),
tuya.dp_energy(55,{name="energy_c",scale=100,component="l3",emit=emit.energy()}),
tuya.dp_energy(57,{name="energy_produced_a",scale=100}),-- 프로파일 미포함
tuya.dp_energy(58,{name="energy_produced_b",scale=100}),-- 프로파일 미포함
tuya.dp_energy(59,{name="energy_produced_c",scale=100}),-- 프로파일 미포함
tuya.dp_on_off(101,{
name="device_locating",
emit=emit.spm02v1gtDeviceLocating(),
converter=converter.lookup_from_to({off=false,on=true}),
}),
tuya.dp_numeric(102,{name="update_frequency",emit=emit.spm02v1gtUpdateFrequency()}),
tuya.dp_power_factor(108,{name="power_factor_a"}),-- 프로파일 미포함
tuya.dp_power_factor(117,{name="power_factor_b"}),-- 프로파일 미포함
tuya.dp_power_factor(126,{name="power_factor_c"}),-- 프로파일 미포함
}
register_device_definition(power_meter_model_spm02v1gt,device_helpers.create_fingerprints("TS0601",{
"_TZE200_wjk6rurm",
"_TZE204_wjk6rurm",
"_TZE284_wjk6rurm",
}))
local power_meter_model_sdm01v1gt={
profile="meters-energy-3phase-sdm01v1gt",
package_group="meters",
tuya.dp_energy(1,{emit=emit.energy(),scale=100}),
tuya.dp_energy(23,{
name="produced_energy",
scale=100,
read_only=true,
emit=emit.sdm01v1gtProducedEnergy(),
}),
tuya.dp_phase_variant2(6,{
phase="a",
component="l1",
emit=emit_metric_bundle({voltage=true,current=true,power=true}),
}),
tuya.dp_phase_variant2(7,{
phase="b",
component="l2",
emit=emit_metric_bundle({voltage=true,current=true,power=true}),
}),
tuya.dp_phase_variant2(8,{
phase="c",
component="l3",
emit=emit_metric_bundle({voltage=true,current=true,power=true}),
}),
tuya.dp_power(29,{emit=emit.power()}),
tuya.dp_ac_frequency(32,{
name="ac_frequency",
read_only=true,
emit=emit.sdm01v1gtAcFrequency(),
}),
tuya.dp_power_factor(50,{
name="power_factor",
read_only=true,
emit=emit.sdm01v1gtPowerFactor(),
}),
tuya.dp_energy(53,{name="energy_a",scale=100,component="l1",emit=emit.energy()}),
tuya.dp_energy(54,{name="energy_b",scale=100,component="l2",emit=emit.energy()}),
tuya.dp_energy(55,{name="energy_c",scale=100,component="l3",emit=emit.energy()}),
tuya.dp_energy(57,{name="energy_produced_a",scale=100}),-- 프로파일 미포함
tuya.dp_energy(58,{name="energy_produced_b",scale=100}),-- 프로파일 미포함
tuya.dp_energy(59,{name="energy_produced_c",scale=100}),-- 프로파일 미포함
tuya.dp_on_off(101,{
name="device_locating",
emit=emit.sdm01v1gtDeviceLocating(),
converter=converter.lookup_from_to({off=false,on=true}),
}),
tuya.dp_numeric(102,{name="update_frequency",emit=emit.sdm01v1gtUpdateFrequency()}),
tuya.dp_power_factor(108,{name="power_factor_a"}),-- 프로파일 미포함
tuya.dp_power_factor(117,{name="power_factor_b"}),-- 프로파일 미포함
tuya.dp_power_factor(126,{name="power_factor_c"}),-- 프로파일 미포함
}
register_device_definition(power_meter_model_sdm01v1gt,device_helpers.create_fingerprints("TS0601",{
"_TZE200_s4sa1mcx",
"_TZE204_s4sa1mcx",
"_TZE284_s4sa1mcx",
}))
local power_meter_model_ts0601_3_phase_clamp_meter={
profile="meters-power-energy-voltage-current-clamp3phase",
package_group="meters",
tuya.dp_energy(1,{emit=emit.energy(),scale=100}),
tuya.dp_power(9,{emit=emit.power()}),
tuya.dp_energy(101,{name="energy_a",component="l1",scale=1000,emit=emit.energy()}),
tuya.dp_power_factor(102,{name="power_factor",component="l1",emit=emit.powerFactorClamp3PhasePercent()}),
tuya.dp_energy(111,{name="energy_b",component="l2",scale=1000,emit=emit.energy()}),
tuya.dp_power_factor(112,{name="power_factor",component="l2",emit=emit.powerFactorClamp3PhasePercent()}),
tuya.dp_energy(121,{name="energy_c",component="l3",scale=1000,emit=emit.energy()}),
tuya.dp_power_factor(122,{name="power_factor",component="l3",emit=emit.powerFactorClamp3PhasePercent()}),
tuya.dp_numeric(132,{name="ac_frequency",emit=emit.acFrequencyClamp3Phase()}),
tuya.dp_temperature(133,{
name="temperature",
scale=10,
read_only=true,
emit=emit.temperature(),
}),
tuya.dp_current(131,{emit=emit.current()}),
tuya.dp_phase_variant2(6,{
phase="a",
component="l1",
emit=emit_metric_bundle({voltage=true,current=true,power=true}),
}),
tuya.dp_phase_variant2(7,{
phase="b",
component="l2",
emit=emit_metric_bundle({voltage=true,current=true,power=true}),
}),
tuya.dp_phase_variant2(8,{
phase="c",
component="l3",
emit=emit_metric_bundle({voltage=true,current=true,power=true}),
}),
tuya.dp_numeric(134,{name="device_status"}),-- 프로파일 미포함
tuya.dp_ac_frequency(135,{
name="ac_frequency_high_precision",
read_only=true,
emit=emit.clamp3PhaseAcFreqHighPrecision(),
}),
}
register_device_definition(power_meter_model_ts0601_3_phase_clamp_meter,device_helpers.create_fingerprints("TS0601",{
"_TZE200_nslr42tt",
}))
register_device_definition(power_meter_model_ts0601_3_phase_clamp_meter,{
device_helpers.create_fingerprint("MatSee Plus","PC321-Z-TY"),
device_helpers.create_fingerprint("OWON","PC321-Z-TY"),
})
local power_meter_model_ts0601_3_phase_clamp_meter_relay={
profile="meters-switch-power-energy-clamp3phase-relay",
package_group="meters",
tuya.dp_energy(1,{emit=emit.energy(),scale=100}),
tuya.dp_energy(2,{
name="produced_energy",
scale=100,
read_only=true,
emit=emit.clamp3RelayProducedEnergy(),
}),
tuya.dp_on_off(16,{name="switch",emit=emit.switch()}),
tuya.dp_power(9,{emit=emit.power()}),
tuya.dp_phase_variant2(6,{
phase="a",
component="l1",
emit=emit_metric_bundle({voltage=true,current=true,power=true}),
}),
tuya.dp_phase_variant2(7,{
phase="b",
component="l2",
emit=emit_metric_bundle({voltage=true,current=true,power=true}),
}),
tuya.dp_phase_variant2(8,{
phase="c",
component="l3",
emit=emit_metric_bundle({voltage=true,current=true,power=true}),
}),
}
register_device_definition(power_meter_model_ts0601_3_phase_clamp_meter_relay,device_helpers.create_fingerprints("TS0601",{
"_TZE200_x8fp01wi",
"_TZE204_x8fp01wi",
}))
local power_meter_model_ts0601_bidirectional_energy_meter={
profile="meters-power-energy-voltage-current-bidirectional",
package_group="meters",
tuya.dp_energy(1,{emit=emit.energy(),scale=100}),
tuya.dp_energy(2,{name="produced_energy",scale=100,emit=emit.producedEnergyBidirectionalMeter()}),
tuya.dp_phase_variant3(6,{
emit=emit_metric_bundle({
voltage=true,
current=true,
power=true,
}),
}),
tuya.dp_enum(102,{name="energy_flow"}),-- 프로파일 미포함
}
register_device_definition(power_meter_model_ts0601_bidirectional_energy_meter,device_helpers.create_fingerprints("TS0601",{
"_TZE204_ac0fhfiq",
"_TZE284_ac0fhfiq",
}))
local power_meter_model_spm01={
profile="meters-energy-1phase-spm01",
package_group="meters",
tuya.dp_energy(1,{emit=emit.energy(),scale=100}),
tuya.dp_energy(2,{
name="produced_energy",
scale=100,
read_only=true,
emit=emit.spm01ProducedEnergy(),
}),
tuya.dp_phase_variant3(6,{
emit=emit_metric_bundle({voltage=true,current=true,power=true}),
}),
}
register_device_definition(power_meter_model_spm01,device_helpers.create_fingerprints("TS0601",{
"_TZE200_bcusnqt8",
}))
local power_meter_model_spm01v2={
profile="meters-energy-1phase-spm01v2",
package_group="meters",
tuya.dp_energy(1,{emit=emit.energy(),scale=100}),
tuya.dp_energy(2,{
name="produced_energy",
scale=100,
read_only=true,
emit=emit.spm01v2ProducedEnergy(),
}),
tuya.dp_power_factor(15,{
name="power_factor",
read_only=true,
emit=emit.spm01v2PowerFactor(),
}),
tuya.dp_raw(18,{name="data_report_duration"}),-- 프로파일 미포함
tuya.dp_ac_frequency(101,{
name="ac_frequency",
read_only=true,
emit=emit.spm01v2AcFrequency(),
}),
tuya.dp_voltage(102,{emit=emit.voltage()}),
tuya.dp_current(103,{emit=emit.current()}),
tuya.dp_power(104,{emit=emit.power()}),
}
register_device_definition(power_meter_model_spm01v2,device_helpers.create_fingerprints("TS0601",{
"_TZE200_qhlxve78",
"_TZE204_qhlxve78",
"_TZE284_qhlxve78",
}))
local power_meter_model_spm01v25={
profile="meters-energy-1phase-spm01v25",
package_group="meters",
tuya.dp_energy(1,{emit=emit.energy(),scale=100}),
tuya.dp_raw(18,{name="data_report_duration"}),-- 프로파일 미포함
tuya.dp_energy(23,{
name="produced_energy",
scale=100,
read_only=true,
emit=emit.spm01v25ProducedEnergy(),
}),
tuya.dp_ac_frequency(32,{
name="ac_frequency",
read_only=true,
emit=emit.spm01v25AcFrequency(),
}),
tuya.dp_power_factor(50,{
name="power_factor",
read_only=true,
emit=emit.spm01v25PowerFactor(),
}),
tuya.dp_voltage(102,{emit=emit.voltage()}),
tuya.dp_current(103,{emit=emit.current()}),
tuya.dp_power(104,{emit=emit.power()}),
}
register_device_definition(power_meter_model_spm01v25,device_helpers.create_fingerprints("TS0601",{
"_TZE200_iwn0gpzz",
"_TZE204_iwn0gpzz",
"_TZE284_iwn0gpzz",
}))
local power_meter_model_spm01v1gt={
profile="meters-energy-1phase-spm01v1gt",
package_group="meters",
tuya.dp_energy(1,{emit=emit.energy(),scale=100}),
tuya.dp_energy(23,{
name="produced_energy",
scale=100,
read_only=true,
emit=emit.spm01v1gtProducedEnergy(),
}),
tuya.dp_phase_variant3(6,{
emit=emit_metric_bundle({voltage=true,current=true,power=true}),
}),
tuya.dp_ac_frequency(32,{
name="ac_frequency",
read_only=true,
emit=emit.spm01v1gtAcFrequency(),
}),
tuya.dp_power_factor(50,{
name="power_factor",
read_only=true,
emit=emit.spm01v1gtPowerFactor(),
}),
tuya.dp_on_off(101,{
name="device_locating",
emit=emit.spm01v1gtDeviceLocating(),
converter=converter.lookup_from_to({off=false,on=true}),
}),
tuya.dp_numeric(102,{name="update_frequency",emit=emit.spm01v1gtUpdateFrequency()}),
}
register_device_definition(power_meter_model_spm01v1gt,device_helpers.create_fingerprints("TS0601",{
"_TZE200_d2zfgtij",
"_TZE204_d2zfgtij",
"_TZE284_d2zfgtij",
}))
local power_meter_model_pc311={
profile="meters-power-energy-voltage-current-pc311",
package_group="meters",
tuya.dp_energy(1,{emit=emit.energy(),scale=100}),
tuya.dp_energy(2,{
name="energy_produced",
scale=100,
read_only=true,
emit=emit.pc311ProducedEnergy(),
}),
tuya.dp_power(9,{emit=emit.power()}),
tuya.dp_energy(101,{name="energy_a",component="ct1",scale=100,emit=emit.energy()}),
tuya.dp_energy(103,{name="energy_b",component="ct2",scale=100,emit=emit.energy()}),
tuya.dp_energy(102,{
name="energy_produced_a",
component="ct1",
scale=100,
read_only=true,
emit=emit.pc311ProducedEnergy(),
}),
tuya.dp_energy(104,{
name="energy_produced_b",
component="ct2",
scale=100,
read_only=true,
emit=emit.pc311ProducedEnergy(),
}),
tuya.dp_current(105,{emit=emit.current(),scale=1000}),
tuya.dp_voltage(106,{emit=emit.voltage(),scale=10}),
tuya.dp_current(107,{name="current_a",component="ct1",scale=1000,emit=emit.current()}),
tuya.dp_power(108,{name="power_a",component="ct1",emit=emit.power()}),
tuya.dp_power_factor(109,{name="power_factor",component="ct1",emit=emit.powerFactorPc311Percent()}),
tuya.dp_current(110,{name="current_b",component="ct2",scale=1000,emit=emit.current()}),
tuya.dp_power(111,{name="power_b",component="ct2",emit=emit.power()}),
tuya.dp_power_factor(112,{name="power_factor",component="ct2",emit=emit.powerFactorPc311Percent()}),
tuya.dp_ac_frequency(113,{name="ac_frequency",emit=emit.acFrequencyPc311()}),
}
register_device_definition(power_meter_model_pc311,device_helpers.create_fingerprints("TS0601",{
"_TZE200_rks0sgb7",
}))
local power_meter_model_2ct={
profile="meters-power-energy-voltage-current-2ct",
package_group="meters",
tuya.dp_power(19,{emit=emit.power(),scale=10,read_only=true}),
tuya.dp_voltage(20,{emit=emit.voltage(),scale=10,read_only=true}),
tuya.dp_current(101,{name="current_a",component="ct1",scale=1000,emit=emit.current(),read_only=true}),
tuya.dp_current(102,{name="current_b",component="ct2",scale=1000,emit=emit.current(),read_only=true}),
tuya.dp_power(103,{name="power_a",component="ct1",scale=10,emit=emit.power(),read_only=true}),
tuya.dp_power(104,{name="power_b",component="ct2",scale=10,emit=emit.power(),read_only=true}),
tuya.dp_ac_frequency(105,{name="ac_frequency",scale=100,emit=emit.acFrequency2ct(),read_only=true}),
tuya.dp_energy(115,{name="energy_a",component="ct1",emit=emit.energy(),scale=100,read_only=true}),
tuya.dp_energy(117,{name="energy_b",component="ct2",emit=emit.energy(),scale=100,read_only=true}),
tuya.dp_power_factor(120,{name="power_factor",component="ct1",emit=emit.powerFactor2ctPercent(),read_only=true}),
tuya.dp_power_factor(121,{name="power_factor",component="ct2",emit=emit.powerFactor2ctPercent(),read_only=true}),
tuya.dp_numeric(122,{name="update_frequency",emit=emit.updateFrequency2ctSeconds60()}),
tuya.dp_numeric(123,{
name="calibration_voltage",
emit=emit.twoCtCalibrationVoltage(),
converter=converter.divide_by_pair(1000),
}),
tuya.dp_numeric(124,{
name="calibration_ac_frequency",
emit=emit.twoCtCalibrationAcFrequency(),
converter=converter.divide_by_pair(1000),
}),
tuya.dp_numeric(125,{
name="calibration_current_a",
emit=emit.twoCtCalibrationCurrentA(),
converter=converter.divide_by_pair(1000),
}),
tuya.dp_numeric(126,{
name="calibration_power_a",
emit=emit.twoCtCalibrationPowerA(),
converter=converter.divide_by_pair(1000),
}),
tuya.dp_numeric(130,{
name="calibration_current_b",
emit=emit.twoCtCalibrationCurrentB(),
converter=converter.divide_by_pair(1000),
}),
tuya.dp_numeric(131,{
name="calibration_power_b",
emit=emit.twoCtCalibrationPowerB(),
converter=converter.divide_by_pair(1000),
}),
}
register_device_definition(power_meter_model_2ct,device_helpers.create_fingerprints("TS0601",{
"_TZE204_dhotiauw",
}))
local power_meter_model_pj1203a={
profile="meters-power-energy-voltage-current-pj1203a",
package_group="meters",
tuya.dp_ac_frequency(111,{
name="ac_frequency",
read_only=true,
emit=emit.pj1203aAcFrequency(),
}),
tuya.dp_voltage(112,{emit=emit.voltage()}),
tuya.dp_power(101,{name="power_a",component="ct1",scale=10,emit=emit.power()}),
tuya.dp_power(105,{name="power_b",component="ct2",scale=10,emit=emit.power()}),
tuya.dp_current(113,{name="current_a",component="ct1",scale=1000,emit=emit.current()}),
tuya.dp_current(114,{name="current_b",component="ct2",scale=1000,emit=emit.current()}),
tuya.dp_power_factor(110,{
name="power_factor_a",
component="ct1",
read_only=true,
emit=emit.pj1203aPowerFactor(),
}),
tuya.dp_power_factor(121,{
name="power_factor_b",
component="ct2",
read_only=true,
emit=emit.pj1203aPowerFactor(),
}),
tuya.dp_energy(106,{name="energy_a",component="ct1",scale=100,emit=emit.energy()}),
tuya.dp_energy(108,{name="energy_b",component="ct2",scale=100,emit=emit.energy()}),
tuya.dp_energy(107,{
name="energy_produced_a",
component="ct1",
scale=100,
read_only=true,
emit=emit.pj1203aProducedEnergy(),
}),
tuya.dp_energy(109,{
name="energy_produced_b",
component="ct2",
scale=100,
read_only=true,
emit=emit.pj1203aProducedEnergy(),
}),
tuya.dp_numeric(102,{name="energy_flow_a"}),-- profile 미포함
tuya.dp_numeric(104,{name="energy_flow_b"}),-- profile 미포함
tuya.dp_power(115,{name="power_ab"}),-- profile 미포함
tuya.dp_numeric(129,{name="update_frequency",emit=emit.updateFrequencyPj1203aSeconds60()}),
}
register_device_definition(power_meter_model_pj1203a,device_helpers.create_fingerprints("TS0601",{
"_TZE204_81yrt3lo",
"_TZE284_81yrt3lo",
"_TZE28C1000000_81yrt3lo",
}))
local power_meter_model_atms10013z3={
profile="meters-energy-3phase-atms10013z3",
package_group="meters",
tuya.dp_energy(1,{emit=emit.energy(),scale=100}),
tuya.dp_phase_variant2(6,{
phase="a",
component="l1",
emit=emit_metric_bundle({voltage=true,current=true,power=true}),
}),
tuya.dp_phase_variant2(7,{
phase="b",
component="l2",
emit=emit_metric_bundle({voltage=true,current=true,power=true}),
}),
tuya.dp_phase_variant2(8,{
phase="c",
component="l3",
emit=emit_metric_bundle({voltage=true,current=true,power=true}),
}),
tuya.dp_energy(23,{
name="produced_energy",
scale=100,
read_only=true,
emit=emit.atms10013z3ProducedEnergy(),
}),
tuya.dp_energy(24,{
name="total_energy",
scale=100,
read_only=true,
emit=emit.atms10013z3TotalEnergy(),
}),
tuya.dp_power(29,{emit=emit.power(),scale=1}),
tuya.dp_numeric(30,{name="power_reactive",emit=emit.reactivePowerAtms10013z3()}),
tuya.dp_power_factor(50,{
name="power_factor",
read_only=true,
emit=emit.atms10013z3PowerFactor(),
}),
}
register_device_definition(power_meter_model_atms10013z3,{
device_helpers.create_fingerprint("_TZE284_a14rjslz","TS0601"),
device_helpers.create_fingerprint("Ourtop","ATMS100133Z"),
})
local power_meter_model_to_q_sa1={
profile="meters-power-energy-voltage-current-toqsa1",
package_group="meters",
tuya.dp_energy(1,{emit=emit.energy(),scale=100}),
tuya.dp_phase_variant2(6,{
emit=emit_metric_bundle({
voltage=true,
current=true,
power=true,
}),
}),
tuya.dp_numeric(13,{name="test1"}),-- 프로파일 미포함
tuya.dp_ac_frequency(32,{
name="ac_frequency",
read_only=true,
emit=emit.toqsa1AcFrequency(),
}),
tuya.dp_power_factor(50,{
name="power_factor",
read_only=true,
emit=emit.toqsa1PowerFactor(),
}),
tuya.dp_enum(102,{
name="over_voltage_setting",
emit=emit.toqsa1OverVoltageSetting(),
converter=converter.lookup_from_to(IGNORE_ALARM_SETTING),
}),
tuya.dp_enum(103,{
name="under_voltage_setting",
emit=emit.toqsa1UnderVoltageSetting(),
converter=converter.lookup_from_to(IGNORE_ALARM_SETTING),
}),
tuya.dp_enum(104,{
name="over_current_setting",
emit=emit.toqsa1OverCurrentSetting(),
converter=converter.lookup_from_to(IGNORE_ALARM_SETTING),
}),
tuya.dp_enum(105,{
name="over_power_setting",
emit=emit.toqsa1OverPowerSetting(),
converter=converter.lookup_from_to(IGNORE_ALARM_SETTING),
}),
tuya.dp_enum(107,{
name="temperature_setting",
emit=emit.toqsa1TemperatureSetting(),
converter=converter.lookup_from_to(IGNORE_ALARM_SETTING),
}),
tuya.dp_enum(110,{
name="event",
read_only=true,
emit=emit.toqsa1Event(),
converter=converter.from_only(converter.lookup_value(BREAKER_EVENT_LOOKUP)),
}),
tuya.dp_numeric(114,{name="over_current_threshold",emit=emit.toqsa1OverCurrentThreshold()}),
tuya.dp_numeric(115,{name="over_voltage_threshold",emit=emit.toqsa1OverVoltageThreshold()}),
tuya.dp_numeric(116,{name="under_voltage_threshold",emit=emit.toqsa1UnderVoltageThreshold()}),
tuya.dp_temperature(118,{
name="temperature_threshold",
scale=10,
emit=emit.toqsa1TemperatureThreshold(),
}),
tuya.dp_numeric(119,{name="over_power_threshold",emit=emit.toqsa1OverPowerThreshold()}),
tuya.dp_numeric(125,{name="forward_electricity"}),-- 프로파일 미포함
tuya.dp_temperature(131,{
name="temperature",
scale=10,
read_only=true,
emit=emit.temperature(),
}),
}
register_device_definition(power_meter_model_to_q_sa1,device_helpers.create_fingerprints("TS0601",{
"_TZE284_4hdbt6rn",
"_TZE284_pglpvdar",
}))
register_device_definition(power_meter_model_to_q_sa1,{
device_helpers.create_fingerprint("Tongou","TOSA1-01WXJAT2A"),
})
local power_meter_model_pj_mgw1203={
profile="meters-power-energy-voltage-current",
package_group="meters",
tuya.dp_current(18,{emit=emit.current(),scale=1000}),
tuya.dp_power(19,{emit=emit.power(),scale=10}),
tuya.dp_voltage(20,{emit=emit.voltage(),scale=10}),
tuya.dp_energy(101,{emit=emit.energy(),scale=1000}),
}
register_device_definition(power_meter_model_pj_mgw1203,device_helpers.create_fingerprints("TS0601",{
"_TZE204_cjbofhxw",
"_TZE284_cjbofhxw",
}))
register_device_definition(power_meter_model_pj_mgw1203,{
device_helpers.create_fingerprint("Tuya","PJ-1203-W"),
})
local power_meter_model_sdm02v1={
profile="meters-power-energy-2phase-sdm02v1",
package_group="meters",
tuya.dp_energy(1,{emit=emit.energy(),scale=100}),
tuya.dp_energy(23,{name="produced_energy",scale=100}),-- 프로파일 미포함
tuya.dp_power(29,{emit=emit.power(),scale=1}),
tuya.dp_ac_frequency(32,{}),-- 프로파일 미포함
tuya.dp_power_factor(50,{}),-- 프로파일 미포함
tuya.dp_numeric(102,{name="update_frequency",emit=emit.updateFrequencySdm02v1Seconds3600()}),
tuya.dp_voltage(103,{name="voltage_l1",component="l1",emit=emit.voltage()}),
tuya.dp_current(104,{name="current_l1",component="l1",emit=emit.current()}),
tuya.dp_power(105,{name="power_l1",component="l1",emit=emit.power(),scale=1}),
tuya.dp_power_factor(108,{name="power_factor_l1"}),-- 프로파일 미포함
tuya.dp_energy(109,{name="energy_l1",component="l1",emit=emit.energy(),scale=100}),
tuya.dp_energy(110,{name="energy_produced_l1",scale=100}),-- 프로파일 미포함
tuya.dp_voltage(112,{name="voltage_l2",component="l2",emit=emit.voltage()}),
tuya.dp_current(113,{name="current_l2",component="l2",emit=emit.current()}),
tuya.dp_power(114,{name="power_l2",component="l2",emit=emit.power(),scale=1}),
tuya.dp_power_factor(117,{name="power_factor_l2"}),-- 프로파일 미포함
tuya.dp_energy(118,{name="energy_l2",component="l2",emit=emit.energy(),scale=100}),
tuya.dp_energy(119,{name="energy_produced_l2",scale=100}),-- 프로파일 미포함
}
register_device_definition(power_meter_model_sdm02v1,device_helpers.create_fingerprints("TS0601",{
"_TZE204_78ioiaml",
"_TZE284_78ioiaml",
"_TZE200_78ioiaml",
}))
local power_meter_model_sdm02v1gt={
profile="meters-energy-2phase-sdm02v1gt",
package_group="meters",
tuya.dp_energy(1,{emit=emit.energy(),scale=100}),
tuya.dp_energy(23,{
name="produced_energy",
scale=100,
read_only=true,
emit=emit.sdm02v1gtProducedEnergy(),
}),
tuya.dp_phase_variant2(6,{
phase="l1",
component="l1",
emit=emit_metric_bundle({voltage=true,current=true,power=true}),
}),
tuya.dp_phase_variant2(7,{
phase="l2",
component="l2",
emit=emit_metric_bundle({voltage=true,current=true,power=true}),
}),
tuya.dp_power(29,{emit=emit.power()}),
tuya.dp_ac_frequency(32,{
name="ac_frequency",
read_only=true,
emit=emit.sdm02v1gtAcFrequency(),
}),
tuya.dp_power_factor(50,{
name="power_factor",
read_only=true,
emit=emit.sdm02v1gtPowerFactor(),
}),
tuya.dp_energy(53,{name="energy_l1",scale=100,component="l1",emit=emit.energy()}),
tuya.dp_energy(54,{name="energy_produced_l1",scale=100}),-- 프로파일 미포함
tuya.dp_energy(57,{name="energy_l2",scale=100,component="l2",emit=emit.energy()}),
tuya.dp_energy(58,{name="energy_produced_l2",scale=100}),-- 프로파일 미포함
tuya.dp_on_off(101,{
name="device_locating",
emit=emit.sdm02v1gtDeviceLocating(),
converter=converter.lookup_from_to({off=false,on=true}),
}),
tuya.dp_numeric(102,{name="update_frequency",emit=emit.sdm02v1gtUpdateFrequency()}),
tuya.dp_power_factor(108,{name="power_factor_l1"}),-- 프로파일 미포함
tuya.dp_power_factor(117,{name="power_factor_l2"}),-- 프로파일 미포함
}
register_device_definition(power_meter_model_sdm02v1gt,device_helpers.create_fingerprints("TS0601",{
"_TZE200_x8diwkqb",
"_TZE204_x8diwkqb",
"_TZE284_x8diwkqb",
}))
local power_meter_model_sdm01v15={
profile="meters-energy-3phase-sdm01v15",
package_group="meters",
tuya.dp_energy(1,{emit=emit.energy(),scale=100}),
tuya.dp_energy(23,{
name="produced_energy",
scale=100,
read_only=true,
emit=emit.sdm01v15ProducedEnergy(),
}),
tuya.dp_power(29,{emit=emit.power(),scale=1}),
tuya.dp_ac_frequency(32,{
name="ac_frequency",
read_only=true,
emit=emit.sdm01v15AcFrequency(),
}),
tuya.dp_power_factor(50,{
name="power_factor",
read_only=true,
emit=emit.sdm01v15PowerFactor(),
}),
tuya.dp_numeric(102,{name="update_frequency",emit=emit.sdm01v15UpdateFrequency()}),
tuya.dp_voltage(103,{name="voltage_a",component="l1",emit=emit.voltage(),scale=10}),
tuya.dp_current(104,{name="current_a",component="l1",emit=emit.current(),scale=1000}),
tuya.dp_power(105,{name="power_a",component="l1",emit=emit.power(),scale=1}),
tuya.dp_power_factor(108,{name="power_factor_a"}),-- 프로파일 미포함
tuya.dp_energy(109,{name="energy_a",scale=100,component="l1",emit=emit.energy()}),
tuya.dp_energy(110,{name="energy_produced_a",scale=100}),-- 프로파일 미포함
tuya.dp_voltage(112,{name="voltage_b",component="l2",emit=emit.voltage(),scale=10}),
tuya.dp_current(113,{name="current_b",component="l2",emit=emit.current(),scale=1000}),
tuya.dp_power(114,{name="power_b",component="l2",emit=emit.power(),scale=1}),
tuya.dp_power_factor(117,{name="power_factor_b"}),-- 프로파일 미포함
tuya.dp_energy(118,{name="energy_b",scale=100,component="l2",emit=emit.energy()}),
tuya.dp_energy(119,{name="energy_produced_b",scale=100}),-- 프로파일 미포함
tuya.dp_voltage(121,{name="voltage_c",component="l3",emit=emit.voltage(),scale=10}),
tuya.dp_current(122,{name="current_c",component="l3",emit=emit.current(),scale=1000}),
tuya.dp_power(123,{name="power_c",component="l3",emit=emit.power(),scale=1}),
tuya.dp_power_factor(126,{name="power_factor_c"}),-- 프로파일 미포함
tuya.dp_energy(127,{name="energy_c",scale=100,component="l3",emit=emit.energy()}),
tuya.dp_energy(128,{name="energy_produced_c",scale=100}),-- 프로파일 미포함
}
register_device_definition(power_meter_model_sdm01v15,device_helpers.create_fingerprints("TS0601",{
"_TZE204_gomuk3dc",
"_TZE284_gomuk3dc",
"_TZE200_gomuk3dc",
}))
return{
id="ef00.din_rail.meters",
registrations=device_definitions,
}
