name: safety-contact-battery-low-battery-voltage
components:
  - id: main
    capabilities:
      - id: contactSensor
        version: 1
      - id: concertmirror08464.batteryLow
        version: 1
      - id: battery
        version: 1
      - id: voltageMeasurement
        version: 1
      - id: refresh
        version: 1
    categories:
      - name: ContactSensor
