zigbeeManufacturer:
  - id: "fp_3c3fa25f37"
    manufacturer: "Nova Digital"
    model: "ZVL-DUAL"
    deviceProfileName: "valves-valve-2-battery-status"
  - id: "fp_e5c0a21f93"
    manufacturer: "_TZE200_1n2zev06"
    model: "TS0601"
    deviceProfileName: "valves-valve"
  - id: "fp_b5b612c798"
    manufacturer: "_TZE200_2wg5qrjy"
    model: "TS0601"
    deviceProfileName: "valves-valve-battery"
  - id: "fp_534188ca9a"
    manufacturer: "_TZE200_5uodvhgc"
    model: "TS0601"
    deviceProfileName: "valves-valve"
  - id: "fp_104be22140"
    manufacturer: "_TZE200_81isopgh"
    model: "TS0601"
    deviceProfileName: "valves-valve-battery"
  - id: "fp_dadaf9b837"
    manufacturer: "_TZE200_akjefhj5"
    model: "TS0601"
    deviceProfileName: "valves-valve-battery"
  - id: "fp_cf45817f25"
    manufacturer: "_TZE200_fphxkxue"
    model: "TS0601"
    deviceProfileName: "valves-valve-battery"
  - id: "fp_8b9073afb0"
    manufacturer: "_TZE200_hbnfokum"
    model: "TS0601"
    deviceProfileName: "valves-valve-position-hbnfokum"
  - id: "fp_ec9ef698b4"
    manufacturer: "_TZE200_vuwtqx0t"
    model: "TS0601"
    deviceProfileName: "valves-valve-ultrasonic-meter"
  - id: "fp_b0de2b1cc7"
    manufacturer: "_TZE200_wt9agwf3"
    model: "TS0601"
    deviceProfileName: "valves-valve"
  - id: "fp_5ab971f9de"
    manufacturer: "_TZE204_dsagrkvg"
    model: "TS0601"
    deviceProfileName: "valves-valve-battery"
  - id: "fp_dffb506fcc"
    manufacturer: "_TZE284_8zizsafo"
    model: "TS0601"
    deviceProfileName: "valves-valve-2-battery-status"
  - id: "fp_b5ca1a2cb7"
    manufacturer: "_TZE284_eaet5qt5"
    model: "TS0601"
    deviceProfileName: "valves-valve-2-battery-status"
  - id: "fp_c8e85c014a"
    manufacturer: "_TZE284_fhvpaltk"
    model: "TS0601"
    deviceProfileName: "valves-valve-2-battery-status"
  - id: "fp_e49badadfb"
    manufacturer: "_TZE284_iilebqoo"
    model: "TS0601"
    deviceProfileName: "valves-valve-2-battery-status"
  - id: "fp_d9df11c7bb"
    manufacturer: "_TZE284_vuwtqx0t"
    model: "TS0601"
    deviceProfileName: "valves-valve-ultrasonic-meter"
  - id: "fp_ef75d4b859"
    manufacturer: "_TZE284_zm8zpwas"
    model: "TS0601"
    deviceProfileName: "valves-valve-battery"
