name: safety-water-lincukoo-w04-z10t-battery-ringtone
components:
  - id: main
    capabilities:
      - {id: concertmirror08464.lincukooWFourAlarmStatus, version: 1}
      - {id: concertmirror08464.lincukooWFourAlarmSwitch, version: 1}
      - {id: concertmirror08464.lincukooWFourRingtone, version: 1}
      - {id: battery, version: 1}
    categories: [{name: LeakSensor}]
deviceConfig:
  dashboard:
    states:
      - {component: main, capability: concertmirror08464.lincukooWFourAlarmStatus, version: 1, group: main}
      - {component: main, capability: battery, version: 1, group: main}
    actions: []
    basicPlus: []
  detailView:
    - {component: main, capability: concertmirror08464.lincukooWFourAlarmStatus, version: 1}
    - {component: main, capability: concertmirror08464.lincukooWFourAlarmSwitch, version: 1}
    - {component: main, capability: concertmirror08464.lincukooWFourRingtone, version: 1}
    - {component: main, capability: battery, version: 1}
  automation:
    conditions:
      - {component: main, capability: concertmirror08464.lincukooWFourAlarmStatus, version: 1}
      - {component: main, capability: concertmirror08464.lincukooWFourAlarmSwitch, version: 1}
      - {component: main, capability: concertmirror08464.lincukooWFourRingtone, version: 1}
      - {component: main, capability: battery, version: 1}
    actions:
      - {component: main, capability: concertmirror08464.lincukooWFourAlarmSwitch, version: 1}
      - {component: main, capability: concertmirror08464.lincukooWFourRingtone, version: 1}
