name: controllers-ir-transceiver
components:
  - id: main
    capabilities:
      - id: concertmirror08464.learnIrCode
        version: 1
      - id: concertmirror08464.learnedIrCode
        version: 1
      - id: concertmirror08464.irCodeToSend
        version: 1
      - id: refresh
        version: 1
    categories:
      - name: RemoteController
