name: scene-switches-1-advanced
components:
  - id: main
    capabilities:
      - id: switch
        version: 1
      - id: button
        version: 1
      - id: concertmirror08464.powerOnBehavior
        version: 1
      - id: concertmirror08464.switchMode
        version: 1
      - id: concertmirror08464.indicatorMode
        version: 1
      - id: refresh
        version: 1
    categories:
      - name: Switch
