zigbeeManufacturer:
  - id: "fp_8b67fc1285"
    manufacturer: "_TZE200_7a5ob7xq"
    model: "TS0601"
    deviceProfileName: "switches-switch-8"
  - id: "fp_9c0222edb9"
    manufacturer: "_TZE200_9dhenr94"
    model: "TS0601"
    deviceProfileName: "switches-moes-sfl02-z4"
  - id: "fp_23d12f8512"
    manufacturer: "_TZE200_b0ihkhxh"
    model: "TS0601"
    deviceProfileName: "switches-switch-4"
  - id: "fp_89f270a971"
    manufacturer: "_TZE200_dq8bu0pt"
    model: "TS0601"
    deviceProfileName: "switches-moes-sfl02-z4"
  - id: "fp_8f796ae125"
    manufacturer: "_TZE200_hktk6hze"
    model: "TS0601"
    deviceProfileName: "switches-moes-sfl02-z2"
  - id: "fp_8c023ac9c8"
    manufacturer: "_TZE200_hmabvy81"
    model: "TS0601"
    deviceProfileName: "switches-moes-sfl02-z4"
  - id: "fp_b5e3fbb4c4"
    manufacturer: "_TZE200_htj3hcpl"
    model: "TS0601"
    deviceProfileName: "switches-switch-6"
  - id: "fp_8b71375800"
    manufacturer: "_TZE200_o7vduidq"
    model: "TS0601"
    deviceProfileName: "switches-wave15-box-erc2202z"
  - id: "fp_7a715cdb0c"
    manufacturer: "_TZE200_pcg0rykt"
    model: "TS0601"
    deviceProfileName: "switches-switch-7"
  - id: "fp_644d7b86fe"
    manufacturer: "_TZE200_rd8cdssd"
    model: "TS0601"
    deviceProfileName: "switches-moes-sfl02-z3"
  - id: "fp_c595c6fe9e"
    manufacturer: "_TZE200_rgeapp2c"
    model: "TS0601"
    deviceProfileName: "switches-wave13-tuya-semicom-two-two"
  - id: "fp_9962dd3ce1"
    manufacturer: "_TZE200_stvgmdjz"
    model: "TS0601"
    deviceProfileName: "switches-moes-sfl02-z1"
  - id: "fp_1138a064e3"
    manufacturer: "_TZE200_tzyy0rtq"
    model: "TS0601"
    deviceProfileName: "switches-moes-sfl02-z2"
  - id: "fp_fc07b8ea8f"
    manufacturer: "_TZE200_uenof8jd"
    model: "TS0601"
    deviceProfileName: "switches-moes-sfl02-z2"
  - id: "fp_903c95f6e4"
    manufacturer: "_TZE200_wv9ukqca"
    model: "TS0601"
    deviceProfileName: "switches-moes-sfl02-z3"
  - id: "fp_896db301b5"
    manufacturer: "_TZE200_xo3vpoah"
    model: "TS0601"
    deviceProfileName: "switches-switch-10"
  - id: "fp_d6956fb89b"
    manufacturer: "_TZE200_ydkqbmpt"
    model: "TS0601"
    deviceProfileName: "switches-moes-sfl02-z1"
  - id: "fp_107762f40b"
    manufacturer: "_TZE200_yp5tsi3y"
    model: "TS0601"
    deviceProfileName: "switches-wave13-box-ews1154z"
  - id: "fp_d193134b4b"
    manufacturer: "_TZE200_z3u99qxt"
    model: "TS0601"
    deviceProfileName: "switches-moes-sfl02-z1"
  - id: "fp_b3903bd814"
    manufacturer: "_TZE200_zo0cfekv"
    model: "TS0601"
    deviceProfileName: "switches-moes-sfl02-z3"
  - id: "fp_fa984e9518"
    manufacturer: "_TZE204_3ctwoaip"
    model: "TS0601"
    deviceProfileName: "switches-screen-zms206eu2"
  - id: "fp_932cfea7a6"
    manufacturer: "_TZE204_4cl0dzt4"
    model: "TS0601"
    deviceProfileName: "switches-wave14-qa-qat44z6h"
  - id: "fp_2ed3ce5c28"
    manufacturer: "_TZE204_8eazvzo6"
    model: "TS0601"
    deviceProfileName: "switches-switch-6"
  - id: "fp_5dae0565a6"
    manufacturer: "_TZE204_iyki9kjp"
    model: "TS0601"
    deviceProfileName: "switches-screen-zms206eu3"
  - id: "fp_7f3c25d7bf"
    manufacturer: "_TZE204_k7v0eqke"
    model: "TS0601"
    deviceProfileName: "switches-screen-zms206eu3"
  - id: "fp_f51e1a0155"
    manufacturer: "_TZE204_kyzjsjo3"
    model: "TS0601"
    deviceProfileName: "switches-wave14-qa-qat44z4h"
  - id: "fp_c00105199c"
    manufacturer: "_TZE204_sa2ueffe"
    model: "TS0601"
    deviceProfileName: "switches-screen-zms206us1"
  - id: "fp_f0267a5c86"
    manufacturer: "_TZE204_zuepxzck"
    model: "TS0601"
    deviceProfileName: "switches-screen-zms206us1"
  - id: "fp_38a1346655"
    manufacturer: "_TZE284_3ctwoaip"
    model: "TS0601"
    deviceProfileName: "switches-screen-zms206eu2"
  - id: "fp_6d6acb9ad9"
    manufacturer: "_TZE284_3xnyj4ga"
    model: "TS0601"
    deviceProfileName: "switches-wave13-nova-to-wk-one"
  - id: "fp_b7fdc31cfa"
    manufacturer: "_TZE284_59dz7ioi"
    model: "TS0601"
    deviceProfileName: "switches-wave13-manhot-mh03-3"
  - id: "fp_9eede8c8bc"
    manufacturer: "_TZE284_7a5ob7xq"
    model: "TS0601"
    deviceProfileName: "switches-switch-8"
  - id: "fp_afda3a8f4d"
    manufacturer: "_TZE284_a2teqi5u"
    model: "TS0601"
    deviceProfileName: "switches-screen-zms208us2"
  - id: "fp_ebc6ec9c4c"
    manufacturer: "_TZE284_dmckrsxg"
    model: "TS0601"
    deviceProfileName: "switches-screen-zms206eu2"
  - id: "fp_dc9ffe253b"
    manufacturer: "_TZE284_dnhhp8ew"
    model: "TS0601"
    deviceProfileName: "switches-wave13-manhot-mh03-2"
  - id: "fp_d80c4d3869"
    manufacturer: "_TZE284_e4pf6l87"
    model: "TS0601"
    deviceProfileName: "switches-screen-zms206eu3"
  - id: "fp_8a64954cc4"
    manufacturer: "_TZE284_esnu2jxv"
    model: "TS0601"
    deviceProfileName: "switches-wave13-manhot-mh03-4"
  - id: "fp_3feb2c8fef"
    manufacturer: "_TZE284_exfilann"
    model: "TS0601"
    deviceProfileName: "switches-wave13-nova-to-wk-two"
  - id: "fp_fc95fd5847"
    manufacturer: "_TZE284_hwv3by9k"
    model: "TS0601"
    deviceProfileName: "switches-wave13-manhot-mh03-8"
  - id: "fp_b8c71f9be9"
    manufacturer: "_TZE284_k7v0eqke"
    model: "TS0601"
    deviceProfileName: "switches-screen-zms206eu3"
  - id: "fp_40745b0169"
    manufacturer: "_TZE284_lnyz4a6v"
    model: "TS0601"
    deviceProfileName: "switches-screen-zms206us1"
  - id: "fp_96698cb413"
    manufacturer: "_TZE284_ncc7uahd"
    model: "TS0601"
    deviceProfileName: "switches-wave13-manhot-mh03-1"
  - id: "fp_6f2670d8be"
    manufacturer: "_TZE284_nzns7udm"
    model: "TS0601"
    deviceProfileName: "switches-switch-1-scene-qa-qat42z1b"
  - id: "fp_40f4f9d1bd"
    manufacturer: "_TZE284_udaucpdi"
    model: "TS0601"
    deviceProfileName: "switches-wave13-avatto-zbs16"
  - id: "fp_1e22e85e02"
    manufacturer: "_TZE284_xvywzhmi"
    model: "TS0601"
    deviceProfileName: "switches-screen-zms208us3"
  - id: "fp_482df0175b"
    manufacturer: "_TZE284_zykra2yj"
    model: "TS0601"
    deviceProfileName: "switches-wave13-manhot-mh03-6"
  - id: "fp_27f713594b"
    manufacturer: "_TZE28C1000000_e4pf6l87"
    model: "TS0601"
    deviceProfileName: "switches-screen-zms206eu3"
  - id: "fp_42cf860da6"
    manufacturer: "_TZE28C1000000_xvywzhmi"
    model: "TS0601"
    deviceProfileName: "switches-screen-zms208us3"
