name: switches-switch-1-temp-humidity
components:
  - id: main
    capabilities:
      - id: switch
        version: 1
      - id: temperatureMeasurement
        version: 1
      - id: relativeHumidityMeasurement
        version: 1
      - id: refresh
        version: 1
    categories:
      - name: Switch
deviceConfig:
  dashboard:
    states:
      - component: main
        capability: switch
        version: 1
        group: main
        composite: true
    actions:
      - component: main
        capability: switch
        version: 1
        group: main
        values:
          - command: "on"
          - command: "off"
    basicPlus: []
  detailView:
    - component: main
      capability: switch
      version: 1
    - component: main
      capability: temperatureMeasurement
      version: 1
    - component: main
      capability: relativeHumidityMeasurement
      version: 1
    - component: main
      capability: refresh
      version: 1
  automation:
    conditions:
      - component: main
        capability: switch
        version: 1
      - component: main
        capability: temperatureMeasurement
        version: 1
      - component: main
        capability: relativeHumidityMeasurement
        version: 1
    actions:
      - component: main
        capability: switch
        version: 1
