zigbeeManufacturer:
  - id: fp_a8a4452fba
    manufacturer: "_TZE200_4hbx5cvx"
    model: "TS0601"
    deviceProfileName: "thermostats-wave6a-futurehome"
  - id: fp_b7606d0df4
    manufacturer: "_TZE200_awnadkan"
    model: "TS0601"
    deviceProfileName: "thermostats-wave6a-engo-eone230w"
  - id: fp_5d500aa315
    manufacturer: "_TZE200_e5hpkc6d"
    model: "TS0601"
    deviceProfileName: "thermostats-wave6a-futurehome"
  - id: fp_9746e8fa9e
    manufacturer: "_TZE200_gtouvmvl"
    model: "TS0601"
    deviceProfileName: "thermostats-wave12-engo-eone-batb"
  - id: fp_550ecb0f7a
    manufacturer: "_TZE204_ca3i8m8p"
    model: "TS0601"
    deviceProfileName: "thermostats-wave6a-engo-eone230w"
  - id: fp_e9847854ea
    manufacturer: "_TZE204_cg8hdnjv"
    model: "TS0601"
    deviceProfileName: "thermostats-wave12-engo-e25-batb"
  - id: fp_bdf094ca86
    manufacturer: "_TZE204_cmyc8g5i"
    model: "TS0601"
    deviceProfileName: "thermostats-wave12-engo-e25-230"
  - id: fp_e7a4b38c77
    manufacturer: "_TZE204_djurk6p5"
    model: "TS0601"
    deviceProfileName: "thermostats-wave12-engo-eone"
  - id: fp_80bc1943a3
    manufacturer: "_TZE204_e5hpkc6d"
    model: "TS0601"
    deviceProfileName: "thermostats-wave6a-futurehome"
  - id: fp_07b8142a49
    manufacturer: "_TZE204_glk6viwg"
    model: "TS0601"
    deviceProfileName: "thermostats-wave6a-engo-e40"
  - id: fp_3c9e2d4aa7
    manufacturer: "_TZE204_hpkusvom"
    model: "TS0601"
    deviceProfileName: "thermostats-wave12-tuya-bac001"
  - id: fp_ac5d7de91b
    manufacturer: "_TZE204_lnxdk2ch"
    model: "TS0601"
    deviceProfileName: "thermostats-wave6a-engo-e40"
  - id: fp_2ce7b4fc5a
    manufacturer: "_TZE204_lpedvtvr"
    model: "TS0601"
    deviceProfileName: "thermostats-wave12-moes-zht-sr"
  - id: fp_5b66fe841e
    manufacturer: "_TZE204_p3lqqy2r"
    model: "TS0601"
    deviceProfileName: "thermostats-wave12-namron-touch"
  - id: fp_c2b101e897
    manufacturer: "_TZE204_x9usygq1"
    model: "TS0601"
    deviceProfileName: "thermostats-wave12-moes-pilot"
  - id: fp_9da7fe0c85
    manufacturer: "_TZE204_zxkwaztm"
    model: "TS0601"
    deviceProfileName: "thermostats-wave12-moes-zht-s03"
  - id: fp_43e9619eab
    manufacturer: "_TZE284_4cgmagba"
    model: "TS0601"
    deviceProfileName: "thermostats-wave12-beca-bht209"
  - id: fp_7d4882dec6
    manufacturer: "_TZE284_rlytpmij"
    model: "TS0601"
    deviceProfileName: "thermostats-wave12-moes-zht-s01"
