name: safety-presence-zf24-move-illuminance
components:
  - id: main
    capabilities:
      - id: presenceSensor
        version: 1
      - id: concertmirror08464.zf24PresenceSensitivity
        version: 1
      - id: concertmirror08464.zf24MoveSensitivity
        version: 1
      - id: concertmirror08464.zf24DetectionDistanceMax
        version: 1
      - id: concertmirror08464.zf24PresenceTimeout
        version: 1
      - id: concertmirror08464.zf24Distance
        version: 1
      - id: concertmirror08464.zf24RadarSwitch
        version: 1
      - id: concertmirror08464.zf24Function
        version: 1
      - id: concertmirror08464.zf24LivingRoom
        version: 1
      - id: concertmirror08464.zf24Bedroom
        version: 1
      - id: concertmirror08464.zf24Bathroom
        version: 1
      - id: concertmirror08464.zf24Sleep
        version: 1
      - id: concertmirror08464.driverMessage
        version: 1
      - id: illuminanceMeasurement
        version: 1
      - id: refresh
        version: 1
    categories:
      - name: PresenceSensor
deviceConfig:
  dashboard:
    states:
      - component: main
        capability: presenceSensor
        version: 1
        group: main
    actions: []
    basicPlus: []
  detailView:
    - component: main
      capability: presenceSensor
      version: 1
    - component: main
      capability: concertmirror08464.zf24PresenceSensitivity
      version: 1
    - component: main
      capability: concertmirror08464.zf24MoveSensitivity
      version: 1
    - component: main
      capability: concertmirror08464.zf24DetectionDistanceMax
      version: 1
    - component: main
      capability: concertmirror08464.zf24PresenceTimeout
      version: 1
    - component: main
      capability: concertmirror08464.zf24Distance
      version: 1
    - component: main
      capability: concertmirror08464.zf24RadarSwitch
      version: 1
    - component: main
      capability: concertmirror08464.zf24Function
      version: 1
    - component: main
      capability: concertmirror08464.zf24LivingRoom
      version: 1
    - component: main
      capability: concertmirror08464.zf24Bedroom
      version: 1
    - component: main
      capability: concertmirror08464.zf24Bathroom
      version: 1
    - component: main
      capability: concertmirror08464.zf24Sleep
      version: 1
    - component: main
      capability: concertmirror08464.driverMessage
      version: 1
    - component: main
      capability: illuminanceMeasurement
      version: 1
    - component: main
      capability: refresh
      version: 1
  automation:
    conditions:
      - component: main
        capability: presenceSensor
        version: 1
      - component: main
        capability: illuminanceMeasurement
        version: 1
      - component: main
        capability: concertmirror08464.zf24Function
        version: 1
      - component: main
        capability: concertmirror08464.zf24LivingRoom
        version: 1
      - component: main
        capability: concertmirror08464.zf24Bedroom
        version: 1
      - component: main
        capability: concertmirror08464.zf24Bathroom
        version: 1
      - component: main
        capability: concertmirror08464.zf24Sleep
        version: 1
    actions:
      - component: main
        capability: concertmirror08464.zf24Function
        version: 1
      - component: main
        capability: concertmirror08464.zf24LivingRoom
        version: 1
      - component: main
        capability: concertmirror08464.zf24Bedroom
        version: 1
      - component: main
        capability: concertmirror08464.zf24Bathroom
        version: 1
      - component: main
        capability: concertmirror08464.zf24Sleep
        version: 1
      - component: main
        capability: concertmirror08464.zf24PresenceSensitivity
        version: 1
      - component: main
        capability: concertmirror08464.zf24MoveSensitivity
        version: 1
      - component: main
        capability: concertmirror08464.zf24DetectionDistanceMax
        version: 1
      - component: main
        capability: concertmirror08464.zf24PresenceTimeout
        version: 1
      - component: main
        capability: concertmirror08464.zf24RadarSwitch
        version: 1
