zigbeeManufacturer:
  - id: "fp_46eba43912"
    manufacturer: "HOBEIAN"
    model: "ZG-302ZL"
    deviceProfileName: "switches-presence-switch-3"
  - id: "fp_fb2f2bc3a8"
    manufacturer: "HOBEIAN"
    model: "ZG-302ZM"
    deviceProfileName: "switches-presence-switch-3"
  - id: "fp_ad59d9261c"
    manufacturer: "Novato"
    model: "ZIS-04"
    deviceProfileName: "safety-presence-switch-illuminance"
  - id: "fp_98a3522d5b"
    manufacturer: "_TZE200_ahpcyzth"
    model: "TS0601"
    deviceProfileName: "switches-presence-switch-3"
  - id: "fp_33a9f7dd4a"
    manufacturer: "_TZE200_bfmfhxra"
    model: "TS0601"
    deviceProfileName: "switches-presence-switch-3"
  - id: "fp_5ba650b33a"
    manufacturer: "_TZE200_cqtamhh5"
    model: "TS0601"
    deviceProfileName: "switches-presence-switch-3"
  - id: "fp_b288c5001f"
    manufacturer: "_TZE200_df04ghrb"
    model: "TS0601"
    deviceProfileName: "switches-presence-switch-3"
  - id: "fp_a0dbc64b35"
    manufacturer: "_TZE200_kccdzaeo"
    model: "TS0601"
    deviceProfileName: "switches-presence-switch-3"
  - id: "fp_26f2d43d38"
    manufacturer: "_TZE200_khzbklyh"
    model: "TS0601"
    deviceProfileName: "switches-presence-switch-3"
  - id: "fp_7454ceed82"
    manufacturer: "_TZE200_kijxnb8q"
    model: "TS0601"
    deviceProfileName: "switches-presence-switch-3"
  - id: "fp_9c1fce39a6"
    manufacturer: "_TZE200_llvwkkde"
    model: "TS0601"
    deviceProfileName: "switches-presence-switch-3"
  - id: "fp_a8f6da67ae"
    manufacturer: "_TZE200_s7rsrtbg"
    model: "TS0601"
    deviceProfileName: "switches-presence-switch-3"
  - id: "fp_a9a62eba18"
    manufacturer: "_TZE200_tmszbtzq"
    model: "TS0601"
    deviceProfileName: "switches-presence-switch-3"
  - id: "fp_e498f4cd3e"
    manufacturer: "_TZE200_toeldckg"
    model: "TS0601"
    deviceProfileName: "switches-presence-switch-3"
  - id: "fp_18a2a6fb72"
    manufacturer: "_TZE200_xlnzk169"
    model: "TS0601"
    deviceProfileName: "switches-presence-switch-3"
  - id: "fp_17ae904284"
    manufacturer: "_TZE204_f2rflfa6"
    model: "TS0601"
    deviceProfileName: "safety-presence-switch-illuminance"
  - id: "fp_0c02abffe3"
    manufacturer: "_TZE204_izy1g1mb"
    model: "TS0601"
    deviceProfileName: "safety-presence-switch-illuminance"
