zigbeeManufacturer:
  - id: fp_ff9241b782
    manufacturer: "_TZE200_2gtsuokt"
    model: "TS0601"
    deviceProfileName: "lights-color-temperature-skydance-wz5-cct"
  - id: fp_36ec0400a4
    manufacturer: "_TZE200_3thxjahu"
    model: "TS0601"
    deviceProfileName: "lights-color-skydance-wz5-rgbw"
  - id: fp_45487acc8c
    manufacturer: "_TZE200_6qoazbre"
    model: "TS0601"
    deviceProfileName: "lights-dimmer-skydance-wz5-dim"
  - id: fp_e75ed1ae0d
    manufacturer: "_TZE200_9hghastn"
    model: "TS0601"
    deviceProfileName: "lights-color-skydance-wz5-rgb"
  - id: fp_b5a42b5f21
    manufacturer: "_TZE200_9mt3kgn0"
    model: "TS0601"
    deviceProfileName: "lights-color-skydance-wz5-rgb"
  - id: fp_dc606d46c9
    manufacturer: "_TZE200_a1ovdobn"
    model: "TS0601"
    deviceProfileName: "lights-moes-zs-d1"
  - id: fp_e99d32fc65
    manufacturer: "_TZE200_aa9awrng"
    model: "TS0601"
    deviceProfileName: "lights-color-temperature-color-skydance-wz5-rgbcct"
  - id: fp_d61be06aad
    manufacturer: "_TZE200_fcooykb4"
    model: "TS0601"
    deviceProfileName: "lights-dimmer-skydance-wz5-dim"
  - id: fp_3d7f713d5d
    manufacturer: "_TZE200_g9jdneiu"
    model: "TS0601"
    deviceProfileName: "lights-color-skydance-wz5-rgbw"
  - id: fp_db357b3920
    manufacturer: "_TZE200_gz3n0tzf"
    model: "TS0601"
    deviceProfileName: "lights-color-temperature-skydance-wz5-cct"
  - id: fp_1ec4748141
    manufacturer: "_TZE200_jowqowye"
    model: "TS0601"
    deviceProfileName: "lights-dimmer-mercator-siswd11-zb"
  - id: fp_9ed109c0e1
    manufacturer: "_TZE200_mde0utnv"
    model: "TS0601"
    deviceProfileName: "lights-color-temperature-color-skydance-wz5-rgbcct"
  - id: fp_3f37d98b2d
    manufacturer: "_TZE200_na98lvjp"
    model: "TS0601"
    deviceProfileName: "lights-color-temperature-skydance-wz5-cct"
  - id: fp_3df1bfd5c3
    manufacturer: "_TZE200_nthosjmx"
    model: "TS0601"
    deviceProfileName: "lights-color-temperature-skydance-wz5-cct"
  - id: fp_78790f1984
    manufacturer: "_TZE200_rlqamjhp"
    model: "TS0601"
    deviceProfileName: "lights-moes-zs-d2"
  - id: fp_326053404e
    manufacturer: "_TZE200_s8gkrkxk"
    model: "TS0601"
    deviceProfileName: "lights-wave19-lidl-hg06467"
  - id: fp_83496df8e8
    manufacturer: "_TZE204_8fffc3kb"
    model: "TS0601"
    deviceProfileName: "lights-wave15-gledopto-gl-spi-206p"
  - id: fp_a66e35a752
    manufacturer: "_TZE204_sdykkwsu"
    model: "TS0601"
    deviceProfileName: "lights-wave19-avatto-zdms16-us-w2"
  - id: fp_441deaf8b9
    manufacturer: "_TZE204_zhiqbr7l"
    model: "TS0601"
    deviceProfileName: "lights-color-temperature-color-skydance-wz5-rgbcct"
  - id: fp_2c22f0a8db
    manufacturer: "_TZE284_5yah8qx4"
    model: "TS0601"
    deviceProfileName: "lights-wave19-nova-topazio"
  - id: fp_a0df290169
    manufacturer: "_TZE284_a1ovdobn"
    model: "TS0601"
    deviceProfileName: "lights-moes-zs-d1"
  - id: fp_8377dd02cb
    manufacturer: "_TZE284_gt5al3bl"
    model: "TS0601"
    deviceProfileName: "lights-wave15-gledopto-gl-spi-206p"
  - id: fp_abae2f820c
    manufacturer: "_TZE284_nthhgkd6"
    model: "TS0601"
    deviceProfileName: "lights-wave19-qa-qadz4din"
  - id: fp_7f52ae1b7e
    manufacturer: "_TZE284_vizxbhco"
    model: "TS0601"
    deviceProfileName: "lights-moes-zs-d3"
  - id: fp_3972d35101
    manufacturer: "_TZE28C1000000_nqqylykc"
    model: "TS0601"
    deviceProfileName: "lights-dimmer-zdms16-1"
  - id: fp_05bf1d72f1
    manufacturer: "_TZE600_wxq8dpha\x00"
    model: "TS0603"
    deviceProfileName: "lights-wave19-lonsonho-vm-s02-010v"
