zigbeeManufacturer:
  - id: fp_040605dfcb
    manufacturer: "_TZE200_0hg58wyk"
    model: "TS0601"
    deviceProfileName: "thermostats-thermostat-s366"
  - id: fp_a4de4a74d9
    manufacturer: "_TZE200_7yoranx2"
    model: "TS0601"
    deviceProfileName: "thermostats-thermostat-tv02"
  - id: fp_6ad2c6e80e
    manufacturer: "_TZE200_9mjy74mp"
    model: "TS0601"
    deviceProfileName: "thermostats-thermostat-trv602"
  - id: fp_0e64bf3f28
    manufacturer: "_TZE200_e9ba97vf"
    model: "TS0601"
    deviceProfileName: "thermostats-thermostat-tv02"
  - id: fp_abbde13868
    manufacturer: "_TZE200_eo6xhfbo"
    model: "TS0601"
    deviceProfileName: "thermostats-thermostat-gtz10"
  - id: fp_1e8407ab6d
    manufacturer: "_TZE200_fsow0qsk"
    model: "TS0601"
    deviceProfileName: "thermostats-thermostat-tv02"
  - id: fp_e22bb09e0f
    manufacturer: "_TZE200_hue3yfsn"
    model: "TS0601"
    deviceProfileName: "thermostats-thermostat-tv02"
  - id: fp_db0aecdbf6
    manufacturer: "_TZE200_husqqvux"
    model: "TS0601"
    deviceProfileName: "thermostats-thermostat-tv02"
  - id: fp_f76b5ab365
    manufacturer: "_TZE200_k1tumq4t"
    model: "TS0601"
    deviceProfileName: "thermostats-thermostat-tv02"
  - id: fp_fc685a609a
    manufacturer: "_TZE200_kds0pmmv"
    model: "TS0601"
    deviceProfileName: "thermostats-thermostat-tv02"
  - id: fp_f533ae5028
    manufacturer: "_TZE200_lhzapfg9"
    model: "TS0601"
    deviceProfileName: "thermostats-thermostat-tv02"
  - id: fp_02c29919b0
    manufacturer: "_TZE200_lllliz3p"
    model: "TS0601"
    deviceProfileName: "thermostats-thermostat-tv02"
  - id: fp_da2aa1eb46
    manufacturer: "_TZE200_lnbfnyxd"
    model: "TS0601"
    deviceProfileName: "thermostats-thermostat-tv02"
  - id: fp_51a6e6a6dc
    manufacturer: "_TZE200_mudxchsu"
    model: "TS0601"
    deviceProfileName: "thermostats-thermostat-tv02"
  - id: fp_62a3825234
    manufacturer: "_TZE200_pbo8cj0z"
    model: "TS0601"
    deviceProfileName: "thermostats-thermostat-gtz10"
  - id: fp_cabc98ff9d
    manufacturer: "_TZE200_py4cm3he"
    model: "TS0601"
    deviceProfileName: "thermostats-thermostat-tv02"
  - id: fp_3839e46803
    manufacturer: "_TZE200_rtrmfadk"
    model: "TS0601"
    deviceProfileName: "thermostats-thermostat-trv602"
  - id: fp_1c59a1650b
    manufacturer: "_TZE200_sur6q7ko"
    model: "TS0601"
    deviceProfileName: "thermostats-thermostat-tv02"
  - id: fp_9a111f61b5
    manufacturer: "_TZE200_wsbfwodu"
    model: "TS0601"
    deviceProfileName: "thermostats-thermostat-tv02"
  - id: fp_fe5bc16350
    manufacturer: "_TZE200_x9axofse"
    model: "TS0601"
    deviceProfileName: "thermostats-thermostat-tv02"
  - id: fp_6c0f7b5996
    manufacturer: "_TZE204_9mjy74mp"
    model: "TS0601"
    deviceProfileName: "thermostats-thermostat-trv602"
  - id: fp_ec227fe6e6
    manufacturer: "_TZE204_cvcu2p6e"
    model: "TS0601"
    deviceProfileName: "thermostats-thermostat-trv601"
  - id: fp_200db13953
    manufacturer: "_TZE204_eekpf0ft"
    model: "TS0601"
    deviceProfileName: "thermostats-thermostat-tr-m3z"
  - id: fp_cbeaaf38f0
    manufacturer: "_TZE204_ltwbm23f"
    model: "TS0601"
    deviceProfileName: "thermostats-thermostat-trv602z"
  - id: fp_34bb25fba0
    manufacturer: "_TZE204_pcdmj88b"
    model: "TS0601"
    deviceProfileName: "thermostats-thermostat-trv4"
  - id: fp_e2ac5dc0d4
    manufacturer: "_TZE204_qyr2m29i"
    model: "TS0601"
    deviceProfileName: "thermostats-thermostat-trv602z"
  - id: fp_f3b1a97139
    manufacturer: "_TZE204_rtrmfadk"
    model: "TS0601"
    deviceProfileName: "thermostats-thermostat-trv601"
  - id: fp_d9a49641e2
    manufacturer: "_TZE204_vjpaih9f"
    model: "TS0601"
    deviceProfileName: "thermostats-thermostat-trv14"
  - id: fp_7cba1cab0a
    manufacturer: "_TZE284_eekpf0ft"
    model: "TS0601"
    deviceProfileName: "thermostats-thermostat-tr-m3z"
  - id: fp_ffc8ead9c8
    manufacturer: "_TZE284_ltwbm23f"
    model: "TS0601"
    deviceProfileName: "thermostats-thermostat-trv602z"
  - id: fp_cb668f2e3b
    manufacturer: "_TZE284_nbv4tdaz"
    model: "TS0601"
    deviceProfileName: "thermostats-thermostat-battery-ar331pro"
  - id: fp_1c8aafd856
    manufacturer: "_TZE284_noixx2uz"
    model: "TS0601"
    deviceProfileName: "thermostats-thermostat-battery-ar331"
  - id: fp_d549dd5c8b
    manufacturer: "_TZE284_pcdmj88b"
    model: "TS0601"
    deviceProfileName: "thermostats-thermostat-trv4"
  - id: fp_ecce990aa1
    manufacturer: "_TZE284_vjpaih9f"
    model: "TS0601"
    deviceProfileName: "thermostats-thermostat-trv14"
