name: meters-wave19-qa-qaszp
components:
  - id: main
    capabilities:
      - {id: powerMeter, version: 1}
      - {id: currentMeasurement, version: 1}
      - {id: voltageMeasurement, version: 1}
      - {id: energyMeter, version: 1}
      - {id: concertmirror08464.qaQaszpReactivePowerThreshold, version: 1}
      - {id: concertmirror08464.qaQaszpMaxEffectivePower, version: 1}
      - {id: concertmirror08464.qaQaszpStatusReport, version: 1}
      - {id: concertmirror08464.qaQaszpSwitchStatus, version: 1}
      - {id: refresh, version: 1}
    categories:
      - name: CurbPowerMeter
