zigbeeManufacturer:
  - id: "fp_3119705992"
    manufacturer: "_TZE200_7ytb3h8u"
    model: "TS0601"
    deviceProfileName: "valves-giex-qt06-two"
  - id: "fp_0df073264b"
    manufacturer: "_TZE200_a7sghmms"
    model: "TS0601"
    deviceProfileName: "valves-giex-qt06-two"
  - id: "fp_980271d175"
    manufacturer: "_TZE200_anv5ujhv"
    model: "TS0601"
    deviceProfileName: "valves-qoto-qt05m"
  - id: "fp_b84f1c5570"
    manufacturer: "_TZE200_arge1ptm"
    model: "TS0601"
    deviceProfileName: "valves-qoto-qt05m"
  - id: "fp_2388ba6101"
    manufacturer: "_TZE200_d0ypnbvn"
    model: "TS0601"
    deviceProfileName: "valves-iotperfect-pf-pm02d"
  - id: "fp_3d2ea6a87a"
    manufacturer: "_TZE200_htnnfasr"
    model: "TS0601"
    deviceProfileName: "valves-wave19-lidl-psbzs-a-one"
  - id: "fp_0678f25625"
    manufacturer: "_TZE200_nbqnmkee"
    model: "TS0601"
    deviceProfileName: "valves-wave19-frankever-fk-bv05"
  - id: "fp_b3b5d8cd81"
    manufacturer: "_TZE200_sh1btabb"
    model: "TS0601"
    deviceProfileName: "valves-giex-qt06-one"
  - id: "fp_32ba525b06"
    manufacturer: "_TZE200_vrjkcam9"
    model: "TS0601"
    deviceProfileName: "valves-iotperfect-pf-pm02d"
  - id: "fp_bdc2d15517"
    manufacturer: "_TZE200_xlppj4f5"
    model: "TS0601"
    deviceProfileName: "valves-qoto-qt05m"
  - id: "fp_b99671afef"
    manufacturer: "_TZE204_7ytb3h8u"
    model: "TS0601"
    deviceProfileName: "valves-giex-qt06-two"
  - id: "fp_12bf659d0f"
    manufacturer: "_TZE204_a7sghmms"
    model: "TS0601"
    deviceProfileName: "valves-giex-qt06-two"
  - id: "fp_ab12d4fc4e"
    manufacturer: "_TZE204_a9ojznj8"
    model: "TS0601"
    deviceProfileName: "valves-neo-nas-wv03b2"
  - id: "fp_edd144e810"
    manufacturer: "_TZE204_d0ypnbvn"
    model: "TS0601"
    deviceProfileName: "valves-iotperfect-pf-pm02d"
  - id: "fp_f988d2690e"
    manufacturer: "_TZE204_v5xjyphj"
    model: "TS0601"
    deviceProfileName: "valves-iotperfect-pf-pm02d"
  - id: "fp_4581a42022"
    manufacturer: "_TZE284_7ytb3h8u"
    model: "TS0601"
    deviceProfileName: "valves-giex-qt06-two"
  - id: "fp_90e4b84312"
    manufacturer: "_TZE284_a9ojznj8"
    model: "TS0601"
    deviceProfileName: "valves-neo-nas-wv03b2"
  - id: "fp_a06b8e0d76"
    manufacturer: "_TZE284_d0ypnbvn"
    model: "TS0601"
    deviceProfileName: "valves-iotperfect-pf-pm02d"
  - id: "fp_5a8eff8f13"
    manufacturer: "_TZE284_v5xjyphj"
    model: "TS0601"
    deviceProfileName: "valves-iotperfect-pf-pm02d"
