zigbeeManufacturer:
  - id: "fp_6d173e7b49"
    manufacturer: "LoraTap"
    model: "SS9600ZB"
    deviceProfileName: "buttons-button-6-battery"
  - id: "fp_a164b6d583"
    manufacturer: "_TZ3210_3ulg9kpo"
    model: "TS0021"
    deviceProfileName: "buttons-button-2-battery"
  - id: "fp_9615a99ece"
    manufacturer: "_TZE200_2m38mh6k"
    model: "TS0601"
    deviceProfileName: "buttons-button-6-battery"
  - id: "fp_374f5621c0"
    manufacturer: "_TZE200_dhke3p9w"
    model: "TS0601"
    deviceProfileName: "buttons-button-18"
  - id: "fp_5663d74c80"
    manufacturer: "_TZE200_mfamvsdb"
    model: "TS0601"
    deviceProfileName: "buttons-button-4"
  - id: "fp_a504f45599"
    manufacturer: "_TZE200_nojsjtj2"
    model: "TS0601"
    deviceProfileName: "security-remotes-sos-battery"
  - id: "fp_c44feac531"
    manufacturer: "_TZE200_vrcfo4i0"
    model: "TS0601"
    deviceProfileName: "security-remotes-sos-battery"
  - id: "fp_6dd4124e09"
    manufacturer: "_TZE284_2baujqot"
    model: "TS0601"
    deviceProfileName: "security-remotes-sos-battery"
  - id: "fp_e5472c0967"
    manufacturer: "_TZE284_5ys44kzo"
    model: "TS0601"
    deviceProfileName: "buttons-button-6-battery"
  - id: "fp_7a1a543fef"
    manufacturer: "_TZE284_dhke3p9w"
    model: "TS0601"
    deviceProfileName: "buttons-button-18"
  - id: "fp_29d167e555"
    manufacturer: "_TZE284_nj7sfid2"
    model: "TS0601"
    deviceProfileName: "buttons-button-4"
