name: safety-contact-temp-humidity-battery-s8
components:
  - id: main
    capabilities:
      - id: concertmirror08464.s8OpeningMode
        version: 1
      - id: temperatureMeasurement
        version: 1
      - id: relativeHumidityMeasurement
        version: 1
      - id: battery
        version: 1
      - id: concertmirror08464.sensitivityContactS8Enum
        version: 1
      - id: concertmirror08464.updateFrequencyContactS8Minutes
        version: 1
      - id: concertmirror08464.alarmDurationContactS8Sec300
        version: 1
      - id: concertmirror08464.s8AlarmState
        version: 1
      - id: concertmirror08464.s8HandlePosition
        version: 1
      - id: concertmirror08464.s8LeftButton
        version: 1
      - id: concertmirror08464.s8RightButton
        version: 1
      - id: concertmirror08464.s8VacationMode
        version: 1
      - id: concertmirror08464.s8AlarmSwitch
        version: 1
      - id: concertmirror08464.s8KeySound
        version: 1
      - id: concertmirror08464.batteryLow
        version: 1
      - id: concertmirror08464.s8HandleSound
        version: 1
      - id: concertmirror08464.s8Calibrate
        version: 1
      - id: firmwareUpdate
        version: 1
      - id: refresh
        version: 1
    categories:
      - name: ContactSensor
preferences:
  - preferenceId: tempOffset
    explicit: true
  - preferenceId: humidityOffset
    explicit: true
