name: safety-contact-vibration-battery-excellux
components:
  - id: main
    capabilities:
      - id: contactSensor
        version: 1
      - id: accelerationSensor
        version: 1
      - id: battery
        version: 1
      - id: concertmirror08464.excelluxCatVibrationSensitivity
        version: 1
      - id: firmwareUpdate
        version: 1
      - id: refresh
        version: 1
    categories:
      - name: MultiFunctionalSensor
