name: thermostats-thermostat-tv02
components:
  - id: main
    capabilities:
      - id: thermostatMode
        version: 1
      - id: thermostatHeatingSetpoint
        version: 1
      - id: temperatureMeasurement
        version: 1
      - id: concertmirror08464.workingDayTv02ScheduleMode
        version: 1
      - id: concertmirror08464.tv02OpenWindow
        version: 1
      - id: concertmirror08464.tv02FrostProtection
        version: 1
      - id: concertmirror08464.tv02ChildLock
        version: 1
      - id: concertmirror08464.tv02BatteryLow
        version: 1
      - id: concertmirror08464.tv02Online
        version: 1
      - id: concertmirror08464.tv02TempCalibration
        version: 1
      - id: concertmirror08464.tv02HolidayTemperature
        version: 1
      - id: concertmirror08464.tv02OpenWindowTemperature
        version: 1
      - id: concertmirror08464.tv02ComfortTemperature
        version: 1
      - id: concertmirror08464.tv02EcoTemperature
        version: 1
      - id: concertmirror08464.tv02BoostCountdown
        version: 1
      - id: concertmirror08464.tv02ErrorStatus
        version: 1
      - id: refresh
        version: 1
    categories:
      - name: Thermostat
deviceConfig:
  dashboard:
    states:
      - component: main
        capability: thermostatHeatingSetpoint
        version: 1
        group: main
    actions: []
    basicPlus: []
  detailView:
    - component: main
      capability: thermostatMode
      version: 1
    - component: main
      capability: thermostatHeatingSetpoint
      version: 1
    - component: main
      capability: temperatureMeasurement
      version: 1
    - component: main
      capability: concertmirror08464.workingDayTv02ScheduleMode
      version: 1
    - component: main
      capability: concertmirror08464.tv02OpenWindow
      version: 1
    - component: main
      capability: concertmirror08464.tv02FrostProtection
      version: 1
    - component: main
      capability: concertmirror08464.tv02ChildLock
      version: 1
    - component: main
      capability: concertmirror08464.tv02BatteryLow
      version: 1
    - component: main
      capability: concertmirror08464.tv02Online
      version: 1
    - component: main
      capability: concertmirror08464.tv02TempCalibration
      version: 1
    - component: main
      capability: concertmirror08464.tv02HolidayTemperature
      version: 1
    - component: main
      capability: concertmirror08464.tv02OpenWindowTemperature
      version: 1
    - component: main
      capability: concertmirror08464.tv02ComfortTemperature
      version: 1
    - component: main
      capability: concertmirror08464.tv02EcoTemperature
      version: 1
    - component: main
      capability: concertmirror08464.tv02BoostCountdown
      version: 1
    - component: main
      capability: concertmirror08464.tv02ErrorStatus
      version: 1
    - component: main
      capability: refresh
      version: 1
  automation:
    conditions:
      - component: main
        capability: thermostatMode
        version: 1
      - component: main
        capability: thermostatHeatingSetpoint
        version: 1
      - component: main
        capability: temperatureMeasurement
        version: 1
      - component: main
        capability: concertmirror08464.workingDayTv02ScheduleMode
        version: 1
      - component: main
        capability: concertmirror08464.tv02OpenWindow
        version: 1
      - component: main
        capability: concertmirror08464.tv02FrostProtection
        version: 1
      - component: main
        capability: concertmirror08464.tv02ChildLock
        version: 1
      - component: main
        capability: concertmirror08464.tv02BatteryLow
        version: 1
      - component: main
        capability: concertmirror08464.tv02Online
        version: 1
      - component: main
        capability: concertmirror08464.tv02TempCalibration
        version: 1
      - component: main
        capability: concertmirror08464.tv02HolidayTemperature
        version: 1
      - component: main
        capability: concertmirror08464.tv02OpenWindowTemperature
        version: 1
      - component: main
        capability: concertmirror08464.tv02ComfortTemperature
        version: 1
      - component: main
        capability: concertmirror08464.tv02EcoTemperature
        version: 1
      - component: main
        capability: concertmirror08464.tv02BoostCountdown
        version: 1
      - component: main
        capability: concertmirror08464.tv02ErrorStatus
        version: 1
    actions:
      - component: main
        capability: thermostatMode
        version: 1
      - component: main
        capability: thermostatHeatingSetpoint
        version: 1
      - component: main
        capability: concertmirror08464.workingDayTv02ScheduleMode
        version: 1
      - component: main
        capability: concertmirror08464.tv02OpenWindow
        version: 1
      - component: main
        capability: concertmirror08464.tv02FrostProtection
        version: 1
      - component: main
        capability: concertmirror08464.tv02ChildLock
        version: 1
      - component: main
        capability: concertmirror08464.tv02TempCalibration
        version: 1
      - component: main
        capability: concertmirror08464.tv02HolidayTemperature
        version: 1
      - component: main
        capability: concertmirror08464.tv02OpenWindowTemperature
        version: 1
      - component: main
        capability: concertmirror08464.tv02ComfortTemperature
        version: 1
      - component: main
        capability: concertmirror08464.tv02EcoTemperature
        version: 1
      - component: main
        capability: concertmirror08464.tv02BoostCountdown
        version: 1
