name: thermostats-thermostat-battery-ar331pro
components:
  - id: main
    capabilities:
      - id: thermostatMode
        version: 1
      - id: thermostatHeatingSetpoint
        version: 1
      - id: thermostatOperatingState
        version: 1
      - id: temperatureMeasurement
        version: 1
      - id: battery
        version: 1
      - id: concertmirror08464.thermostatPresetAr331proSixMode
        version: 1
      - id: concertmirror08464.ar331proChildLock
        version: 1
      - id: concertmirror08464.ar331proPreheat
        version: 1
      - id: concertmirror08464.ar331proWindowDetection
        version: 1
      - id: concertmirror08464.ar331proWindowOpen
        version: 1
      - id: concertmirror08464.ar331proValveState
        version: 1
      - id: concertmirror08464.ar331proBoostHeating
        version: 1
      - id: concertmirror08464.ar331proBoostTime
        version: 1
      - id: concertmirror08464.ar331proSummerMode
        version: 1
      - id: concertmirror08464.ar331proHeatCoolMode
        version: 1
      - id: concertmirror08464.ar331proBatteryStatus
        version: 1
      - id: concertmirror08464.ar331proScreenOrientation
        version: 1
      - id: concertmirror08464.ar331proOverrideActive
        version: 1
      - id: concertmirror08464.ar331proTempCalibration
        version: 1
      - id: concertmirror08464.ar331proEcoTemperature
        version: 1
      - id: concertmirror08464.ar331proComfortTemperature
        version: 1
      - id: concertmirror08464.ar331proFrostTemperature
        version: 1
      - id: concertmirror08464.ar331proWindowTemp
        version: 1
      - id: concertmirror08464.ar331proWindowDelay
        version: 1
      - id: concertmirror08464.ar331proWindowCloseDelay
        version: 1
      - id: concertmirror08464.ar331proDisplayBrightness
        version: 1
      - id: concertmirror08464.ar331proOverrideTemperature
        version: 1
      - id: concertmirror08464.ar331proFaultCode
        version: 1
      - id: refresh
        version: 1
    categories:
      - name: Thermostat
deviceConfig:
  dashboard:
    states:
      - component: main
        capability: thermostatHeatingSetpoint
        version: 1
        group: main
    actions: []
    basicPlus: []
  detailView:
    - component: main
      capability: thermostatMode
      version: 1
    - component: main
      capability: thermostatHeatingSetpoint
      version: 1
    - component: main
      capability: thermostatOperatingState
      version: 1
    - component: main
      capability: temperatureMeasurement
      version: 1
    - component: main
      capability: battery
      version: 1
    - component: main
      capability: concertmirror08464.thermostatPresetAr331proSixMode
      version: 1
    - component: main
      capability: concertmirror08464.ar331proChildLock
      version: 1
    - component: main
      capability: concertmirror08464.ar331proPreheat
      version: 1
    - component: main
      capability: concertmirror08464.ar331proWindowDetection
      version: 1
    - component: main
      capability: concertmirror08464.ar331proWindowOpen
      version: 1
    - component: main
      capability: concertmirror08464.ar331proValveState
      version: 1
    - component: main
      capability: concertmirror08464.ar331proBoostHeating
      version: 1
    - component: main
      capability: concertmirror08464.ar331proBoostTime
      version: 1
    - component: main
      capability: concertmirror08464.ar331proSummerMode
      version: 1
    - component: main
      capability: concertmirror08464.ar331proHeatCoolMode
      version: 1
    - component: main
      capability: concertmirror08464.ar331proBatteryStatus
      version: 1
    - component: main
      capability: concertmirror08464.ar331proScreenOrientation
      version: 1
    - component: main
      capability: concertmirror08464.ar331proOverrideActive
      version: 1
    - component: main
      capability: concertmirror08464.ar331proTempCalibration
      version: 1
    - component: main
      capability: concertmirror08464.ar331proEcoTemperature
      version: 1
    - component: main
      capability: concertmirror08464.ar331proComfortTemperature
      version: 1
    - component: main
      capability: concertmirror08464.ar331proFrostTemperature
      version: 1
    - component: main
      capability: concertmirror08464.ar331proWindowTemp
      version: 1
    - component: main
      capability: concertmirror08464.ar331proWindowDelay
      version: 1
    - component: main
      capability: concertmirror08464.ar331proWindowCloseDelay
      version: 1
    - component: main
      capability: concertmirror08464.ar331proDisplayBrightness
      version: 1
    - component: main
      capability: concertmirror08464.ar331proOverrideTemperature
      version: 1
    - component: main
      capability: concertmirror08464.ar331proFaultCode
      version: 1
    - component: main
      capability: refresh
      version: 1
  automation:
    conditions:
      - component: main
        capability: thermostatMode
        version: 1
      - component: main
        capability: thermostatHeatingSetpoint
        version: 1
      - component: main
        capability: thermostatOperatingState
        version: 1
      - component: main
        capability: temperatureMeasurement
        version: 1
      - component: main
        capability: battery
        version: 1
      - component: main
        capability: concertmirror08464.thermostatPresetAr331proSixMode
        version: 1
      - component: main
        capability: concertmirror08464.ar331proChildLock
        version: 1
      - component: main
        capability: concertmirror08464.ar331proPreheat
        version: 1
      - component: main
        capability: concertmirror08464.ar331proWindowDetection
        version: 1
      - component: main
        capability: concertmirror08464.ar331proWindowOpen
        version: 1
      - component: main
        capability: concertmirror08464.ar331proValveState
        version: 1
      - component: main
        capability: concertmirror08464.ar331proBoostHeating
        version: 1
      - component: main
        capability: concertmirror08464.ar331proBoostTime
        version: 1
      - component: main
        capability: concertmirror08464.ar331proSummerMode
        version: 1
      - component: main
        capability: concertmirror08464.ar331proHeatCoolMode
        version: 1
      - component: main
        capability: concertmirror08464.ar331proBatteryStatus
        version: 1
      - component: main
        capability: concertmirror08464.ar331proScreenOrientation
        version: 1
      - component: main
        capability: concertmirror08464.ar331proOverrideActive
        version: 1
      - component: main
        capability: concertmirror08464.ar331proTempCalibration
        version: 1
      - component: main
        capability: concertmirror08464.ar331proEcoTemperature
        version: 1
      - component: main
        capability: concertmirror08464.ar331proComfortTemperature
        version: 1
      - component: main
        capability: concertmirror08464.ar331proFrostTemperature
        version: 1
      - component: main
        capability: concertmirror08464.ar331proWindowTemp
        version: 1
      - component: main
        capability: concertmirror08464.ar331proWindowDelay
        version: 1
      - component: main
        capability: concertmirror08464.ar331proWindowCloseDelay
        version: 1
      - component: main
        capability: concertmirror08464.ar331proDisplayBrightness
        version: 1
      - component: main
        capability: concertmirror08464.ar331proOverrideTemperature
        version: 1
      - component: main
        capability: concertmirror08464.ar331proFaultCode
        version: 1
    actions:
      - component: main
        capability: thermostatMode
        version: 1
      - component: main
        capability: thermostatHeatingSetpoint
        version: 1
      - component: main
        capability: concertmirror08464.thermostatPresetAr331proSixMode
        version: 1
      - component: main
        capability: concertmirror08464.ar331proChildLock
        version: 1
      - component: main
        capability: concertmirror08464.ar331proWindowDetection
        version: 1
      - component: main
        capability: concertmirror08464.ar331proBoostHeating
        version: 1
      - component: main
        capability: concertmirror08464.ar331proBoostTime
        version: 1
      - component: main
        capability: concertmirror08464.ar331proSummerMode
        version: 1
      - component: main
        capability: concertmirror08464.ar331proHeatCoolMode
        version: 1
      - component: main
        capability: concertmirror08464.ar331proScreenOrientation
        version: 1
      - component: main
        capability: concertmirror08464.ar331proOverrideActive
        version: 1
      - component: main
        capability: concertmirror08464.ar331proTempCalibration
        version: 1
      - component: main
        capability: concertmirror08464.ar331proEcoTemperature
        version: 1
      - component: main
        capability: concertmirror08464.ar331proComfortTemperature
        version: 1
      - component: main
        capability: concertmirror08464.ar331proFrostTemperature
        version: 1
      - component: main
        capability: concertmirror08464.ar331proWindowTemp
        version: 1
      - component: main
        capability: concertmirror08464.ar331proWindowDelay
        version: 1
      - component: main
        capability: concertmirror08464.ar331proWindowCloseDelay
        version: 1
      - component: main
        capability: concertmirror08464.ar331proDisplayBrightness
        version: 1
      - component: main
        capability: concertmirror08464.ar331proOverrideTemperature
        version: 1
