name: sensors-soil-temp-humidity-moisture-battery-air-illum
components:
  - id: main
    capabilities:
      - id: temperatureMeasurement
        version: 1
      - id: relativeHumidityMeasurement
        version: 1
      - id: concertmirror08464.soilMoisture
        version: 1
      - id: battery
        version: 1
      - id: concertmirror08464.humidityCalibrationZs301z
        version: 1
      - id: refresh
        version: 1
    categories:
      - name: MoistureSensor
