name: sensors-temp-humidity-battery-sensitivity-nous-e6
components:
  - id: main
    capabilities:
      - id: temperatureMeasurement
        version: 1
      - id: relativeHumidityMeasurement
        version: 1
      - id: battery
        version: 1
      - id: concertmirror08464.nousE6TemperatureSensitivity
        version: 1
      - id: concertmirror08464.nousE6HumiditySensitivity
        version: 1
      - id: refresh
        version: 1
    categories:
      - name: TempHumiditySensor
