name: sensors-soil-temp-moisture-battery-unit-illuminance-sgs02z
components:
- id: main
  capabilities:
  - id: temperatureMeasurement
    version: 1
  - id: concertmirror08464.soilMoisture
    version: 1
  - id: battery
    version: 1
  - id: concertmirror08464.sgs02zIlluminanceLevel
    version: 1
  - id: concertmirror08464.sgs02zTemperatureUnit
    version: 1
  - id: firmwareUpdate
    version: 1
  - id: refresh
    version: 1
  categories:
  - name: TempHumiditySensor
