zigbeeManufacturer:
  - id: "fp_7c46d6b3f5"
    manufacturer: "Coswall"
    model: "X99-G-kbFan-1g-ZG-LN-11"
    deviceProfileName: "fans-fan-level-light-switch"
  - id: "fp_6acfefe5ac"
    manufacturer: "Earda"
    model: "EDM-1ZAA-EU"
    deviceProfileName: "lights-dimmer-options-ts0601"
  - id: "fp_7ef25eacd3"
    manufacturer: "Earda"
    model: "EDM-1ZAB-EU"
    deviceProfileName: "lights-dimmer-options-ts0601"
  - id: "fp_6d7b11d6ad"
    manufacturer: "Earda"
    model: "EDM-1ZBA-EU"
    deviceProfileName: "lights-dimmer-options-ts0601"
  - id: "fp_a810e6afdd"
    manufacturer: "ION Industries"
    model: "90.500.040"
    deviceProfileName: "lights-dimmer-options-ts0601"
  - id: "fp_da3e604dab"
    manufacturer: "ION Industries"
    model: "90.500.090"
    deviceProfileName: "lights-dimmer-options-ts0601"
  - id: "fp_b7ff335d8a"
    manufacturer: "ION Industries"
    model: "ID200W-ZIGB"
    deviceProfileName: "lights-dimmer-options-ts0601"
  - id: "fp_f6837f183a"
    manufacturer: "KnockautX"
    model: "FMD2C018"
    deviceProfileName: "lights-dimmer-2"
  - id: "fp_adcb9c8223"
    manufacturer: "Larkkey"
    model: "ZSTY-SM-1DMZG-EU"
    deviceProfileName: "lights-dimmer-options-ts0601"
  - id: "fp_40529b90a2"
    manufacturer: "Lerlink"
    model: "T2-Z67/T2-W67"
    deviceProfileName: "fans-fan-light-switch"
  - id: "fp_09a371c6d3"
    manufacturer: "Lerlink"
    model: "X706U"
    deviceProfileName: "lights-dimmer-options-ts0601"
  - id: "fp_a076299dce"
    manufacturer: "Liwokit"
    model: "Fan+Light-01"
    deviceProfileName: "fans-fan-light-switch"
  - id: "fp_600f9bad6d"
    manufacturer: "Lonsonho"
    model: "EDM-1ZBB-EU"
    deviceProfileName: "lights-dimmer-options-ts0601"
  - id: "fp_d8e7ca9fa8"
    manufacturer: "Mercator Ikuü"
    model: "SSWD01"
    deviceProfileName: "lights-dimmer-options-ts0601"
  - id: "fp_f9e5c823be"
    manufacturer: "Mercator Ikuü"
    model: "SSWM-DIMZ"
    deviceProfileName: "lights-dimmer-options-ts0601"
  - id: "fp_927c883056"
    manufacturer: "Mercator Ikuü"
    model: "SSWRM-ZB"
    deviceProfileName: "lights-dimmer-options-ts0601"
  - id: "fp_1b6c706f21"
    manufacturer: "Moes"
    model: "EDM-1ZBB-EU"
    deviceProfileName: "lights-dimmer-options-ts0601"
  - id: "fp_ef7f3d45f1"
    manufacturer: "Moes"
    model: "MS-105-M"
    deviceProfileName: "lights-dimmer"
  - id: "fp_998782acd2"
    manufacturer: "Moes"
    model: "MS-105B"
    deviceProfileName: "lights-dimmer-2"
  - id: "fp_b0869f9d05"
    manufacturer: "Moes"
    model: "MS-105Z"
    deviceProfileName: "lights-dimmer-options-ts0601"
  - id: "fp_412ba32efd"
    manufacturer: "Moes"
    model: "WS-SY-EURD"
    deviceProfileName: "lights-dimmer"
  - id: "fp_4050bdf1ed"
    manufacturer: "Moes"
    model: "WS-SY-EURD-WH-MS"
    deviceProfileName: "lights-dimmer"
  - id: "fp_f812ecabd1"
    manufacturer: "Moes"
    model: "ZM-105B-M"
    deviceProfileName: "lights-dimmer-2"
  - id: "fp_53b1f5f944"
    manufacturer: "Moes"
    model: "ZS-EUD_1gang"
    deviceProfileName: "lights-dimmer-options-ts0601"
  - id: "fp_bda7cb19f5"
    manufacturer: "Moes"
    model: "ZS-EUD_2gang"
    deviceProfileName: "lights-dimmer-2"
  - id: "fp_85053df392"
    manufacturer: "Moes"
    model: "ZS-EUD_3gang"
    deviceProfileName: "lights-dimmer-3"
  - id: "fp_2ff5a38572"
    manufacturer: "Moes"
    model: "ZS-SR-EUD-1"
    deviceProfileName: "lights-dimmer-options-ts0601"
  - id: "fp_c3df4c2d63"
    manufacturer: "Moes"
    model: "ZS-SR-EUD-2"
    deviceProfileName: "lights-dimmer-2"
  - id: "fp_e70bebd064"
    manufacturer: "Moes"
    model: "ZS-SR-EUD-3"
    deviceProfileName: "lights-dimmer-3"
  - id: "fp_8e511d2b1d"
    manufacturer: "Moes"
    model: "ZS-USD"
    deviceProfileName: "lights-dimmer-options-ts0601"
  - id: "fp_d3853bf78c"
    manufacturer: "Zemismart"
    model: "ZN2S-RS1E-FL / ZN2S-US1U-FL"
    deviceProfileName: "fans-fan-level-light-switch"
  - id: "fp_4f6bfa2d79"
    manufacturer: "Zemismart"
    model: "ZN2S-RS3E-DH"
    deviceProfileName: "lights-dimmer-3"
  - id: "fp_96a64532a7"
    manufacturer: "Zemismart"
    model: "ZN2S-US1-SD"
    deviceProfileName: "lights-dimmer-options-ts0601"
  - id: "fp_8724a29613"
    manufacturer: "_TZE200_0hb4rdnp"
    model: "TS0601"
    deviceProfileName: "lights-dimmer-options-ts0601"
  - id: "fp_21bd8751e2"
    manufacturer: "_TZE200_0nauxa0p"
    model: "TS0601"
    deviceProfileName: "lights-dimmer-options-ts0601"
  - id: "fp_a3f9494d2a"
    manufacturer: "_TZE200_1agwnems"
    model: "TS0601"
    deviceProfileName: "lights-dimmer-options-ts0601"
  - id: "fp_1cf9988a10"
    manufacturer: "_TZE200_3p5ydos3"
    model: "TS0601"
    deviceProfileName: "lights-dimmer-options-ts0601"
  - id: "fp_eee68445bc"
    manufacturer: "_TZE200_4mh6tyyo"
    model: "TS0601"
    deviceProfileName: "lights-dimmer-options-ts0601"
  - id: "fp_2324cb6523"
    manufacturer: "_TZE200_579lguh2"
    model: "TS0601"
    deviceProfileName: "lights-dimmer-options-ts0601"
  - id: "fp_416507a43c"
    manufacturer: "_TZE200_86nbew0j"
    model: "TS0601"
    deviceProfileName: "lights-dimmer"
  - id: "fp_ae999a3cef"
    manufacturer: "_TZE200_9cxuhakf"
    model: "TS0601"
    deviceProfileName: "lights-dimmer-options-ts0601"
  - id: "fp_82459c4d71"
    manufacturer: "_TZE200_9i9dt8is"
    model: "TS0601"
    deviceProfileName: "lights-dimmer-options-ts0601"
  - id: "fp_7199b695bf"
    manufacturer: "_TZE200_a0syesf5"
    model: "TS0601"
    deviceProfileName: "lights-dimmer-options-ts0601"
  - id: "fp_6b1c858b09"
    manufacturer: "_TZE200_bxoo2swd"
    model: "TS0601"
    deviceProfileName: "lights-dimmer-2"
  - id: "fp_3b3f3f0e26"
    manufacturer: "_TZE200_ctq0k47x"
    model: "TS0601"
    deviceProfileName: "lights-dimmer-options-ts0601"
  - id: "fp_d36f575fd0"
    manufacturer: "_TZE200_dcnsggv"
    model: "TS0601"
    deviceProfileName: "lights-dimmer"
  - id: "fp_6180067718"
    manufacturer: "_TZE200_dcnsggvz"
    model: "TS0601"
    deviceProfileName: "lights-dimmer"
  - id: "fp_75d723bab6"
    manufacturer: "_TZE200_dfxkcots"
    model: "TS0601"
    deviceProfileName: "lights-dimmer-options-ts0601"
  - id: "fp_48a0f06454"
    manufacturer: "_TZE200_drs6j6m5"
    model: "TS0601"
    deviceProfileName: "lights-dimmer"
  - id: "fp_07b7ea8cff"
    manufacturer: "_TZE200_e3oitdyu"
    model: "TS0601"
    deviceProfileName: "lights-dimmer-2"
  - id: "fp_089036b79b"
    manufacturer: "_TZE200_ebwgzdqq"
    model: "TS0601"
    deviceProfileName: "lights-dimmer-options-ts0601"
  - id: "fp_7b6ea8076d"
    manufacturer: "_TZE200_fjjbhx9d"
    model: "TS0601"
    deviceProfileName: "lights-dimmer-2"
  - id: "fp_95a32035f1"
    manufacturer: "_TZE200_gne0e6mk"
    model: "TS0601"
    deviceProfileName: "lights-dimmer-options-ts0601"
  - id: "fp_bb11078e81"
    manufacturer: "_TZE200_gwkapsoq"
    model: "TS0601"
    deviceProfileName: "lights-dimmer-2"
  - id: "fp_a5e456401f"
    manufacturer: "_TZE200_hmqzfqml"
    model: "TS0601"
    deviceProfileName: "fans-fan-light-switch"
  - id: "fp_d6b4988db3"
    manufacturer: "_TZE200_io0zdqh1"
    model: "TS0601"
    deviceProfileName: "lights-dimmer"
  - id: "fp_134970e61d"
    manufacturer: "_TZE200_ip2akl4w"
    model: "TS0601"
    deviceProfileName: "lights-dimmer-options-ts0601"
  - id: "fp_335a3c9099"
    manufacturer: "_TZE200_itp8dt7f"
    model: "TS0601"
    deviceProfileName: "lights-dimmer-options-ts0601"
  - id: "fp_137adebf90"
    manufacturer: "_TZE200_la2c2uo9"
    model: "TS0601"
    deviceProfileName: "lights-dimmer-options-ts0601"
  - id: "fp_d2b5a6e145"
    manufacturer: "_TZE200_lawxy9e2"
    model: "TS0601"
    deviceProfileName: "fans-fan-light-switch"
  - id: "fp_2a2b1ac9bd"
    manufacturer: "_TZE200_ojzhk75b"
    model: "TS0601"
    deviceProfileName: "lights-dimmer-options-ts0601"
  - id: "fp_4cf8f26699"
    manufacturer: "_TZE200_p0gzbqct"
    model: "TS0601"
    deviceProfileName: "lights-dimmer"
  - id: "fp_ca2d7c1d9f"
    manufacturer: "_TZE200_qanl25yu"
    model: "TS0601"
    deviceProfileName: "fans-fan-light-switch"
  - id: "fp_952471ecc6"
    manufacturer: "_TZE200_qyss8gjy"
    model: "TS0601"
    deviceProfileName: "lights-dimmer"
  - id: "fp_b9c0d5e5fe"
    manufacturer: "_TZE200_qzaing2g"
    model: "TS0601"
    deviceProfileName: "lights-dimmer-power-voltage-current"
  - id: "fp_df2aa60a8b"
    manufacturer: "_TZE200_r32ctezx"
    model: "TS0601"
    deviceProfileName: "fans-switch-fan-mode-ef00"
  - id: "fp_c5268ffe9b"
    manufacturer: "_TZE200_swaamsoy"
    model: "TS0601"
    deviceProfileName: "lights-dimmer-options-ts0601"
  - id: "fp_2461429f96"
    manufacturer: "_TZE200_tgeqdjgk"
    model: "TS0601"
    deviceProfileName: "lights-color-temperature"
  - id: "fp_d17b06b9d4"
    manufacturer: "_TZE200_tsxpl0d0"
    model: "TS0601"
    deviceProfileName: "lights-dimmer-2"
  - id: "fp_e4a0cb20dc"
    manufacturer: "_TZE200_vizxbhco"
    model: "TS0601"
    deviceProfileName: "lights-dimmer-3"
  - id: "fp_7b4189e1d4"
    manufacturer: "_TZE200_vm1gyrso"
    model: "TS0601"
    deviceProfileName: "lights-dimmer-3"
  - id: "fp_684f87ed69"
    manufacturer: "_TZE200_vucankjx"
    model: "TS0601"
    deviceProfileName: "lights-dimmer-options-ts0601"
  - id: "fp_9a0c03b0e3"
    manufacturer: "_TZE200_w4cryh2i"
    model: "TS0601"
    deviceProfileName: "lights-dimmer-options-ts0601"
  - id: "fp_3b5b261040"
    manufacturer: "_TZE200_whpb9yts"
    model: "TS0601"
    deviceProfileName: "lights-dimmer"
  - id: "fp_d7763b90ea"
    manufacturer: "_TZE200_ykgar0ow"
    model: "TS0601"
    deviceProfileName: "lights-dimmer-options-ts0601"
  - id: "fp_d67eb3b25a"
    manufacturer: "_TZE200_ywe90lt0"
    model: "TS0601"
    deviceProfileName: "lights-dimmer"
  - id: "fp_db3921d721"
    manufacturer: "_TZE204_1v1dxkck"
    model: "TS0601"
    deviceProfileName: "lights-dimmer-3"
  - id: "fp_3718fe32ed"
    manufacturer: "_TZE204_2jnoy8dj"
    model: "TS0601"
    deviceProfileName: "fans-fan-level-light-switch"
  - id: "fp_2a53644c9a"
    manufacturer: "_TZE204_68utemio"
    model: "TS0601"
    deviceProfileName: "lights-dimmer-options-ts0601"
  - id: "fp_b774467a94"
    manufacturer: "_TZE204_9qhuzgo0"
    model: "TS0601"
    deviceProfileName: "lights-dimmer-options-ts0601"
  - id: "fp_634812be41"
    manufacturer: "_TZE204_bql5khqx"
    model: "TS0601"
    deviceProfileName: "fans-fan-level-light-switch"
  - id: "fp_4f6aee41fe"
    manufacturer: "_TZE204_bxoo2swd"
    model: "TS0601"
    deviceProfileName: "lights-dimmer-2"
  - id: "fp_958d61a2b3"
    manufacturer: "_TZE204_dcnsggvz"
    model: "TS0601"
    deviceProfileName: "lights-dimmer"
  - id: "fp_14b87bc47f"
    manufacturer: "_TZE204_drs6j6m5"
    model: "TS0601"
    deviceProfileName: "lights-dimmer"
  - id: "fp_7643dd7267"
    manufacturer: "_TZE204_hlx9tnzb"
    model: "TS0601"
    deviceProfileName: "lights-dimmer-options-ts0601"
  - id: "fp_23f7928e3c"
    manufacturer: "_TZE204_lawxy9e2"
    model: "TS0601"
    deviceProfileName: "fans-fan-light-switch"
  - id: "fp_4b4d781649"
    manufacturer: "_TZE204_n9ctkb6j"
    model: "TS0601"
    deviceProfileName: "lights-dimmer-options-ts0601"
  - id: "fp_2373d9c176"
    manufacturer: "_TZE204_r32ctezx"
    model: "TS0601"
    deviceProfileName: "fans-switch-fan-mode-ef00"
  - id: "fp_826b256ec9"
    manufacturer: "_TZE204_vevc4c6g"
    model: "TS0601"
    deviceProfileName: "lights-dimmer-options-ts0601"
  - id: "fp_8f29ec5734"
    manufacturer: "_TZE204_zenj4lxv"
    model: "TS0601"
    deviceProfileName: "lights-dimmer-2"
  - id: "fp_bc2a6930a1"
    manufacturer: "_TZE204_znvwzxkq"
    model: "TS0601"
    deviceProfileName: "lights-dimmer-3"
  - id: "fp_1fab3d2dc9"
    manufacturer: "_TZE284_68utemio"
    model: "TS0601"
    deviceProfileName: "lights-dimmer-options-ts0601"
  - id: "fp_1ca35e8348"
    manufacturer: "_TZE284_ikul00sx"
    model: "TS0601"
    deviceProfileName: "fans-fan-level-light-dimmer"
  - id: "fp_fd6555492a"
    manufacturer: "_TZE284_m1cvyneb"
    model: "TS0601"
    deviceProfileName: "lights-dimmer-options-ts0601"
  - id: "fp_4c2cda415f"
    manufacturer: "_TZE284_tgeqdjgk"
    model: "TS0601"
    deviceProfileName: "lights-color-temperature"
  - id: "fp_d71f5b89aa"
    manufacturer: "_TZE284_z5jz7wpo"
    model: "TS0601"
    deviceProfileName: "fans-switch-fan-mode-ef00"
  - id: "fp_112711dd3a"
    manufacturer: "_TZE284_znvwzxkq"
    model: "TS0601"
    deviceProfileName: "lights-dimmer-3"
  - id: "fp_48c5803655"
    manufacturer: "_TZE28C1000000_z5jz7wpo"
    model: "TS0601"
    deviceProfileName: "fans-switch-fan-mode-ef00"
