zigbeeManufacturer:
  - id: "fp_8e35866676"
    manufacturer: "'_TZ32101000000_5oy7cysk'"
    model: "TS0210"
    deviceProfileName: "safety-wave19-tuya-ts0210-quoted"
  - id: "fp_73929d3d0f"
    manufacturer: "HEIMAN"
    model: "HS2AQ-EF-3.0"
    deviceProfileName: "sensors-wave19-heiman-hs2aq-ef-three"
  - id: "fp_5852d6dd82"
    manufacturer: "LinknLink"
    model: "eMotion Air"
    deviceProfileName: "sensors-linknlink-emotion-air"
  - id: "fp_874cbd971f"
    manufacturer: "PLAID SYSTEMS"
    model: "PS-SPRZMS-SLP3"
    deviceProfileName: "sensors-wave19-plaid-spruce"
  - id: "fp_3a4d979ba1"
    manufacturer: "Shelly"
    model: "Presence"
    deviceProfileName: "sensors-shelly-presence-gen4"
  - id: "fp_ffb5dec29a"
    manufacturer: "_TZ3000_eit7p838 "
    model: "TS0207"
    deviceProfileName: "safety-water-leak-tamper-battery-low-battery"
  - id: "fp_4cc27816a0"
    manufacturer: "eWeLink"
    model: "CK-TLSR8656-Z123SE22DY-01(7035)"
    deviceProfileName: "safety-wave19-ewelink-7035"
  - id: "fp_9c9c0cfe23"
    manufacturer: "eWeLink"
    model: "CK-TLSR8656-Z123SE24DY-01(7037)"
    deviceProfileName: "safety-co-detector-battery-voltage-ewelink-7037"
  - id: "fp_bcbb35d4d4"
    manufacturer: "eWeLink"
    model: "CK-TLSR8656-Z23SE11HW-01(7019)"
    deviceProfileName: "safety-water-leak-battery-low-battery"
