name: thermostats-wave6a-futurehome
components:
  - id: main
    capabilities:
      - {id: thermostatMode, version: 1}
      - {id: thermostatHeatingSetpoint, version: 1}
      - {id: thermostatOperatingState, version: 1}
      - {id: temperatureMeasurement, version: 1}
      - {id: energyMeter, version: 1}
      - {id: concertmirror08464.fhThermostatPreset, version: 1}
      - {id: concertmirror08464.fhThermostatSensor, version: 1}
      - {id: concertmirror08464.fhThermostatFloorTemperature, version: 1}
      - {id: concertmirror08464.fhThermostatTempCalibration, version: 1}
      - {id: concertmirror08464.fhThermostatChildLock, version: 1}
      - {id: concertmirror08464.fhThermostatWindowDetection, version: 1}
      - {id: concertmirror08464.fhThermostatHysteresis, version: 1}
      - {id: concertmirror08464.fhThermostatMaxGuardTemp, version: 1}
      - {id: refresh, version: 1}
    categories: [{name: Thermostat}]
