name: thermostats-wave12-engo-e25-230
components:
  - id: main
    capabilities:
      - {id: switch, version: 1}
      - {id: thermostatMode, version: 1}
      - {id: thermostatHeatingSetpoint, version: 1}
      - {id: thermostatOperatingState, version: 1}
      - {id: temperatureMeasurement, version: 1}
      - {id: concertmirror08464.engoE25TempCalibration, version: 1}
      - {id: concertmirror08464.engoE25MaxTemperature, version: 1}
      - {id: concertmirror08464.engoE25MinTemperature, version: 1}
      - {id: concertmirror08464.engoE25ChildLock, version: 1}
      - {id: concertmirror08464.engoE25Backlight, version: 1}
      - {id: concertmirror08464.engoE25Preset, version: 1}
      - {id: concertmirror08464.engoE25ControlAlgorithm, version: 1}
      - {id: concertmirror08464.engoE25FrostSet, version: 1}
      - {id: concertmirror08464.engoE25ValveProtection, version: 1}
      - {id: concertmirror08464.engoE25RelayMode, version: 1}
      - {id: refresh, version: 1}
    categories: [{name: Thermostat}]
