zigbeeManufacturer:
  - id: "fp_f19b6038ea"
    manufacturer: "Aubess"
    model: "1005005194831629"
    deviceProfileName: "safety-contact-temp-humidity-battery"
  - id: "fp_8fb2e4a718"
    manufacturer: "CAT0001"
    model: "Excellux"
    deviceProfileName: "safety-vibration-battery"
  - id: "fp_b950c8a2fc"
    manufacturer: "Conecto"
    model: "COZIGVS"
    deviceProfileName: "safety-acceleration-4cqhd2ha"
  - id: "fp_83cc546fce"
    manufacturer: "DYGSM"
    model: "DY-RQ500A"
    deviceProfileName: "safety-gas-detector-alarm-time-ringtone"
  - id: "fp_624a85e6f7"
    manufacturer: "HOBEIAN"
    model: "ZG-102ZM"
    deviceProfileName: "safety-acceleration-contact-battery-zg102zm"
  - id: "fp_4e51557a2d"
    manufacturer: "HOBEIAN"
    model: "ZG-223Z"
    deviceProfileName: "safety-water-leak-illuminance-battery-zg223z"
  - id: "fp_d706096345"
    manufacturer: "HOBEIAN"
    model: "ZG-226Z"
    deviceProfileName: "safety-water-leak-alarm-battery-zg226z"
  - id: "fp_067f19cf5f"
    manufacturer: "HOBEIAN"
    model: "ZG-228Z"
    deviceProfileName: "safety-acceleration-alarm-battery-zg228z"
  - id: "fp_1d02167be0"
    manufacturer: "HOBEIAN"
    model: "ZG-229Z"
    deviceProfileName: "safety-alarm-battery-zg229z"
  - id: "fp_398b3ee93b"
    manufacturer: "NEO"
    model: "NAS-WS02B0"
    deviceProfileName: "safety-water-leak"
  - id: "fp_dea60ec9bf"
    manufacturer: "Nous"
    model: "E8"
    deviceProfileName: "safety-smoke-detector-battery"
  - id: "fp_3c08ddd703"
    manufacturer: "PIRIV01"
    model: "Excellux"
    deviceProfileName: "safety-motion-vibration-illuminance-battery"
  - id: "fp_c23c485187"
    manufacturer: "TZE200_0zaf1cr8"
    model: "TS0601"
    deviceProfileName: "safety-smoke-detector-battery"
  - id: "fp_ccccce5020"
    manufacturer: "VABRATE"
    model: "Excellux"
    deviceProfileName: "safety-acceleration-battery"
  - id: "fp_60f75aa06e"
    manufacturer: "_TZE200_0zaf1cr8"
    model: "TS0601"
    deviceProfileName: "safety-smoke-detector-battery"
  - id: "fp_43d06794ac"
    manufacturer: "_TZE200_2pddnnrk"
    model: "TS0601"
    deviceProfileName: "safety-water-leak-illuminance-battery-zg223z"
  - id: "fp_1a0396e369"
    manufacturer: "_TZE200_5d3vhjro"
    model: "TS0601"
    deviceProfileName: "safety-smoke-detector-battery"
  - id: "fp_2790984edf"
    manufacturer: "_TZE200_7bztmfm1"
    model: "TS0601"
    deviceProfileName: "safety-co-detector"
  - id: "fp_e392451f33"
    manufacturer: "_TZE200_8isdky6j"
    model: "TS0601"
    deviceProfileName: "safety-gas-detector-zg225z"
  - id: "fp_7cdd1f4c74"
    manufacturer: "_TZE200_8ply8mjj"
    model: "TS0601"
    deviceProfileName: "safety-acceleration-4cqhd2ha"
  - id: "fp_631fe43191"
    manufacturer: "_TZE200_afycb3cg"
    model: "TS0601"
    deviceProfileName: "safety-acceleration-battery-zg103z"
  - id: "fp_80a7126752"
    manufacturer: "_TZE200_aj0oxo1i"
    model: "TS0225"
    deviceProfileName: "safety-gas-detector-zg225z"
  - id: "fp_4363fe2c98"
    manufacturer: "_TZE200_aycxwiau"
    model: "TS0601"
    deviceProfileName: "safety-smoke-detector-battery"
  - id: "fp_15a355683d"
    manufacturer: "_TZE200_bxdyeaa9"
    model: "TS0601"
    deviceProfileName: "safety-smoke-detector-battery"
  - id: "fp_2feb8c9d60"
    manufacturer: "_TZE200_dnz6yvl2"
    model: "TS0601"
    deviceProfileName: "safety-smoke-detector-battery"
  - id: "fp_147415b5d5"
    manufacturer: "_TZE200_dq1mfjug"
    model: "TS0601"
    deviceProfileName: "safety-smoke-detector-battery"
  - id: "fp_f9fa465508"
    manufacturer: "_TZE200_e2bedvo9"
    model: "TS0601"
    deviceProfileName: "safety-smoke-detector-battery"
  - id: "fp_a00dd31661"
    manufacturer: "_TZE200_ft523twt"
    model: "TS0601"
    deviceProfileName: "safety-smoke-detector-battery"
  - id: "fp_3b44078ac4"
    manufacturer: "_TZE200_fwoorn8y"
    model: "TS0601"
    deviceProfileName: "safety-contact-battery"
  - id: "fp_4c6ee96899"
    manufacturer: "_TZE200_ggev5fsl"
    model: "TS0601"
    deviceProfileName: "safety-gas-detector-self-test"
  - id: "fp_3ff8103f30"
    manufacturer: "_TZE200_hggxgsjj"
    model: "TS0601"
    deviceProfileName: "safety-acceleration-battery-zg103z"
  - id: "fp_604022a8d7"
    manufacturer: "_TZE200_iba1ckek"
    model: "TS0601"
    deviceProfileName: "safety-acceleration-battery-zg103z"
  - id: "fp_c1634b3454"
    manufacturer: "_TZE200_ijey4q29"
    model: "TS0601"
    deviceProfileName: "safety-contact-illuminance-battery"
  - id: "fp_f0585ff8d6"
    manufacturer: "_TZE200_ioxkjvuz"
    model: "TS0601"
    deviceProfileName: "safety-gas-detector"
  - id: "fp_98bfbc917f"
    manufacturer: "_TZE200_iuk8kupi"
    model: "TS0601"
    deviceProfileName: "safety-gas-co-detector"
  - id: "fp_6e7cba706b"
    manufacturer: "_TZE200_j7sgd8po"
    model: "TS0601"
    deviceProfileName: "safety-contact-temp-humidity-battery-s8"
  - id: "fp_102958bf66"
    manufacturer: "_TZE200_jfw0a4aa"
    model: "TS0601"
    deviceProfileName: "safety-acceleration-contact-battery-zg102zm"
  - id: "fp_05c8dd18f7"
    manufacturer: "_TZE200_jsaqgakf"
    model: "TS0601"
    deviceProfileName: "safety-water-leak-illuminance-battery-zg223z"
  - id: "fp_185c5eaf83"
    manufacturer: "_TZE200_jthf7vb6"
    model: "TS0601"
    deviceProfileName: "safety-water-leak-battery"
  - id: "fp_e628d9ad14"
    manufacturer: "_TZE200_kf2hbko4"
    model: "TS0601"
    deviceProfileName: "safety-contact-illuminance-battery"
  - id: "fp_4aa75056a0"
    manufacturer: "_TZE200_kltffuzl"
    model: "TS0601"
    deviceProfileName: "safety-contact-battery"
  - id: "fp_6118662d5b"
    manufacturer: "_TZE200_kvpwq8z7"
    model: "TS0601"
    deviceProfileName: "safety-gas-detector-self-test"
  - id: "fp_6327f421ea"
    manufacturer: "_TZE200_kzm5w4iz"
    model: "TS0601"
    deviceProfileName: "safety-vibration-battery"
  - id: "fp_56c17dbd42"
    manufacturer: "_TZE200_m9skfctm"
    model: "TS0601"
    deviceProfileName: "safety-smoke-detector-battery"
  - id: "fp_574838288f"
    manufacturer: "_TZE200_mby4kbtq"
    model: "TS0601"
    deviceProfileName: "safety-gas-detector"
  - id: "fp_1653b16e33"
    manufacturer: "_TZE200_ntcy3xu1"
    model: "TS0601"
    deviceProfileName: "safety-smoke-detector-battery"
  - id: "fp_7d6a18233c"
    manufacturer: "_TZE200_nus5kk3n"
    model: "TS0601"
    deviceProfileName: "safety-gas-detector"
  - id: "fp_b4f6fe004c"
    manufacturer: "_TZE200_nvups4nh"
    model: "TS0601"
    deviceProfileName: "safety-contact-temp-humidity-battery"
  - id: "fp_20e918b7f0"
    manufacturer: "_TZE200_p6fuhvez"
    model: "TS0225"
    deviceProfileName: "safety-gas-detector-zg225z"
  - id: "fp_3d48f41552"
    manufacturer: "_TZE200_pay2byax"
    model: "TS0601"
    deviceProfileName: "safety-contact-illuminance-battery"
  - id: "fp_25e45f16bc"
    manufacturer: "_TZE200_qq9mpfhw"
    model: "TS0601"
    deviceProfileName: "safety-water-leak"
  - id: "fp_31da5ec568"
    manufacturer: "_TZE200_qtbrwrfv"
    model: "TS0601"
    deviceProfileName: "safety-smoke-detector-battery"
  - id: "fp_50546fcbb9"
    manufacturer: "_TZE200_rccxox8p"
    model: "TS0601"
    deviceProfileName: "safety-smoke-detector-battery"
  - id: "fp_0089335766"
    manufacturer: "_TZE200_t5p1vj8r"
    model: "TS0601"
    deviceProfileName: "safety-smoke-detector-battery"
  - id: "fp_187436162b"
    manufacturer: "_TZE200_u319yc66"
    model: "TS0601"
    deviceProfileName: "safety-gas-detector-self-test"
  - id: "fp_b25f0f02d8"
    manufacturer: "_TZE200_u6x1zyv2"
    model: "TS0601"
    deviceProfileName: "safety-water-leak-illuminance-battery-zg223z"
  - id: "fp_dc55418866"
    manufacturer: "_TZE200_uebojraa"
    model: "TS0601"
    deviceProfileName: "safety-smoke-detector-battery"
  - id: "fp_98267af1e0"
    manufacturer: "_TZE200_ux5v4dbd"
    model: "TS0601"
    deviceProfileName: "safety-smoke-detector-battery"
  - id: "fp_48e993b068"
    manufacturer: "_TZE200_vzekyi4c"
    model: "TS0601"
    deviceProfileName: "safety-smoke-detector-battery"
  - id: "fp_726cf468e2"
    manufacturer: "_TZE200_wzk0x7fq"
    model: "TS0601"
    deviceProfileName: "safety-acceleration-contact-battery-zg102zm"
  - id: "fp_1c49805e50"
    manufacturer: "_TZE200_yh7aoahi"
    model: "TS0601"
    deviceProfileName: "safety-smoke-detector-battery"
  - id: "fp_0d42bd1002"
    manufacturer: "_TZE200_yjryxpot"
    model: "TS0601"
    deviceProfileName: "safety-acceleration-battery-zg103z"
  - id: "fp_f519214d84"
    manufacturer: "_TZE200_ykglasuj"
    model: "TS0601"
    deviceProfileName: "safety-contact-illuminance-battery"
  - id: "fp_f1024e8167"
    manufacturer: "_TZE200_yojqa8xn"
    model: "TS0601"
    deviceProfileName: "safety-gas-detector-alarm-time-ringtone"
  - id: "fp_3ac93e0152"
    manufacturer: "_TZE200_ytibqbra"
    model: "TS0601"
    deviceProfileName: "safety-smoke-detector-battery"
  - id: "fp_e3f782e882"
    manufacturer: "_TZE200_ytx9fudw"
    model: "TS0601"
    deviceProfileName: "safety-contact-tamper-battery-opening"
  - id: "fp_efc3adf43b"
    manufacturer: "_TZE204_7bztmfm1"
    model: "TS0601"
    deviceProfileName: "safety-co-detector"
  - id: "fp_b09040ac6d"
    manufacturer: "_TZE204_chbyv06x"
    model: "TS0601"
    deviceProfileName: "safety-gas-detector-alarm-time-ringtone"
  - id: "fp_4c99330a40"
    manufacturer: "_TZE204_fncxk3ob"
    model: "TS0601"
    deviceProfileName: "safety-alarm-battery-duration-volume-ringtone-yxzbsl"
  - id: "fp_3d177b87ff"
    manufacturer: "_TZE204_hcxvyxa5"
    model: "TS0601"
    deviceProfileName: "safety-alarm-duration-volume-ringtone-za03"
  - id: "fp_7fa1b3db58"
    manufacturer: "_TZE204_iuk8kupi"
    model: "TS0601"
    deviceProfileName: "safety-gas-co-detector"
  - id: "fp_dfaad68269"
    manufacturer: "_TZE204_k7mfgaen"
    model: "TS0601"
    deviceProfileName: "safety-alarm-battery-duration-volume-ringtone-yxzbsl"
  - id: "fp_96457ae437"
    manufacturer: "_TZE204_kgaxpvxr"
    model: "TS0601"
    deviceProfileName: "safety-smoke-detector-battery-288wz"
  - id: "fp_22275fe5ad"
    manufacturer: "_TZE204_kvpwq8z7"
    model: "TS0601"
    deviceProfileName: "safety-gas-detector-self-test"
  - id: "fp_ddd909d7b1"
    manufacturer: "_TZE204_mby4kbtq"
    model: "TS0601"
    deviceProfileName: "safety-gas-detector"
  - id: "fp_dea4279a6d"
    manufacturer: "_TZE204_ntcy3xu1"
    model: "TS0601"
    deviceProfileName: "safety-smoke-detector-battery"
  - id: "fp_dbcfc30d34"
    manufacturer: "_TZE204_uo8qcagc"
    model: "TS0601"
    deviceProfileName: "safety-gas-detector"
  - id: "fp_fe02f658ac"
    manufacturer: "_TZE204_v6iczj35"
    model: "TS0601"
    deviceProfileName: "safety-gas-detector"
  - id: "fp_3cd0b6b072"
    manufacturer: "_TZE204_vawy74yh"
    model: "TS0601"
    deviceProfileName: "safety-smoke-detector-battery"
  - id: "fp_906140e411"
    manufacturer: "_TZE204_yojqa8xn"
    model: "TS0601"
    deviceProfileName: "safety-gas-detector-alarm-time-ringtone"
  - id: "fp_c77e77892d"
    manufacturer: "_TZE204_zougpkpy"
    model: "TS0601"
    deviceProfileName: "safety-gas-detector-alarm-time-ringtone"
  - id: "fp_c8e6cef9c4"
    manufacturer: "_TZE284_0zaf1cr8"
    model: "TS0601"
    deviceProfileName: "safety-smoke-detector-battery"
  - id: "fp_4836f65e1a"
    manufacturer: "_TZE284_4cqhd2ha"
    model: "TS0601"
    deviceProfileName: "safety-acceleration-4cqhd2ha"
  - id: "fp_89113f93b8"
    manufacturer: "_TZE284_6teua268"
    model: "TS0601"
    deviceProfileName: "safety-contact-battery-senoro-win-v2"
  - id: "fp_8bfdcb5249"
    manufacturer: "_TZE284_6ycgarab"
    model: "TS0601"
    deviceProfileName: "safety-smoke-co-detector-battery"
  - id: "fp_1a0ac9708f"
    manufacturer: "_TZE284_ai4rqhky"
    model: "TS0601"
    deviceProfileName: "safety-smoke-detector-battery"
  - id: "fp_5973485207"
    manufacturer: "_TZE284_chbyv06x"
    model: "TS0601"
    deviceProfileName: "safety-gas-detector-alarm-time-ringtone"
  - id: "fp_7a5ef5f589"
    manufacturer: "_TZE284_e2bedvo9"
    model: "TS0601"
    deviceProfileName: "safety-smoke-detector-battery"
  - id: "fp_b447466296"
    manufacturer: "_TZE284_fncxk3ob"
    model: "TS0601"
    deviceProfileName: "safety-alarm-battery-duration-volume-ringtone-yxzbsl"
  - id: "fp_11f1abf66b"
    manufacturer: "_TZE284_gyzlwu5q"
    model: "TS0601"
    deviceProfileName: "safety-smoke-temp-humidity-battery"
  - id: "fp_742013d63d"
    manufacturer: "_TZE284_n4ttsck2"
    model: "TS0601"
    deviceProfileName: "safety-smoke-detector-battery-288wz"
  - id: "fp_c8e6c8af2d"
    manufacturer: "_TZE284_rccxox8p"
    model: "TS0601"
    deviceProfileName: "safety-smoke-detector-battery"
