name: thermostats-thermostat-tervix
components:
  - id: main
    capabilities:
      - id: thermostatMode
        version: 1
      - id: thermostatHeatingSetpoint
        version: 1
      - id: thermostatOperatingState
        version: 1
      - id: temperatureMeasurement
        version: 1
      - id: relativeHumidityMeasurement
        version: 1
      - id: concertmirror08464.thermostatPresetTervixProgram
        version: 1
      - id: concertmirror08464.tervixMode
        version: 1
      - id: concertmirror08464.tervixRunMode
        version: 1
      - id: concertmirror08464.tervixWorkingStatus
        version: 1
      - id: concertmirror08464.tervixWindowCheck
        version: 1
      - id: concertmirror08464.tervixWindowState
        version: 1
      - id: concertmirror08464.tervixFrostProtection
        version: 1
      - id: concertmirror08464.tervixChildLock
        version: 1
      - id: concertmirror08464.tervixSensorChoose
        version: 1
      - id: concertmirror08464.tervixTempCorrection
        version: 1
      - id: concertmirror08464.tervixUpperTemp
        version: 1
      - id: concertmirror08464.tervixSwitchSensitivity
        version: 1
      - id: concertmirror08464.tervixFloorTempProtection
        version: 1
      - id: concertmirror08464.tervixFloorLowProtection
        version: 1
      - id: concertmirror08464.tervixWindowDetectTime
        version: 1
      - id: concertmirror08464.tervixWindowDetectTemp
        version: 1
      - id: concertmirror08464.tervixWindowDelayTime
        version: 1
      - id: concertmirror08464.tervixHumidityControl
        version: 1
      - id: concertmirror08464.tervixUpperHumidityLimit
        version: 1
      - id: concertmirror08464.tervixWeekProgramPeriods
        version: 1
      - id: concertmirror08464.tervixFactoryReset
        version: 1
      - id: refresh
        version: 1
    categories:
      - name: Thermostat
deviceConfig:
  dashboard:
    states:
      - component: main
        capability: thermostatHeatingSetpoint
        version: 1
        group: main
    actions: []
    basicPlus: []
  detailView:
    - component: main
      capability: thermostatMode
      version: 1
    - component: main
      capability: thermostatHeatingSetpoint
      version: 1
    - component: main
      capability: thermostatOperatingState
      version: 1
    - component: main
      capability: temperatureMeasurement
      version: 1
    - component: main
      capability: relativeHumidityMeasurement
      version: 1
    - component: main
      capability: concertmirror08464.thermostatPresetTervixProgram
      version: 1
    - component: main
      capability: concertmirror08464.tervixMode
      version: 1
    - component: main
      capability: concertmirror08464.tervixRunMode
      version: 1
    - component: main
      capability: concertmirror08464.tervixWorkingStatus
      version: 1
    - component: main
      capability: concertmirror08464.tervixWindowCheck
      version: 1
    - component: main
      capability: concertmirror08464.tervixWindowState
      version: 1
    - component: main
      capability: concertmirror08464.tervixFrostProtection
      version: 1
    - component: main
      capability: concertmirror08464.tervixChildLock
      version: 1
    - component: main
      capability: concertmirror08464.tervixSensorChoose
      version: 1
    - component: main
      capability: concertmirror08464.tervixTempCorrection
      version: 1
    - component: main
      capability: concertmirror08464.tervixUpperTemp
      version: 1
    - component: main
      capability: concertmirror08464.tervixSwitchSensitivity
      version: 1
    - component: main
      capability: concertmirror08464.tervixFloorTempProtection
      version: 1
    - component: main
      capability: concertmirror08464.tervixFloorLowProtection
      version: 1
    - component: main
      capability: concertmirror08464.tervixWindowDetectTime
      version: 1
    - component: main
      capability: concertmirror08464.tervixWindowDetectTemp
      version: 1
    - component: main
      capability: concertmirror08464.tervixWindowDelayTime
      version: 1
    - component: main
      capability: concertmirror08464.tervixHumidityControl
      version: 1
    - component: main
      capability: concertmirror08464.tervixUpperHumidityLimit
      version: 1
    - component: main
      capability: concertmirror08464.tervixWeekProgramPeriods
      version: 1
    - component: main
      capability: concertmirror08464.tervixFactoryReset
      version: 1
    - component: main
      capability: refresh
      version: 1
  automation:
    conditions:
      - component: main
        capability: thermostatMode
        version: 1
      - component: main
        capability: thermostatHeatingSetpoint
        version: 1
      - component: main
        capability: thermostatOperatingState
        version: 1
      - component: main
        capability: temperatureMeasurement
        version: 1
      - component: main
        capability: relativeHumidityMeasurement
        version: 1
      - component: main
        capability: concertmirror08464.thermostatPresetTervixProgram
        version: 1
      - component: main
        capability: concertmirror08464.tervixMode
        version: 1
      - component: main
        capability: concertmirror08464.tervixRunMode
        version: 1
      - component: main
        capability: concertmirror08464.tervixWorkingStatus
        version: 1
      - component: main
        capability: concertmirror08464.tervixWindowCheck
        version: 1
      - component: main
        capability: concertmirror08464.tervixWindowState
        version: 1
      - component: main
        capability: concertmirror08464.tervixFrostProtection
        version: 1
      - component: main
        capability: concertmirror08464.tervixChildLock
        version: 1
      - component: main
        capability: concertmirror08464.tervixSensorChoose
        version: 1
      - component: main
        capability: concertmirror08464.tervixTempCorrection
        version: 1
      - component: main
        capability: concertmirror08464.tervixUpperTemp
        version: 1
      - component: main
        capability: concertmirror08464.tervixSwitchSensitivity
        version: 1
      - component: main
        capability: concertmirror08464.tervixFloorTempProtection
        version: 1
      - component: main
        capability: concertmirror08464.tervixFloorLowProtection
        version: 1
      - component: main
        capability: concertmirror08464.tervixWindowDetectTime
        version: 1
      - component: main
        capability: concertmirror08464.tervixWindowDetectTemp
        version: 1
      - component: main
        capability: concertmirror08464.tervixWindowDelayTime
        version: 1
      - component: main
        capability: concertmirror08464.tervixHumidityControl
        version: 1
      - component: main
        capability: concertmirror08464.tervixUpperHumidityLimit
        version: 1
      - component: main
        capability: concertmirror08464.tervixWeekProgramPeriods
        version: 1
      - component: main
        capability: concertmirror08464.tervixFactoryReset
        version: 1
    actions:
      - component: main
        capability: thermostatMode
        version: 1
      - component: main
        capability: thermostatHeatingSetpoint
        version: 1
      - component: main
        capability: concertmirror08464.thermostatPresetTervixProgram
        version: 1
      - component: main
        capability: concertmirror08464.tervixMode
        version: 1
      - component: main
        capability: concertmirror08464.tervixRunMode
        version: 1
      - component: main
        capability: concertmirror08464.tervixWindowCheck
        version: 1
      - component: main
        capability: concertmirror08464.tervixFrostProtection
        version: 1
      - component: main
        capability: concertmirror08464.tervixChildLock
        version: 1
      - component: main
        capability: concertmirror08464.tervixSensorChoose
        version: 1
      - component: main
        capability: concertmirror08464.tervixTempCorrection
        version: 1
      - component: main
        capability: concertmirror08464.tervixUpperTemp
        version: 1
      - component: main
        capability: concertmirror08464.tervixSwitchSensitivity
        version: 1
      - component: main
        capability: concertmirror08464.tervixFloorTempProtection
        version: 1
      - component: main
        capability: concertmirror08464.tervixFloorLowProtection
        version: 1
      - component: main
        capability: concertmirror08464.tervixWindowDetectTime
        version: 1
      - component: main
        capability: concertmirror08464.tervixWindowDetectTemp
        version: 1
      - component: main
        capability: concertmirror08464.tervixWindowDelayTime
        version: 1
      - component: main
        capability: concertmirror08464.tervixHumidityControl
        version: 1
      - component: main
        capability: concertmirror08464.tervixUpperHumidityLimit
        version: 1
      - component: main
        capability: concertmirror08464.tervixFactoryReset
        version: 1
