name: thermostats-thermostat-pilot-wire-no-operating
components:
  - id: main
    capabilities:
      - id: thermostatMode
        version: 1
      - id: thermostatHeatingSetpoint
        version: 1
      - id: temperatureMeasurement
        version: 1
      - id: powerMeter
        version: 1
      - id: voltageMeasurement
        version: 1
      - id: currentMeasurement
        version: 1
      - id: energyMeter
        version: 1
      - id: concertmirror08464.pilotWirePreset
        version: 1
      - id: concertmirror08464.pilotWireChildLock
        version: 1
      - id: concertmirror08464.windowDetectionPilotWire
        version: 1
      - id: concertmirror08464.pilotWireWindow
        version: 1
      - id: concertmirror08464.pilotWireDeviceModeType
        version: 1
      - id: concertmirror08464.pilotWireTempCalibration
        version: 1
      - id: concertmirror08464.pilotWireTempSensibility
        version: 1
      - id: concertmirror08464.energyTodayPilotWire
        version: 1
      - id: concertmirror08464.energyYesterdayPilotWire
        version: 1
      - id: concertmirror08464.pilotWireFault
        version: 1
      - id: refresh
        version: 1
    categories:
      - name: Thermostat
deviceConfig:
  dashboard:
    states:
      - component: main
        capability: thermostatHeatingSetpoint
        version: 1
        group: main
    actions: []
    basicPlus: []
  detailView:
    - component: main
      capability: thermostatMode
      version: 1
    - component: main
      capability: thermostatHeatingSetpoint
      version: 1
    - component: main
      capability: temperatureMeasurement
      version: 1
    - component: main
      capability: powerMeter
      version: 1
    - component: main
      capability: voltageMeasurement
      version: 1
    - component: main
      capability: currentMeasurement
      version: 1
    - component: main
      capability: energyMeter
      version: 1
    - component: main
      capability: concertmirror08464.pilotWirePreset
      version: 1
    - component: main
      capability: concertmirror08464.pilotWireChildLock
      version: 1
    - component: main
      capability: concertmirror08464.windowDetectionPilotWire
      version: 1
    - component: main
      capability: concertmirror08464.pilotWireWindow
      version: 1
    - component: main
      capability: concertmirror08464.pilotWireDeviceModeType
      version: 1
    - component: main
      capability: concertmirror08464.pilotWireTempCalibration
      version: 1
    - component: main
      capability: concertmirror08464.pilotWireTempSensibility
      version: 1
    - component: main
      capability: concertmirror08464.energyTodayPilotWire
      version: 1
    - component: main
      capability: concertmirror08464.energyYesterdayPilotWire
      version: 1
    - component: main
      capability: concertmirror08464.pilotWireFault
      version: 1
    - component: main
      capability: refresh
      version: 1
  automation:
    conditions:
      - component: main
        capability: thermostatMode
        version: 1
      - component: main
        capability: thermostatHeatingSetpoint
        version: 1
      - component: main
        capability: temperatureMeasurement
        version: 1
      - component: main
        capability: powerMeter
        version: 1
      - component: main
        capability: voltageMeasurement
        version: 1
      - component: main
        capability: currentMeasurement
        version: 1
      - component: main
        capability: energyMeter
        version: 1
      - component: main
        capability: concertmirror08464.pilotWirePreset
        version: 1
      - component: main
        capability: concertmirror08464.pilotWireChildLock
        version: 1
      - component: main
        capability: concertmirror08464.windowDetectionPilotWire
        version: 1
      - component: main
        capability: concertmirror08464.pilotWireWindow
        version: 1
      - component: main
        capability: concertmirror08464.pilotWireDeviceModeType
        version: 1
      - component: main
        capability: concertmirror08464.pilotWireTempCalibration
        version: 1
      - component: main
        capability: concertmirror08464.pilotWireTempSensibility
        version: 1
      - component: main
        capability: concertmirror08464.energyTodayPilotWire
        version: 1
      - component: main
        capability: concertmirror08464.energyYesterdayPilotWire
        version: 1
      - component: main
        capability: concertmirror08464.pilotWireFault
        version: 1
    actions:
      - component: main
        capability: thermostatMode
        version: 1
      - component: main
        capability: thermostatHeatingSetpoint
        version: 1
      - component: main
        capability: concertmirror08464.pilotWirePreset
        version: 1
      - component: main
        capability: concertmirror08464.pilotWireChildLock
        version: 1
      - component: main
        capability: concertmirror08464.windowDetectionPilotWire
        version: 1
      - component: main
        capability: concertmirror08464.pilotWireDeviceModeType
        version: 1
      - component: main
        capability: concertmirror08464.pilotWireTempCalibration
        version: 1
      - component: main
        capability: concertmirror08464.pilotWireTempSensibility
        version: 1
