name: switches-switch-2-ay301z-two
components:
  - id: main
    capabilities:
      - {id: switch, version: 1}
      - {id: concertmirror08464.ay301zTwoSwitchType, version: 1}
      - {id: concertmirror08464.ay301zTwoCountdownOne, version: 1}
      - {id: refresh, version: 1}
    categories:
      - {name: Switch}
  - id: switch2
    capabilities:
      - {id: switch, version: 1}
      - {id: concertmirror08464.ay301zTwoCountdownTwo, version: 1}
    categories:
      - {name: Switch}
