name: switches-switch-1-mli-tint
components:
  - id: main
    capabilities:
      - {id: switch, version: 1}
      - {id: concertmirror08464.mliTintPowerOnBehavior, version: 1}
      - {id: refresh, version: 1}
    categories:
      - name: Switch
