name: switches-wave14-sber-sbdv-00200-cover
components:
  - id: main
    capabilities:
      - {id: refresh, version: 1}
    categories:
      - name: Blind
  - id: cover
    capabilities:
      - {id: windowShade, version: 1}
      - {id: windowShadeLevel, version: 1}
      - {id: concertmirror08464.sber200CoverMode, version: 1}
      - {id: concertmirror08464.sber200CalibrationTime, version: 1}
      - {id: concertmirror08464.sber200MotorTimeout, version: 1}
      - {id: concertmirror08464.sber200ButtonsMode, version: 1}
      - {id: concertmirror08464.sber200CoverIdentify, version: 1}
      - {id: concertmirror08464.sber200CoverLedOffEnabled, version: 1}
      - {id: concertmirror08464.sber200CoverLedOffHue, version: 1}
      - {id: concertmirror08464.sber200CoverLedOffSaturation, version: 1}
      - {id: concertmirror08464.sber200CoverLedOffBrightness, version: 1}
      - {id: concertmirror08464.sber200ChildLock, version: 1}
      - {id: concertmirror08464.sber200SerialNumber, version: 1}
      - {id: concertmirror08464.sber200ResetsCount, version: 1}
      - {id: concertmirror08464.sber200Uptime, version: 1}
      - {id: concertmirror08464.sber200ButtonClicksOne, version: 1}
      - {id: concertmirror08464.sber200ButtonClicksTwo, version: 1}
      - {id: concertmirror08464.sber200ButtonClicksThree, version: 1}
      - {id: concertmirror08464.sber200RelaySwitchesOne, version: 1}
      - {id: concertmirror08464.sber200RelaySwitchesTwo, version: 1}
      - {id: concertmirror08464.sber200NeutralPresence, version: 1}
      - {id: concertmirror08464.sber200PowerProfile, version: 1}
      - {id: concertmirror08464.sber200LedIndicationType, version: 1}
    categories:
      - name: Blind
