name: switches-wave14-sber-sbdv-00199-cover
components:
  - id: main
    capabilities:
      - {id: refresh, version: 1}
    categories:
      - name: Blind
  - id: cover
    capabilities:
      - {id: windowShade, version: 1}
      - {id: windowShadeLevel, version: 1}
      - {id: concertmirror08464.sber199CoverMode, version: 1}
      - {id: concertmirror08464.sber199CalibrationTime, version: 1}
      - {id: concertmirror08464.sber199MotorTimeout, version: 1}
      - {id: concertmirror08464.sber199ButtonsMode, version: 1}
      - {id: concertmirror08464.sber199CoverIdentify, version: 1}
      - {id: concertmirror08464.sber199CoverLedOffEnabled, version: 1}
      - {id: concertmirror08464.sber199CoverLedOffHue, version: 1}
      - {id: concertmirror08464.sber199CoverLedOffSaturation, version: 1}
      - {id: concertmirror08464.sber199CoverLedOffBrightness, version: 1}
      - {id: concertmirror08464.sber199ChildLock, version: 1}
      - {id: concertmirror08464.sber199SerialNumber, version: 1}
      - {id: concertmirror08464.sber199ResetsCount, version: 1}
      - {id: concertmirror08464.sber199Uptime, version: 1}
      - {id: concertmirror08464.sber199ButtonClicksOne, version: 1}
      - {id: concertmirror08464.sber199ButtonClicksTwo, version: 1}
      - {id: concertmirror08464.sber199ButtonClicksThree, version: 1}
      - {id: concertmirror08464.sber199RelaySwitchesOne, version: 1}
      - {id: concertmirror08464.sber199RelaySwitchesTwo, version: 1}
    categories:
      - name: Blind
