name: safety-presence-mtg075-entry-controls-illuminance
components:
  - id: main
    capabilities:
      - id: presenceSensor
        version: 1
      - id: illuminanceMeasurement
        version: 1
      - id: concertmirror08464.mtg075TargetDistance
        version: 1
      - id: concertmirror08464.mtg075RadarSensitivity
        version: 1
      - id: concertmirror08464.mtg075DetectionRange
        version: 1
      - id: concertmirror08464.mtg075ShieldRange
        version: 1
      - id: concertmirror08464.mtg075EntrySensitivity
        version: 1
      - id: concertmirror08464.mtg075EntryIndentation
        version: 1
      - id: concertmirror08464.mtg075EntryFilterTime
        version: 1
      - id: concertmirror08464.mtg075DepartureDelay
        version: 1
      - id: concertmirror08464.mtg075BlockTime
        version: 1
      - id: concertmirror08464.mtg075IlluminanceThreshold
        version: 1
      - id: concertmirror08464.mtg075BreakerMode
        version: 1
      - id: concertmirror08464.mtg075BreakerStatus
        version: 1
      - id: concertmirror08464.mtg075BreakerPolarity
        version: 1
      - id: concertmirror08464.mtg075StatusIndication
        version: 1
      - id: concertmirror08464.mtg075SensorState
        version: 1
      - id: concertmirror08464.driverMessage
        version: 1
      - id: refresh
        version: 1
    categories:
      - name: PresenceSensor
deviceConfig:
  dashboard:
    states:
      - component: main
        capability: presenceSensor
        version: 1
        group: main
    actions: []
    basicPlus: []
  detailView:
    - component: main
      capability: presenceSensor
      version: 1
    - component: main
      capability: illuminanceMeasurement
      version: 1
    - component: main
      capability: concertmirror08464.mtg075TargetDistance
      version: 1
    - component: main
      capability: concertmirror08464.mtg075RadarSensitivity
      version: 1
    - component: main
      capability: concertmirror08464.mtg075DetectionRange
      version: 1
    - component: main
      capability: concertmirror08464.mtg075ShieldRange
      version: 1
    - component: main
      capability: concertmirror08464.mtg075EntrySensitivity
      version: 1
    - component: main
      capability: concertmirror08464.mtg075EntryIndentation
      version: 1
    - component: main
      capability: concertmirror08464.mtg075EntryFilterTime
      version: 1
    - component: main
      capability: concertmirror08464.mtg075DepartureDelay
      version: 1
    - component: main
      capability: concertmirror08464.mtg075BlockTime
      version: 1
    - component: main
      capability: concertmirror08464.mtg075IlluminanceThreshold
      version: 1
    - component: main
      capability: concertmirror08464.mtg075BreakerMode
      version: 1
    - component: main
      capability: concertmirror08464.mtg075BreakerStatus
      version: 1
    - component: main
      capability: concertmirror08464.mtg075BreakerPolarity
      version: 1
    - component: main
      capability: concertmirror08464.mtg075StatusIndication
      version: 1
    - component: main
      capability: concertmirror08464.mtg075SensorState
      version: 1
    - component: main
      capability: concertmirror08464.driverMessage
      version: 1
    - component: main
      capability: refresh
      version: 1
  automation:
    conditions:
      - component: main
        capability: presenceSensor
        version: 1
      - component: main
        capability: illuminanceMeasurement
        version: 1
      - component: main
        capability: concertmirror08464.mtg075TargetDistance
        version: 1
      - component: main
        capability: concertmirror08464.mtg075BreakerStatus
        version: 1
    actions:
      - component: main
        capability: concertmirror08464.mtg075RadarSensitivity
        version: 1
      - component: main
        capability: concertmirror08464.mtg075DetectionRange
        version: 1
      - component: main
        capability: concertmirror08464.mtg075ShieldRange
        version: 1
      - component: main
        capability: concertmirror08464.mtg075EntrySensitivity
        version: 1
      - component: main
        capability: concertmirror08464.mtg075EntryIndentation
        version: 1
      - component: main
        capability: concertmirror08464.mtg075EntryFilterTime
        version: 1
      - component: main
        capability: concertmirror08464.mtg075DepartureDelay
        version: 1
      - component: main
        capability: concertmirror08464.mtg075BlockTime
        version: 1
      - component: main
        capability: concertmirror08464.mtg075IlluminanceThreshold
        version: 1
      - component: main
        capability: concertmirror08464.mtg075BreakerMode
        version: 1
      - component: main
        capability: concertmirror08464.mtg075BreakerStatus
        version: 1
      - component: main
        capability: concertmirror08464.mtg075BreakerPolarity
        version: 1
      - component: main
        capability: concertmirror08464.mtg075StatusIndication
        version: 1
      - component: main
        capability: concertmirror08464.mtg075SensorState
        version: 1
