name: safety-presence-zym10024gv2-move-range-illuminance
components:
  - id: main
    capabilities:
      - id: presenceSensor
        version: 1
      - id: concertmirror08464.zym24gv2State
        version: 1
      - id: concertmirror08464.zym24gv2Sensitivity
        version: 1
      - id: concertmirror08464.zym24gv2MoveSensitivity
        version: 1
      - id: concertmirror08464.zym24gv2MinRange
        version: 1
      - id: concertmirror08464.zym24gv2MaxRange
        version: 1
      - id: concertmirror08464.zym24gv2Timeout
        version: 1
      - id: concertmirror08464.zym24gv2TargetDistance
        version: 1
      - id: illuminanceMeasurement
        version: 1
      - id: refresh
        version: 1
    categories:
      - name: PresenceSensor
deviceConfig:
  dashboard:
    states:
      - component: main
        capability: presenceSensor
        version: 1
        group: main
    actions: []
    basicPlus: []
  detailView:
    - component: main
      capability: presenceSensor
      version: 1
    - component: main
      capability: concertmirror08464.zym24gv2State
      version: 1
    - component: main
      capability: concertmirror08464.zym24gv2Sensitivity
      version: 1
    - component: main
      capability: concertmirror08464.zym24gv2MoveSensitivity
      version: 1
    - component: main
      capability: concertmirror08464.zym24gv2MinRange
      version: 1
    - component: main
      capability: concertmirror08464.zym24gv2MaxRange
      version: 1
    - component: main
      capability: concertmirror08464.zym24gv2Timeout
      version: 1
    - component: main
      capability: concertmirror08464.zym24gv2TargetDistance
      version: 1
    - component: main
      capability: illuminanceMeasurement
      version: 1
    - component: main
      capability: refresh
      version: 1
  automation:
    conditions:
      - component: main
        capability: presenceSensor
        version: 1
      - component: main
        capability: illuminanceMeasurement
        version: 1
      - component: main
        capability: concertmirror08464.zym24gv2State
        version: 1
      - component: main
        capability: concertmirror08464.zym24gv2TargetDistance
        version: 1
    actions:
      - component: main
        capability: concertmirror08464.zym24gv2Sensitivity
        version: 1
      - component: main
        capability: concertmirror08464.zym24gv2MoveSensitivity
        version: 1
      - component: main
        capability: concertmirror08464.zym24gv2MinRange
        version: 1
      - component: main
        capability: concertmirror08464.zym24gv2MaxRange
        version: 1
      - component: main
        capability: concertmirror08464.zym24gv2Timeout
        version: 1
