name: safety-occupancy-mtd085-illuminance
components:
  - id: main
    capabilities:
      - id: occupancySensor
        version: 1
      - id: illuminanceMeasurement
        version: 1
      - id: concertmirror08464.mtd085TargetDistance
        version: 1
      - id: concertmirror08464.mtd085RadarSensitivity
        version: 1
      - id: concertmirror08464.mtd085DetectionRange
        version: 1
      - id: concertmirror08464.mtd085ShieldRange
        version: 1
      - id: concertmirror08464.mtd085EntrySensitivity
        version: 1
      - id: concertmirror08464.mtd085EntryDistance
        version: 1
      - id: concertmirror08464.mtd085EntryFilterTime
        version: 1
      - id: concertmirror08464.mtd085DepartureDelay
        version: 1
      - id: concertmirror08464.mtd085BlockTime
        version: 1
      - id: concertmirror08464.mtd085StatusIndication
        version: 1
      - id: concertmirror08464.mtd085Sensor
        version: 1
      - id: concertmirror08464.mtd085ScenePreset
        version: 1
      - id: concertmirror08464.mtd085DistanceReportMode
        version: 1
      - id: concertmirror08464.mtd085DebugMode
        version: 1
      - id: concertmirror08464.mtd085DebugDistance
        version: 1
      - id: concertmirror08464.mtd085DebugCountdown
        version: 1
      - id: concertmirror08464.driverMessage
        version: 1
      - id: refresh
        version: 1
    categories:
      - name: PresenceSensor
deviceConfig:
  dashboard:
    states:
      - component: main
        capability: occupancySensor
        version: 1
        group: main
    actions: []
    basicPlus: []
  detailView:
    - component: main
      capability: occupancySensor
      version: 1
    - component: main
      capability: illuminanceMeasurement
      version: 1
    - component: main
      capability: concertmirror08464.mtd085TargetDistance
      version: 1
    - component: main
      capability: concertmirror08464.mtd085RadarSensitivity
      version: 1
    - component: main
      capability: concertmirror08464.mtd085DetectionRange
      version: 1
    - component: main
      capability: concertmirror08464.mtd085ShieldRange
      version: 1
    - component: main
      capability: concertmirror08464.mtd085EntrySensitivity
      version: 1
    - component: main
      capability: concertmirror08464.mtd085EntryDistance
      version: 1
    - component: main
      capability: concertmirror08464.mtd085EntryFilterTime
      version: 1
    - component: main
      capability: concertmirror08464.mtd085DepartureDelay
      version: 1
    - component: main
      capability: concertmirror08464.mtd085BlockTime
      version: 1
    - component: main
      capability: concertmirror08464.mtd085StatusIndication
      version: 1
    - component: main
      capability: concertmirror08464.mtd085Sensor
      version: 1
    - component: main
      capability: concertmirror08464.mtd085ScenePreset
      version: 1
    - component: main
      capability: concertmirror08464.mtd085DistanceReportMode
      version: 1
    - component: main
      capability: concertmirror08464.mtd085DebugMode
      version: 1
    - component: main
      capability: concertmirror08464.mtd085DebugDistance
      version: 1
    - component: main
      capability: concertmirror08464.mtd085DebugCountdown
      version: 1
    - component: main
      capability: concertmirror08464.driverMessage
      version: 1
    - component: main
      capability: refresh
      version: 1
  automation:
    conditions:
      - component: main
        capability: occupancySensor
        version: 1
      - component: main
        capability: illuminanceMeasurement
        version: 1
      - component: main
        capability: concertmirror08464.mtd085TargetDistance
        version: 1
      - component: main
        capability: concertmirror08464.mtd085DebugDistance
        version: 1
      - component: main
        capability: concertmirror08464.mtd085DebugCountdown
        version: 1
    actions:
      - component: main
        capability: concertmirror08464.mtd085RadarSensitivity
        version: 1
      - component: main
        capability: concertmirror08464.mtd085DetectionRange
        version: 1
      - component: main
        capability: concertmirror08464.mtd085ShieldRange
        version: 1
      - component: main
        capability: concertmirror08464.mtd085EntrySensitivity
        version: 1
      - component: main
        capability: concertmirror08464.mtd085EntryDistance
        version: 1
      - component: main
        capability: concertmirror08464.mtd085EntryFilterTime
        version: 1
      - component: main
        capability: concertmirror08464.mtd085DepartureDelay
        version: 1
      - component: main
        capability: concertmirror08464.mtd085BlockTime
        version: 1
      - component: main
        capability: concertmirror08464.mtd085StatusIndication
        version: 1
      - component: main
        capability: concertmirror08464.mtd085Sensor
        version: 1
      - component: main
        capability: concertmirror08464.mtd085ScenePreset
        version: 1
      - component: main
        capability: concertmirror08464.mtd085DistanceReportMode
        version: 1
      - component: main
        capability: concertmirror08464.mtd085DebugMode
        version: 1
