name: thermostats-wave12-avatto-trv60
components:
  - id: main
    capabilities:
      - {id: thermostatHeatingSetpoint, version: 1}
      - {id: temperatureMeasurement, version: 1}
      - {id: battery, version: 1}
      - {id: relativeHumidityMeasurement, version: 1}
      - {id: concertmirror08464.avattoTrvSixtyMode, version: 1}
      - {id: concertmirror08464.avattoTrvSixtyWorkState, version: 1}
      - {id: concertmirror08464.avattoTrvSixtyChildLock, version: 1}
      - {id: concertmirror08464.avattoTrvSixtyWindowDetection, version: 1}
      - {id: concertmirror08464.avattoTrvSixtyScheduleMonday, version: 1}
      - {id: concertmirror08464.avattoTrvSixtyScheduleTuesday, version: 1}
      - {id: concertmirror08464.avattoTrvSixtyScheduleWednesday, version: 1}
      - {id: concertmirror08464.avattoTrvSixtyScheduleThursday, version: 1}
      - {id: concertmirror08464.avattoTrvSixtyScheduleFriday, version: 1}
      - {id: concertmirror08464.avattoTrvSixtyScheduleSaturday, version: 1}
      - {id: concertmirror08464.avattoTrvSixtyScheduleSunday, version: 1}
      - {id: concertmirror08464.avattoTrvSixtyFault, version: 1}
      - {id: concertmirror08464.avattoTrvSixtyFrostProtection, version: 1}
      - {id: concertmirror08464.avattoTrvSixtyScaleProtection, version: 1}
      - {id: concertmirror08464.avattoTrvSixtyTempCalibration, version: 1}
      - {id: concertmirror08464.avattoTrvSixtyValveVolume, version: 1}
      - {id: concertmirror08464.avattoTrvSixtyDoorSensorOne, version: 1}
      - {id: concertmirror08464.avattoTrvSixtyDoorSensorTwo, version: 1}
      - {id: concertmirror08464.avattoTrvSixtyDoorSensorThree, version: 1}
      - {id: concertmirror08464.avattoTrvSixtyOutTemperature, version: 1}
      - {id: concertmirror08464.avattoTrvSixtyScreenOrientation, version: 1}
      - {id: refresh, version: 1}
    categories: [{name: Thermostat}]
