name: thermostats-wave12-moes-sh4
components:
  - id: main
    capabilities:
      - {id: thermostatHeatingSetpoint, version: 1}
      - {id: temperatureMeasurement, version: 1}
      - {id: battery, version: 1}
      - {id: concertmirror08464.moesShFourChildLock, version: 1}
      - {id: concertmirror08464.moesShFourWindowDetection, version: 1}
      - {id: concertmirror08464.moesShFourBoostHeating, version: 1}
      - {id: concertmirror08464.moesShFourBoostCountdown, version: 1}
      - {id: concertmirror08464.moesShFourAutoOverride, version: 1}
      - {id: concertmirror08464.moesShFourTempCalibration, version: 1}
      - {id: concertmirror08464.moesShFourPreset, version: 1}
      - {id: concertmirror08464.moesShFourComfortTemperature, version: 1}
      - {id: concertmirror08464.moesShFourEcoTemperature, version: 1}
      - {id: concertmirror08464.moesShFourWindowTemperature, version: 1}
      - {id: concertmirror08464.moesShFourWindowTime, version: 1}
      - {id: concertmirror08464.moesShFourOnline, version: 1}
      - {id: concertmirror08464.moesShFourErrorStatus, version: 1}
      - {id: refresh, version: 1}
    categories: [{name: Thermostat}]
