name: thermostats-thermostat-trv06
components:
  - id: main
    capabilities:
      - id: thermostatMode
        version: 1
      - id: thermostatHeatingSetpoint
        version: 1
      - id: thermostatOperatingState
        version: 1
      - id: temperatureMeasurement
        version: 1
      - id: concertmirror08464.trv06ChildLock
        version: 1
      - id: concertmirror08464.trv06FrostProtection
        version: 1
      - id: concertmirror08464.trv06ScaleProtection
        version: 1
      - id: concertmirror08464.trv06TempCalibration
        version: 1
      - id: concertmirror08464.trv06PiHeatingDemand
        version: 1
      - id: concertmirror08464.trv06BatteryLow
        version: 1
      - id: concertmirror08464.trv06Error
        version: 1
      - id: refresh
        version: 1
    categories:
      - name: Thermostat
deviceConfig:
  dashboard:
    states:
      - component: main
        capability: thermostatHeatingSetpoint
        version: 1
        group: main
    actions: []
    basicPlus: []
  detailView:
    - component: main
      capability: thermostatMode
      version: 1
    - component: main
      capability: thermostatHeatingSetpoint
      version: 1
    - component: main
      capability: thermostatOperatingState
      version: 1
    - component: main
      capability: temperatureMeasurement
      version: 1
    - component: main
      capability: concertmirror08464.trv06ChildLock
      version: 1
    - component: main
      capability: concertmirror08464.trv06FrostProtection
      version: 1
    - component: main
      capability: concertmirror08464.trv06ScaleProtection
      version: 1
    - component: main
      capability: concertmirror08464.trv06TempCalibration
      version: 1
    - component: main
      capability: concertmirror08464.trv06PiHeatingDemand
      version: 1
    - component: main
      capability: concertmirror08464.trv06BatteryLow
      version: 1
    - component: main
      capability: concertmirror08464.trv06Error
      version: 1
    - component: main
      capability: refresh
      version: 1
  automation:
    conditions:
      - component: main
        capability: thermostatMode
        version: 1
      - component: main
        capability: thermostatHeatingSetpoint
        version: 1
      - component: main
        capability: thermostatOperatingState
        version: 1
      - component: main
        capability: temperatureMeasurement
        version: 1
      - component: main
        capability: concertmirror08464.trv06ChildLock
        version: 1
      - component: main
        capability: concertmirror08464.trv06FrostProtection
        version: 1
      - component: main
        capability: concertmirror08464.trv06ScaleProtection
        version: 1
      - component: main
        capability: concertmirror08464.trv06TempCalibration
        version: 1
      - component: main
        capability: concertmirror08464.trv06PiHeatingDemand
        version: 1
      - component: main
        capability: concertmirror08464.trv06BatteryLow
        version: 1
      - component: main
        capability: concertmirror08464.trv06Error
        version: 1
    actions:
      - component: main
        capability: thermostatMode
        version: 1
      - component: main
        capability: thermostatHeatingSetpoint
        version: 1
      - component: main
        capability: concertmirror08464.trv06ChildLock
        version: 1
      - component: main
        capability: concertmirror08464.trv06FrostProtection
        version: 1
      - component: main
        capability: concertmirror08464.trv06ScaleProtection
        version: 1
      - component: main
        capability: concertmirror08464.trv06TempCalibration
        version: 1
