name: thermostats-thermostat-zht002
components:
  - id: main
    capabilities:
      - id: thermostatMode
        version: 1
      - id: thermostatHeatingSetpoint
        version: 1
      - id: temperatureMeasurement
        version: 1
      - id: concertmirror08464.zht002ProgrammingMode
        version: 1
      - id: concertmirror08464.zht002WorkingDay
        version: 1
      - id: concertmirror08464.zht002Sensor
        version: 1
      - id: concertmirror08464.zht002ValveState
        version: 1
      - id: concertmirror08464.zht002ChildLock
        version: 1
      - id: concertmirror08464.zht002EcoMode
        version: 1
      - id: concertmirror08464.zht002MinTemperature
        version: 1
      - id: concertmirror08464.zht002MaxTemperature
        version: 1
      - id: concertmirror08464.maxTempLimitZhtCToSeventy
        version: 1
      - id: concertmirror08464.zht002TempCalibration
        version: 1
      - id: concertmirror08464.zht002DeadzoneTemperature
        version: 1
      - id: refresh
        version: 1
    categories:
      - name: Thermostat
deviceConfig:
  dashboard:
    states:
      - component: main
        capability: thermostatHeatingSetpoint
        version: 1
        group: main
    actions: []
    basicPlus: []
  detailView:
    - component: main
      capability: thermostatMode
      version: 1
    - component: main
      capability: thermostatHeatingSetpoint
      version: 1
    - component: main
      capability: temperatureMeasurement
      version: 1
    - component: main
      capability: concertmirror08464.zht002ProgrammingMode
      version: 1
    - component: main
      capability: concertmirror08464.zht002WorkingDay
      version: 1
    - component: main
      capability: concertmirror08464.zht002Sensor
      version: 1
    - component: main
      capability: concertmirror08464.zht002ValveState
      version: 1
    - component: main
      capability: concertmirror08464.zht002ChildLock
      version: 1
    - component: main
      capability: concertmirror08464.zht002EcoMode
      version: 1
    - component: main
      capability: concertmirror08464.zht002MinTemperature
      version: 1
    - component: main
      capability: concertmirror08464.zht002MaxTemperature
      version: 1
    - component: main
      capability: concertmirror08464.maxTempLimitZhtCToSeventy
      version: 1
    - component: main
      capability: concertmirror08464.zht002TempCalibration
      version: 1
    - component: main
      capability: concertmirror08464.zht002DeadzoneTemperature
      version: 1
    - component: main
      capability: refresh
      version: 1
  automation:
    conditions:
      - component: main
        capability: thermostatMode
        version: 1
      - component: main
        capability: thermostatHeatingSetpoint
        version: 1
      - component: main
        capability: temperatureMeasurement
        version: 1
      - component: main
        capability: concertmirror08464.zht002ProgrammingMode
        version: 1
      - component: main
        capability: concertmirror08464.zht002WorkingDay
        version: 1
      - component: main
        capability: concertmirror08464.zht002Sensor
        version: 1
      - component: main
        capability: concertmirror08464.zht002ValveState
        version: 1
      - component: main
        capability: concertmirror08464.zht002ChildLock
        version: 1
      - component: main
        capability: concertmirror08464.zht002EcoMode
        version: 1
      - component: main
        capability: concertmirror08464.zht002MinTemperature
        version: 1
      - component: main
        capability: concertmirror08464.zht002MaxTemperature
        version: 1
      - component: main
        capability: concertmirror08464.maxTempLimitZhtCToSeventy
        version: 1
      - component: main
        capability: concertmirror08464.zht002TempCalibration
        version: 1
      - component: main
        capability: concertmirror08464.zht002DeadzoneTemperature
        version: 1
    actions:
      - component: main
        capability: thermostatMode
        version: 1
      - component: main
        capability: thermostatHeatingSetpoint
        version: 1
      - component: main
        capability: concertmirror08464.zht002ProgrammingMode
        version: 1
      - component: main
        capability: concertmirror08464.zht002WorkingDay
        version: 1
      - component: main
        capability: concertmirror08464.zht002Sensor
        version: 1
      - component: main
        capability: concertmirror08464.zht002ChildLock
        version: 1
      - component: main
        capability: concertmirror08464.zht002EcoMode
        version: 1
      - component: main
        capability: concertmirror08464.zht002MinTemperature
        version: 1
      - component: main
        capability: concertmirror08464.zht002MaxTemperature
        version: 1
      - component: main
        capability: concertmirror08464.maxTempLimitZhtCToSeventy
        version: 1
      - component: main
        capability: concertmirror08464.zht002TempCalibration
        version: 1
      - component: main
        capability: concertmirror08464.zht002DeadzoneTemperature
        version: 1
