-- Generated by source/tools/build_dist.py. Source catalog remains in source/src/core.
local custom_capabilities = {}
local function range(value)
if type(value) ~= "table" then return nil end
return { minimum = value[1], maximum = value[2], step = value[3], unit = value[4], allowed_values = value[5] }
end
local function numeric(row)
return { kind = "numeric", emit_name = row[1], range_key = row[2], capability_id = row[3], attribute_name = row[4], range_attribute_name = row[5], command_name = row[6], argument_name = row[7], mapping_name = row[8], label = row[9], default_range = range(row[10]), event_minimum = row[11], event_maximum = row[12], event_unit = row[13] }
end
local function enum(row)
return { kind = "enum", emit_name = row[1], range_key = row[2], capability_id = row[3], attribute_name = row[4], supported_attribute_name = row[5], command_name = row[6], argument_name = row[7], mapping_name = row[8], label = row[9], supported_values = row[10], default_range = { allowed_values = row[10] } }
end
local function text(row)
return { kind = "text", emit_name = row[1], capability_id = row[2], attribute_name = row[3], command_name = row[4], argument_name = row[5], mapping_name = row[6], label = row[7], maximum_length = row[8] }
end
local function build(rows, factory)
local out = {}
for _, row in ipairs(rows) do out[#out + 1] = factory(row) end
return out
end
custom_capabilities.numeric = build({ { "zmsFourBacklightBrightness", nil, "concertmirror08464.zmsFourBacklightBrightness", "backlightBrightness", nil, "setBacklightBrightness", "backlightBrightness", "zms206_backlight_brightness", "Zms Four Backlight Brightness", { 0, 100, 1, "%", nil }, nil, nil, "%" }, { "zmsFourCountdown", nil, "concertmirror08464.zmsFourCountdown", "countdown", nil, "setCountdown", "countdown", "zms206_countdown", "Zms Four Countdown", { 0, 43200, 1, "s", nil }, nil, nil, "s" } }, numeric)
custom_capabilities.enum = build({ { "zmsFourBacklightMode", nil, "concertmirror08464.zmsFourBacklightMode", "backlightMode", nil, "setBacklightMode", "backlightMode", "zms206_backlight_mode", "Zms Four Backlight Mode", { "off", "on" } }, { "zmsFourChildLock", nil, "concertmirror08464.zmsFourChildLock", "childLock", nil, "setChildLock", "childLock", "zms206_child_lock", "Zms Four Child Lock", { "off", "on" } }, { "zmsFourRadarConfig", nil, "concertmirror08464.zmsFourRadarConfig", "radarConfig", nil, "setRadarConfig", "radarConfig", "zms206_radar_config", "Zms Four Radar Config", { "none", "10s", "20s", "30s", "45s", "60s" } }, { "zmsFourSwitchColorOn", nil, "concertmirror08464.zmsFourSwitchColorOn", "switchColorOn", nil, "setSwitchColorOn", "switchColorOn", "zms206_switch_color_on", "Zms Four Switch Color On", { "red", "blue", "green", "white", "yellow", "magenta", "cyan", "warm_white", "warm_yellow" } }, { "zmsFourSwitchColorOff", nil, "concertmirror08464.zmsFourSwitchColorOff", "switchColorOff", nil, "setSwitchColorOff", "switchColorOff", "zms206_switch_color_off", "Zms Four Switch Color Off", { "red", "blue", "green", "white", "yellow", "magenta", "cyan", "warm_white", "warm_yellow" } }, { "zmsFourIndicatorStatus", nil, "concertmirror08464.zmsFourIndicatorStatus", "indicatorStatus", nil, "setIndicatorStatus", "indicatorStatus", "zms206_indicator_status", "Zms Four Indicator Status", { "off", "on_off_status", "switch_position" } }, { "zmsFourDelayOffColor", nil, "concertmirror08464.zmsFourDelayOffColor", "delayOffColor", nil, "setDelayOffColor", "delayOffColor", "zms206_delay_off_color", "Zms Four Delay Off Color", { "red", "blue", "green", "white", "yellow", "magenta", "cyan", "warm_white", "warm_yellow" } }, { "zmsFourRelayStatus", nil, "concertmirror08464.zmsFourRelayStatus", "relayStatus", nil, "setRelayStatus", "relayStatus", "zms206_relay_status", "Zms Four Relay Status", { "power_on", "power_off", "restart_memory" } } }, enum)
custom_capabilities.text = build({ { "last_power_response_time", "concertmirror08464.lastPowerResponseTime", "lastPowerResponseTime", nil, nil, nil, "Last power response time", 64 }, { "zmsFourSwitchName", "concertmirror08464.zmsFourSwitchName", "switchName", "setSwitchName", "switchName", "zms206_switch_name", "Zms Four Switch Name", 12 } }, text)
custom_capabilities.driver_message = { ["attribute_name"] = "driverMessage", ["capability_id"] = "concertmirror08464.driverMessage", ["emit_name"] = "driver_message", ["label"] = "Driver message", ["maximum_length"] = 512 }
custom_capabilities.by_range_key = {}
custom_capabilities.by_emit_name = {}
custom_capabilities.by_capability_id = {}
local function index_metadata(definitions)
for _, metadata in ipairs(definitions) do
custom_capabilities.by_emit_name[metadata.emit_name] = metadata
if type(metadata.capability_id) == "string" and metadata.capability_id ~= "" then custom_capabilities.by_capability_id[metadata.capability_id] = metadata end
if type(metadata.range_key) == "string" and metadata.range_key ~= "" then custom_capabilities.by_range_key[metadata.range_key] = metadata end
end
end
index_metadata(custom_capabilities.numeric)
index_metadata(custom_capabilities.enum)
index_metadata(custom_capabilities.text)
custom_capabilities.by_emit_name[custom_capabilities.driver_message.emit_name] = custom_capabilities.driver_message
custom_capabilities.by_capability_id[custom_capabilities.driver_message.capability_id] = custom_capabilities.driver_message
local function clone_allowed_values(allowed_values)
if type(allowed_values) ~= "table" then return nil end
local copied = {}
for index, value in ipairs(allowed_values) do copied[index] = value end
return copied
end
function custom_capabilities.resolve_range(definition, metadata)
if type(metadata) ~= "table" then return nil end
local default_range = type(metadata.default_range) == "table" and metadata.default_range or nil
local ranges = type(definition) == "table" and definition.presence_capability_ranges or nil
local resolved = type(ranges) == "table" and ranges[metadata.range_key] or nil
if type(resolved) ~= "table" then resolved = default_range end
if type(resolved) ~= "table" then return nil end
return {
minimum = type(resolved.minimum) == "number" and resolved.minimum or (default_range and default_range.minimum or nil),
maximum = type(resolved.maximum) == "number" and resolved.maximum or (default_range and default_range.maximum or nil),
step = type(resolved.step) == "number" and resolved.step or (default_range and default_range.step or nil),
unit = type(resolved.unit) == "string" and resolved.unit or (default_range and default_range.unit or nil),
allowed_values = type(resolved.allowed_values) == "table" and clone_allowed_values(resolved.allowed_values) or clone_allowed_values(default_range and default_range.allowed_values or nil),
}
end
return custom_capabilities
