name: valves-valve-2-battery-timer-gx03
components:
  - id: main
    capabilities:
      - id: valve
        version: 1
      - id: concertmirror08464.gx03Timer
        version: 1
      - id: concertmirror08464.gx03ValveState
        version: 1
      - id: concertmirror08464.gx03LastDuration
        version: 1
      - id: battery
        version: 1
      - id: refresh
        version: 1
    categories:
      - name: WaterValve
  - id: valve2
    capabilities:
      - id: valve
        version: 1
      - id: concertmirror08464.gx03Timer
        version: 1
      - id: concertmirror08464.gx03ValveState
        version: 1
      - id: concertmirror08464.gx03LastDuration
        version: 1
    categories:
      - name: WaterValve
