name: switches-switch-1-countdown-indicator
components:
  - id: main
    capabilities:
      - {id: switch, version: 1}
      - {id: concertmirror08464.countdownTimerZclTwelveHours, version: 1}
      - {id: concertmirror08464.indicatorMode, version: 1}
      - {id: refresh, version: 1}
    categories:
      - name: Switch
