name: switches-switch-1-countdown-switch-type
components:
  - id: main
    capabilities:
      - id: switch
        version: 1
      - id: concertmirror08464.switchType
        version: 1
      - id: concertmirror08464.countdownTimerZclTwelveHours
        version: 1
      - id: refresh
        version: 1
    categories:
      - name: Switch
