name: thermostats-fcu-thermostat-l2-t-f-mf
components:
  - id: main
    capabilities:
      - id: thermostatMode
        version: 1
      - id: thermostatHeatingSetpoint
        version: 1
      - id: temperatureMeasurement
        version: 1
      - id: fanMode
        version: 1
      - id: concertmirror08464.screenBrightnessL2TFMfLevel9
        version: 1
      - id: refresh
        version: 1
    categories:
      - name: Thermostat
