name: thermostats-thermostat-battery-ar331pro
components:
  - id: main
    capabilities:
      - id: thermostatMode
        version: 1
      - id: thermostatHeatingSetpoint
        version: 1
      - id: thermostatOperatingState
        version: 1
      - id: temperatureMeasurement
        version: 1
      - id: battery
        version: 1
      - id: concertmirror08464.thermostatPresetAr331proSixMode
        version: 1
      - id: concertmirror08464.childLock
        version: 1
      - id: refresh
        version: 1
    categories:
      - name: Thermostat
deviceConfig:
  dashboard:
    states:
      - component: main
        capability: temperatureMeasurement
        version: 1
        group: main
        values:
          - label: "{{temperature.value}}{{temperature.unit}}"
      - component: main
        capability: thermostatOperatingState
        version: 1
    actions: []
    basicPlus: []
  detailView:
    - component: main
      capability: temperatureMeasurement
      version: 1
    - component: main
      capability: thermostatMode
      version: 1
    - component: main
      capability: thermostatHeatingSetpoint
      version: 1
    - component: main
      capability: thermostatOperatingState
      version: 1
    - component: main
      capability: concertmirror08464.thermostatPresetAr331proSixMode
      version: 1
    - component: main
      capability: concertmirror08464.childLock
      version: 1
    - component: main
      capability: battery
      version: 1
    - component: main
      capability: refresh
      version: 1
  automation:
    conditions:
      - component: main
        capability: temperatureMeasurement
        version: 1
      - component: main
        capability: thermostatMode
        version: 1
      - component: main
        capability: thermostatHeatingSetpoint
        version: 1
      - component: main
        capability: thermostatOperatingState
        version: 1
      - component: main
        capability: concertmirror08464.thermostatPresetAr331proSixMode
        version: 1
      - component: main
        capability: concertmirror08464.childLock
        version: 1
      - component: main
        capability: battery
        version: 1
    actions:
      - component: main
        capability: thermostatMode
        version: 1
      - component: main
        capability: thermostatHeatingSetpoint
        version: 1
      - component: main
        capability: concertmirror08464.thermostatPresetAr331proSixMode
        version: 1
      - component: main
        capability: concertmirror08464.childLock
        version: 1
