zigbeeManufacturer:
  - id: "fp_4e1dbf2713"
    manufacturer: "_TZ3210_5rta89nj"
    model: "TS0601"
    deviceProfileName: "covers-wave10-moes-zc-lp01"
  - id: "fp_f0dac9ca3b"
    manufacturer: "_TZ3210_rundhkxp"
    model: "TS030F"
    deviceProfileName: "covers-wave10-moes-adcbzi01"
  - id: "fp_66fff3c994"
    manufacturer: "_TZ3210_sxtfesc6"
    model: "TS030F"
    deviceProfileName: "covers-wave10-moes-adcbzi01"
  - id: "fp_e8b390462e"
    manufacturer: "_TZE200_ra6wrlgv"
    model: "TS0601"
    deviceProfileName: "covers-wave15-box-erc2206z"
  - id: "fp_71854b289a"
    manufacturer: "_TZE200_sbordckq"
    model: "TS0601"
    deviceProfileName: "covers-wave19-legacy-tuya"
  - id: "fp_7b620c7d71"
    manufacturer: "_TZE200_swhwv3k3"
    model: "TS0601"
    deviceProfileName: "covers-wave19-legacy-tuya"
  - id: "fp_eb10fe66f7"
    manufacturer: "_TZE200_xtrnjaoz"
    model: "TS0601"
    deviceProfileName: "covers-cover-gm25teq"
  - id: "fp_4eeecb3d73"
    manufacturer: "_TZE204_7lb6j8wg"
    model: "TS0601"
    deviceProfileName: "covers-wave15-tuya-semicom-three"
  - id: "fp_a7a090a8c6"
    manufacturer: "_TZE204_mpg22jc1"
    model: "TS0601"
    deviceProfileName: "covers-wave10-zemismart-zn-usc1u-ht"
  - id: "fp_1b44253e37"
    manufacturer: "_TZE204_srmahpwl"
    model: "TS0601"
    deviceProfileName: "covers-wave10-moes-zs-sr-euc"
  - id: "fp_da4c44c5df"
    manufacturer: "_TZE204_xtrnjaoz"
    model: "TS0601"
    deviceProfileName: "covers-cover-gm25teq"
  - id: "fp_d68ddd69ac"
    manufacturer: "_TZE210_xgzzuerd"
    model: "TS0301"
    deviceProfileName: "covers-wave10-tuya-ts0301-cover-two"
  - id: "fp_e6d5d079f5"
    manufacturer: "_TZE284_6hrnp30w"
    model: "TS0601"
    deviceProfileName: "covers-wave10-zemismart-zmp1"
  - id: "fp_7b59b0ddfe"
    manufacturer: "_TZE284_7qc2wlqr"
    model: "TS0601"
    deviceProfileName: "covers-wave10-manhot-bl82-tyz1"
  - id: "fp_5c49374973"
    manufacturer: "_TZE284_8whfphjv"
    model: "TS0601"
    deviceProfileName: "covers-cover-gm25teq"
  - id: "fp_188c9168b3"
    manufacturer: "_TZE284_hbjwgkdh"
    model: "TS0601"
    deviceProfileName: "covers-wave10-xenon-x7726"
  - id: "fp_3d09e458c2"
    manufacturer: "_TZE284_qoi1aqxg"
    model: "TS0601"
    deviceProfileName: "covers-wave10-moes-fwjzceh18a001"
  - id: "fp_b4d6e2c53d"
    manufacturer: "_TZE284_upt8lzi0"
    model: "TS0601"
    deviceProfileName: "covers-cover-moes-zs-sf-euc-wh-ms"
