name: switches-screen-zms208us2
components:
  - id: main
    label: ZMS-208US-2
    capabilities:
      - id: switch
        version: 1
      - id: concertmirror08464.zms208TwoChildLock
        version: 1
      - id: refresh
        version: 1
    categories:
      - name: Switch
  - id: switch1
    label: Switch 1
    capabilities:
      - id: switch
        version: 1
      - id: concertmirror08464.zms208TwoSwitchName
        version: 1
      - id: concertmirror08464.zms208TwoCountdown
        version: 1
    categories:
      - name: Switch
  - id: switch2
    label: Switch 2
    capabilities:
      - id: switch
        version: 1
      - id: concertmirror08464.zms208TwoSwitchName
        version: 1
      - id: concertmirror08464.zms208TwoCountdown
        version: 1
    categories:
      - name: Switch
metadata:
  deviceType: Switch
  ocfDeviceType: oic.d.switch
