name: safety-presence-zy-hps01-illuminance
components:
  - id: main
    capabilities:
      - id: occupancySensor
        version: 1
      - id: concertmirror08464.zyhps01MoveSensitivity
        version: 1
      - id: concertmirror08464.zyhps01BreathSensitivity
        version: 1
      - id: concertmirror08464.zyhps01MoveMaximumRange
        version: 1
      - id: concertmirror08464.zyhps01MoveMinimumRange
        version: 1
      - id: concertmirror08464.zyhps01BreathMaximumRange
        version: 1
      - id: concertmirror08464.zyhps01BreathMinimumRange
        version: 1
      - id: concertmirror08464.zyhps01PresenceTimeout
        version: 1
      - id: concertmirror08464.driverMessage
        version: 1
      - id: illuminanceMeasurement
        version: 1
      - id: firmwareUpdate
        version: 1
      - id: refresh
        version: 1
    categories:
      - name: PresenceSensor
deviceConfig:
  dashboard:
    states:
      - component: main
        capability: occupancySensor
        version: 1
        group: main
    actions: []
    basicPlus: []
  detailView:
    - component: main
      capability: occupancySensor
      version: 1
    - component: main
      capability: concertmirror08464.zyhps01MoveSensitivity
      version: 1
    - component: main
      capability: concertmirror08464.zyhps01BreathSensitivity
      version: 1
    - component: main
      capability: concertmirror08464.zyhps01MoveMaximumRange
      version: 1
    - component: main
      capability: concertmirror08464.zyhps01MoveMinimumRange
      version: 1
    - component: main
      capability: concertmirror08464.zyhps01BreathMaximumRange
      version: 1
    - component: main
      capability: concertmirror08464.zyhps01BreathMinimumRange
      version: 1
    - component: main
      capability: concertmirror08464.zyhps01PresenceTimeout
      version: 1
    - component: main
      capability: concertmirror08464.driverMessage
      version: 1
    - component: main
      capability: illuminanceMeasurement
      version: 1
    - component: main
      capability: refresh
      version: 1
  automation:
    conditions:
      - component: main
        capability: occupancySensor
        version: 1
      - component: main
        capability: illuminanceMeasurement
        version: 1
    actions:
      - component: main
        capability: concertmirror08464.zyhps01MoveSensitivity
        version: 1
      - component: main
        capability: concertmirror08464.zyhps01BreathSensitivity
        version: 1
      - component: main
        capability: concertmirror08464.zyhps01MoveMaximumRange
        version: 1
      - component: main
        capability: concertmirror08464.zyhps01MoveMinimumRange
        version: 1
      - component: main
        capability: concertmirror08464.zyhps01BreathMaximumRange
        version: 1
      - component: main
        capability: concertmirror08464.zyhps01BreathMinimumRange
        version: 1
      - component: main
        capability: concertmirror08464.zyhps01PresenceTimeout
        version: 1
