-- Generated from analysis/custom_capability_family_matrix.json.
-- Fixed family custom capabilities intentionally do not define dynamic Range attributes.

local CAPABILITY_NAMESPACE = "concertmirror08464."
local function capitalize(value) return value:sub(1, 1):upper() .. value:sub(2) end
local DIGIT_WORDS = {
  ["0"] = "Zero",
  ["1"] = "One",
  ["2"] = "Two",
  ["3"] = "Three",
  ["4"] = "Four",
  ["5"] = "Five",
  ["6"] = "Six",
  ["7"] = "Seven",
  ["8"] = "Eight",
  ["9"] = "Nine",
}
local ATTRIBUTE_OVERRIDES = {
  acFrequency2ct = "acFrequencyTwoCt",
  acFrequencyPc311 = "acFrequencyPcThreeEleven",
  acFrequencySdm01 = "acFrequencySdmOne",
  clearFaultDin2 = "clearFaultDinTwo",
  clearFaultDin3 = "clearFaultDinThree",
  currentThresholdRcbo63a = "currentThreshRcboSixtyThreeA",
  currentThresholdToqcb2A63 = "currentThreshToqcbTwoAThree",
  humidityCalibrationZg204zx = "humidityCalZgTwoFour",
  antiInterferenceZg204zx = "antiInterferenceZgTwoFour",
  indicatorZg204zx = "indicatorZgTwoFour",
  illuminanceIntervalZg204zx = "illumIntervalZgTwoFour",
  leakageThresholdProtector100ma = "leakageThreshProtHundredMa",
  minBrightnessTs0601 = "minBrightTsZeroSixZeroOne",
  maxBrightnessTs0601 = "maxBrightTsZeroSixZeroOne",
  motionDetectionSensitivityZg204zx = "motionSensZgTwoFour",
  powerFactor2ctPercent = "powerFactorTwoCtPercent",
  powerFactorPc311Percent = "powerFactorPcThreeElevenPercent",
  powerFactorSdm01Percent = "powerFactorSdmOnePercent",
  presenceDetectionRangeZg204zx = "presenceRangeZgTwoFour",
  presenceDetectionRangeZym100l = "presenceRangeZymHundredL",
  presenceSensitivityZym100l = "presenceSensZymHundredL",
  presenceTargetDistanceZym100l = "presenceTargetZymHundredL",
  reactivePowerAtms10013z3 = "reactivePowerAtmsZ",
  reactivePowerDin1 = "reactivePowerDinOne",
  staticDetectionSensitivityZg204zx = "staticSensZgTwoFour",
  temperatureCalibrationZg204zx = "tempCalZgTwoFour",
  temperatureUnitZg204zx = "tempUnitZgTwoFour",
  updateFrequency2ctSeconds60 = "updateFreqTwoCtSixtySec",
  updateFrequencyPj1203aSeconds60 = "updateFreqPjTwelveSixtySec",
  updateFrequencySdm02v1Seconds3600 = "updateFreqSdmHour",
  temperatureCalibrationZg227z = "capsksodykzsbecifgevpsl",
  tempCalibrationSoilWarnC2 = "caprvctgpgoubsacohqfcrq",
  temperatureCalibrationZsSf00 = "capzmbvtirjrrmcdwraeljk",
  humidityCalibrationZs301z = "capecdchfnprpgfnjbpimxt",
  humidityCalibrationSoilWarning30 = "capllnskkvcohtuzxhesiem",
  illuminanceCalibrationZs300z = "capazxdmcoktbdrxpnkvhjg",
  illuminanceCalibrationZsSf00 = "capvkwmdygsbyidigodegra",
  tempSensitivityThCToOne = "capftbtllusxgdcurvagawp",
  humiditySensitivityThThreeTen = "capwpgporfdddkgukpmerzi",
  humiditySensitivitySoilOneFive = "capegmpdrnhojlbjgavjhpb",
  updateFrequencyContactS8Minutes = "capttgosbypqdikduohtdty",
  tempDeltaBotRToTen = "capgqurzzieraunpalthkof",
  tempDeltaTgmCToTen = "capmxioiznwtyipfnfgvqta",
  tempDeltaXhCToNinetyFive = "capjwjngwlnvzrlskixhstp",
  maxTempLimitTybacCToThirty = "capqrfwpywdvjzmovhdtays",
  maxTempLimitZhtCToSeventy = "captpspguaydpwcwsllmxjd",
  minTempLimitTybacCToThirty = "capqheplozwascjxlchygob",
  displayBrightnessPro900zLevel8 = "capzrlgutkngagaxybskmfh",
  displayBrightnessPressureLevel8 = "displayBrightnessPressureEight",
  alarmDurationSirenZa03Seconds = "capoxxgfdnqcgmalgvopqkp",
  alarmDurationContactS8Sec300 = "capmajqiedkymyekcrjnmlq",
  vibrationSensitivityZgFifty = "capivrsyvmblqszklvkqzek",
  vibrationSensitivity4cqhd2haLevel = "capsvlhotqzqpwjpjpwgruu",
  txPowerSenoroWinLevel = "capqhhcecqeiqdmxrfyxouq",
  illuminanceSamplingZg223zMinutes = "capeaiclppvxczqelbqqzmu",
  soilFertilityWarningZsSf = "capjudipkgogczuddzwjoso",
  garageRunTimeCountdownOpener120 = "capmjohqwokmotdvrfcfvaf",
  manualModeHhstAutoManualTemp = "capvkzueasiklxvfytdgcrp",
  motorDirectionZm79eDtLeftRight = "caprayirlspeprfrwwysgxh",
  motorDirectionBxTyzNormalRev = "capnfcnnbmfkahvrbckxcij",
  motorDirectionMbNormalRev = "capultkjbczgdpnaciiuoqx",
  coverWorkPimsActual = "capcpcfsvmnkqqvbyfklqpl",
  coverWorkRmOpeningClosing = "capmtldrdyfbzxvbdlnhcgl",
  coverCalibrationPims3028StartEnd = "capvonpjrddxpdpephlodgy",
  thermostatPresetAr331proSixMode = "capnfdjacfllfzxkmgyzkot",
  thermostatPresetZwt07Program = "capdvrszjverdyaeiqbvgbj",
  tempSensorSelectTervixInOut = "capnmcdorbfaidtbpctvlfz",
  temperatureSensorSelectX5hThree = "capsgauxdjohqtflrikhdrj",
  sensitivitySmoke288wzEnum = "captrsqgnoflamhbuavbcxl",
  vibrationSensitivityZg103zEnum = "capxngbvkpdnnivabdvdqnt",
  tempSensitivitySoilC03To1 = "tempSensSoilCToOne",
}

local function attribute_name(capability_id)
  if ATTRIBUTE_OVERRIDES[capability_id] ~= nil then
    return ATTRIBUTE_OVERRIDES[capability_id]
  end

  return (capability_id:gsub("%d", DIGIT_WORDS))
end

local function titleize(value)
  local label = value:gsub("(%l)(%u)", "%1 %2"):gsub("2ct", "2CT"):gsub("Ph", "pH"):gsub("Orp", "ORP"):gsub("Tds", "TDS")
  return label:sub(1, 1):upper() .. label:sub(2)
end
local function command_name(attr, writable) return writable and ("set" .. capitalize(attr)) or nil end
local function base_metadata(row, kind)
  local capability_id, writable, mapping_name = row[1], row[2], row[3]
  local attr = attribute_name(capability_id)
  return { emit_name = capability_id, capability_id = CAPABILITY_NAMESPACE .. capability_id, attribute_name = attr, command_name = command_name(attr, writable), argument_name = writable and attr or nil, mapping_name = mapping_name, label = titleize(capability_id), kind = kind }
end
local function numeric(row)
  local metadata = base_metadata(row, "numeric")
  metadata.default_range = { minimum = row[4], maximum = row[5], step = row[6], unit = row[7] }
  metadata.event_unit = row[7]
  return metadata
end
local function enum(row)
  local metadata = base_metadata(row, "enum")
  metadata.supported_values = row[4]
  metadata.default_range = { allowed_values = row[4] }
  return metadata
end
local function text(row)
  local metadata = base_metadata(row, "text")
  metadata.maximum_length = row[4]
  return metadata
end
local function build(rows, factory)
  local definitions = {}
  for _, row in ipairs(rows) do definitions[#definitions + 1] = factory(row) end
  return definitions
end
local numeric_rows = {
    {"batteryVoltage",false,"battery_voltage",0,10,0.001,"V"},
    {"temperatureProbeExcellux",false,"temperature_probe",-40,125,0.1,"C"},
    {"temperatureProbe2aaa",false,"temperature_probe",-40,125,0.1,"C"},
    {"sensitivityContactS8",true,"sensitivity",1,10,1,nil},
    {"temperatureCalibrationZg227z",true,"temperature_calibration",-2,2,0.1,"C"},
    {"temperatureCalibrationZg204zx",true,"temperature_calibration",-10,10,0.1,"C"},
    {"temperatureCalibrationSoilWarning",true,"temperature_calibration",-10,10,0.1,"C"},
    {"tempCalibrationSoilWarnC2",true,"temperature_calibration",-2,2,0.1,"C"},
    {"temperatureCalibrationSoilFertility",true,"temperature_calibration",-10,10,0.1,"C"},
    {"temperatureCalibrationZsSf00",true,"temperature_calibration",-2,2,0.1,"C"},
    {"humidityCalibrationZg227z",true,"humidity_calibration",-30,30,1,"%"},
    {"humidityCalibrationZg204zx",true,"humidity_calibration",-50,50,1,"%"},
    {"humidityCalibrationSoilAirIllum",true,"humidity_calibration",-50,50,1,"%"},
    {"humidityCalibrationZs301z",true,"humidity_calibration",-30,30,1,"%"},
    {"humidityCalibrationSoilWarning",true,"humidity_calibration",-50,50,1,"%"},
    {"humidityCalibrationSoilWarning30",true,"humidity_calibration",-30,30,1,"%"},
    {"illuminanceCalibrationSoilIllumWarning",true,"illuminance_calibration",-10000,10000,1,"lux"},
    {"illuminanceCalibrationZs300z",true,"illuminance_calibration",-1000,1000,1,"lux"},
    {"illuminanceCalibrationSoilFertility",true,"illuminance_calibration",-10000,10000,1,"lux"},
    {"illuminanceCalibrationZsSf00",true,"illuminance_calibration",-15,1000,1,"lux"},
    {"temperatureSensitivityTh",true,"temperature_sensitivity",0,10,0.1,"C"},
    {"temperatureSensitivityThAlarm",true,"temperature_sensitivity",0,10,0.1,"C"},
    {"tempSensitivityThCToOne",true,"temperature_sensitivity",0.3,1,0.1,"C"},
    {"temperatureSensitivitySoilAlarm",true,"temperature_sensitivity",0,10,0.1,"C"},
    {"tempSensitivitySoilC03To1",true,"temperature_sensitivity",0.3,1,0.1,"C"},
    {"humiditySensitivityThAlarm",true,"humidity_sensitivity",0,100,1,"%"},
    {"humiditySensitivityThThreeTen",true,"humidity_sensitivity",3,10,1,"%"},
    {"humiditySensitivitySoilAlarm",true,"humidity_sensitivity",0,100,1,"%"},
    {"humiditySensitivitySoilOneFive",true,"humidity_sensitivity",1,5,1,"%"},
    {"motionDetectionSensitivityZg204zx",true,"motion_detection_sensitivity",0,10,1,nil},
    {"staticDetectionSensitivityZg204zx",true,"static_detection_sensitivity",0,10,1,nil},
    {"presenceDetectionRangeZg204zx",true,"detection_distance",0,5,0.01,"m"},
    {"presenceFadingTimeZg204zx",true,"fading_time",0,28800,1,"s"},
    {"presenceSensitivityGnpflcoq",true,"sensitivity",0,10,1,nil},
    {"presenceFadingTimeGnpflcoq",true,"fading_time",0,1000,1,"s"},
    {"illuminanceIntervalZg204zx",true,"illuminance_interval",1,720,1,"min"},
    {"presenceSensitivityZym100l",true,"presence_sensitivity",0,9,1,nil},
    {"minimumRangeZym100l",true,"minimum_range",0,9.5,0.15,"m"},
    {"presenceDetectionRangeZym100l",true,"presence_detection_range",0,9.5,0.15,"m"},
    {"detectionDelayZym100l",true,"detection_delay",0,10,0.1,"s"},
    {"presenceFadingTimeZym100l",true,"presence_fading_time",0,1500,1,"s"},
    {"presenceTargetDistanceZym100l",false,"presence_target_distance",0,9.5,0.01,"m"},
    {"producedEnergyDin",false,"produced_energy",0,999999,0.001,"kWh"},
    {"producedEnergyBidirectionalMeter",false,"produced_energy",0,999999,0.001,"kWh"},
    {"energyTodayPilotWire",false,"energy_today",0,999999,0.001,"kWh"},
    {"energyTodayTwcR01",false,"energy_today",0,999999,0.001,"kWh"},
    {"energyYesterdayPilotWire",false,"energy_yesterday",0,999999,0.001,"kWh"},
    {"energyYesterdayTwcR01",false,"energy_yesterday",0,999999,0.001,"kWh"},
    {"acFrequencySdm01",false,"ac_frequency",45,65,0.01,"Hz"},
    {"acFrequencyClamp3Phase",false,"ac_frequency",45,65,0.01,"Hz"},
    {"acFrequencyPc311",false,"ac_frequency",45,65,0.01,"Hz"},
    {"acFrequency2ct",false,"ac_frequency",45,65,0.01,"Hz"},
    {"powerFactorSdm01",false,"power_factor",0,1,0.001,nil},
    {"powerFactorSdm01Percent",false,"power_factor",0,100,1,"%"},
    {"powerFactorClamp3Phase",false,"power_factor",0,1,0.001,nil},
    {"powerFactorClamp3PhasePercent",false,"power_factor",0,100,1,"%"},
    {"powerFactorPc311",false,"power_factor",0,1,0.001,nil},
    {"powerFactorPc311Percent",false,"power_factor",0,100,1,"%"},
    {"powerFactor2ct",false,"power_factor",0,1,0.001,nil},
    {"powerFactor2ctPercent",false,"power_factor",0,100,1,"%"},
    {"reactivePowerDin1",false,"power_reactive",0,999999,1,"var"},
    {"reactivePowerAtms10013z3",false,"power_reactive",0,999999,1,"var"},
    {"leakageCurrentProtector",false,"leakage_current",0,1000,1,"mA"},
    {"leakageCurrentToqJzt",false,"leakage_current",0,1000,1,"mA"},
    {"leakageThresholdProtector",true,"leakage_threshold",0,1000,1,"mA"},
    {"leakageThresholdProtector100ma",true,"leakage_threshold",10,100,1,"mA"},
    {"currentThresholdToqcb2",true,"current_threshold",0,100,0.1,"A"},
    {"currentThresholdToqcb2A63",true,"current_threshold",1,63,1,"A"},
    {"currentThresholdRcbo63a",true,"current_threshold",1,63,1,"A"},
    {"updateFrequency2ct",true,"update_frequency",1,86400,1,"s"},
    {"updateFrequency2ctSeconds60",true,"update_frequency",3,60,1,"s"},
    {"updateFrequencyPj1203a",true,"update_frequency",1,86400,1,"s"},
    {"updateFrequencyPj1203aSeconds60",true,"update_frequency",3,60,1,"s"},
    {"updateFrequencySdm02v1",true,"update_frequency",1,86400,1,"s"},
    {"updateFrequencySdm02v1Seconds3600",true,"update_frequency",5,3600,1,"s"},
    {"updateFrequencyContactS8",true,"update_frequency",1,86400,1,"s"},
    {"updateFrequencyContactS8Minutes",true,"update_frequency",0,700,1,"min"},
    {"valvePositionHbnfokum",true,"position",0,100,10,"%"},
    {"valveCurrentPositionHbnfokum",false,"position_current",0,100,10,"%"},
    {"waterConsumedUltrasonic",false,"water_consumed",0,999999,0.001,"m3"},
    {"waterConsumedUltrasonicLiters",false,"water_consumed",0,999999,0.001,"L"},
    {"waterConsumedHeatMeter",false,"water_consumed",0,999999,0.001,"m3"},
    {"coverPositionReportRm28Le",false,"position_report",0,100,1,"%"},
    {"coverPositionReportZm79eDt",false,"position_report",0,100,1,"%"},
    {"coverPositionReportBx82Tyz1",false,"position_report",0,100,1,"%"},
    {"favoritePositionZbSm",true,"favorite_position",0,100,1,"%"},
    {"temperatureDeltaBotR15w",true,"temperature_delta",0,10,0.1,"C"},
    {"tempDeltaBotRToTen",true,"temperature_delta",0.5,10,0.5,"C"},
    {"temperatureDeltaTgm50",true,"temperature_delta",0,10,0.1,"C"},
    {"tempDeltaTgmCToTen",true,"temperature_delta",0.5,10,0.5,"C"},
    {"temperatureDeltaWall",true,"temperature_delta",0,10,0.1,"C"},
    {"tempDeltaXhCToNinetyFive",true,"temperature_delta",0.5,9.5,0.5,"C"},
    {"maxTemperatureLimitTybac006",true,"max_temperature_limit",5,95,0.5,"C"},
    {"maxTempLimitTybacCToThirty",true,"max_temperature_limit",15,30,1,"C"},
    {"maxTemperatureLimitZht002",true,"max_temperature_limit",5,95,0.5,"C"},
    {"maxTempLimitZhtCToSeventy",true,"max_temperature_limit",25,70,1,"C"},
    {"minTemperatureLimitTybac006",true,"min_temperature_limit",0,50,0.5,"C"},
    {"minTempLimitTybacCToThirty",true,"min_temperature_limit",15,30,1,"C"},
    {"displayBrightnessPressureTemp",true,"display_brightness",0,100,1,"%"},
    {"displayBrightnessPressureLevel8",true,"display_brightness",0,8,1,nil},
    {"displayBrightnessPro900z",true,"display_brightness",0,100,1,"%"},
    {"displayBrightnessPro900zLevel8",true,"display_brightness",0,8,1,nil},
    {"displayBrightnessFcu",true,"display_brightness",0,100,1,"%"},
    {"screenBrightnessL2TFMfLevel9",true,"display_brightness",1,9,1,nil},
    {"alarmDurationSiren",true,"duration",0,1800,1,"s"},
    {"alarmDurationSirenYxzbslMinutes",true,"duration",1,60,1,"min"},
    {"alarmDurationSirenZa03Seconds",true,"duration",1,380,1,"s"},
    {"alarmDurationContactS8",true,"duration",0,1800,1,"s"},
    {"alarmDurationContactS8Sec300",true,"duration",0,300,1,"s"},
    {"alarmDurationGas",true,"duration",0,1800,1,"s"},
    {"alarmDurationGas180",true,"alarm_time",1,180,1,"s"},
    {"vibrationSensitivityZg102zm",true,"sensitivity",0,10,1,nil},
    {"vibrationSensitivityZgFifty",true,"sensitivity",1,50,1,nil},
    {"vibrationSensitivity4cqhd2haLevel",true,"sensitivity",0,2,1,nil},
    {"vibrationLimitSenoroWinV2",true,"vibration_limit",0,100,1,nil},
    {"txPowerSenoroWinLevel",true,"transmission_power",11,19,1,nil},
    {"illuminanceSamplingZg223zMinutes",true,"illuminance_sampling",1,480,1,"min"},
    {"poolPhChlorineMeter",false,"ph",0,14,0.01,"pH"},
    {"poolOrpChlorineMeter",false,"orp",-2000,2000,1,"mV"},
    {"freeChlorineChlorineMeter",false,"free_chlorine",0,20,0.1,"mg/L"},
    {"salinityChlorineMeter",false,"salinity",0,100000,1,"ppm"},
    {"tdsChlorineMeter",false,"tds",0,100000,1,"ppm"},
    {"soilWarningThresholdLegacy",true,"soil_warning_threshold",0,100,1,"%"},
    {"soilWarningThresholdFertility",true,"soil_warning_threshold",0,100,1,"%"},
    {"soilFertilityWarningZsSf",true,"soil_fertility_warning_setting",100,5000,1,"uS/cm"},
    {"garageRunTimeCountdownOpener",true,"run_time",1,300,1,"s"},
    {"garageRunTimeCountdownOpener120",true,"run_time",0,120,1,"s"},
    {"garageOpenAlarmTimeCountdownOpener",true,"open_alarm_time",0,3600,1,"s"},
    {"garageOpenAlarmTimeOpenerDay",true,"open_alarm_time",0,86400,1,"s"},
    {"countdownTsOneTenHours",true,"countdown_timer",0,43200,1,"s"},
    {"countdownTsOneTenHalfMinute",true,"countdown_timer",0,43200,30,"s"},
    {"countdownTimerZclTwelveHours",true,"countdown_timer",0,43200,1,"s"},
    {"minBrightnessZclThousand",true,"min_brightness",0,1000,1,nil},
    {"maxBrightnessZclThousand",true,"max_brightness",0,1000,1,nil},
    {"minimumBrightnessTsOneTenMax",true,"min_brightness",1,255,1,nil},
    {"maxBrightnessTsOneTenMax",true,"max_brightness",1,255,1,nil},
    {"minBrightnessTs0601",true,"min_brightness",0,100,1,nil},
    {"maxBrightnessTs0601",true,"max_brightness",0,100,1,nil},
}
local enum_rows = {
    {"childLock",true,"child_lock",{"off","on"}},
    {"antiInterferenceZg204zx",true,"anti_interference",{"off","on"}},
    {"indicatorZg204zx",true,"indicator",{"off","on"}},
    {"temperatureUnitZg204zx",true,"temperature_unit",{"C","F"}},
    {"selfTestSmoke",true,"self_test",{"off","on"}},
    {"selfTestGas",true,"self_test",{"off","on"}},
    {"selfTestPresence",true,"self_test",{"off","on"}},
    {"clearEnergyRcbo",true,"clear_energy",{"off","on"}},
    {"clearEnergyDinMeter",true,"clear_energy",{"off","on"}},
    {"clearFaultDin2",true,"clear_fault",{"off","on"}},
    {"clearFaultDin3",true,"clear_fault",{"off","on"}},
    {"clearFaultBreaker",true,"clear_fault",{"off","on"}},
    {"tripTestRcbo",true,"trip_test",{"off","on"}},
    {"tripTestRcboTripClear",true,"trip_test",{"clear","trip"}},
    {"tripTestLeakageProtector",true,"trip_test",{"off","on"}},
    {"autoCleanUltrasonicValve",true,"auto_clean",{"off","on"}},
    {"tiltModeMb60l",true,"tilt_mode",{"off","on"}},
    {"manualModeTybac006",true,"manual_mode",{"off","on"}},
    {"manualModeHhst001",true,"manual_mode",{"off","on"}},
    {"manualModeHhstAutoManualTemp",true,"manual_mode",{"auto","manual","temporary"}},
    {"manualModeEpjZb",true,"manual_mode",{"off","on"}},
    {"manualModeEpjZbEnableDisable",true,"manual_mode",{"enable","disable"}},
    {"pilotWireModeTwcR01",true,"pilot_wire_mode",{"comfort","eco","antifrost","off","comfort_1","comfort_2"}},
    {"windowDetectionTervix",true,"window_detection",{"off","on"}},
    {"windowDetectionPilotWire",true,"window_detection",{"off","on"}},
    {"windowDetectionEpjZbState",true,"window_detection",{"opened","closed","pending"}},
    {"mufflingWaterLeak",true,"muffling",{"off","on"}},
    {"mufflingSiren",true,"muffling",{"off","on"}},
    {"dryDetectionSoilAirDry",true,"dry_detection",{"off","on"}},
    {"waterShortageSoilWarningLegacy",true,"water_shortage",{"off","on"}},
    {"valveStatusDualIrrigation",false,"valve_status",{"open","closed","opening","closing","fault"}},
    {"valveStatusDualIrrigationMode",false,"valve_status",{"manual","auto","idle"}},
    {"motorDirectionZbSm",true,"motor_direction",{"forward","reverse"}},
    {"motorDirectionZbSmNormalRev",true,"motor_direction",{"normal","reversed"}},
    {"motorDirectionZm79eDt",true,"motor_direction",{"forward","reverse"}},
    {"motorDirectionZm79eDtLeftRight",true,"motor_direction",{"left","right"}},
    {"motorDirectionBx82Tyz1",true,"motor_direction",{"forward","reverse"}},
    {"motorDirectionBxTyzNormalRev",true,"motor_direction",{"normal","reversed"}},
    {"motorDirectionMb60l",true,"motor_direction",{"forward","reverse"}},
    {"motorDirectionMbNormalRev",true,"motor_direction",{"normal","reversed"}},
    {"motorDirectionEpjZb",true,"motor_direction",{"forward","reverse"}},
    {"motorDirectionEpjZbSide",true,"motor_direction",{"left_side","right_side"}},
    {"coverWorkStatePims3028",false,"work_state",{"idle","opening","closing","stopped","fault"}},
    {"coverWorkPimsActual",false,"work_state",{"opening","closing","value_123"}},
    {"coverWorkStateRm28Le",false,"work_state",{"idle","opening","closing","stopped","fault"}},
    {"coverWorkRmOpeningClosing",false,"work_state",{"opening","closing"}},
    {"coverWorkStateZm79eDt",false,"work_state",{"idle","opening","closing","stopped","fault"}},
    {"coverWorkStateZm79eDtLearning",false,"work_state",{"standby","success","learning"}},
    {"coverCalibrationPims3028StartEnd",true,"calibration",{"start","end"}},
    {"coverCalibrationZm79eDt",true,"calibration",{"idle","start","set_upper","set_lower","calibrate","reset"}},
    {"coverCalibrationMb60l",true,"calibration",{"idle","start","set_upper","set_lower","calibrate","reset"}},
    {"thermostatPresetZgWkDa",true,"preset",{"manual","schedule","holiday","temporary"}},
    {"thermostatPresetZgWkDaAuto",true,"preset",{"manual","auto"}},
    {"thermostatPresetAr331pro",true,"preset",{"auto","heat","away","eco","comfort","off"}},
    {"thermostatPresetAr331proSixMode",true,"preset",{"auto","manual","holiday","comfort","eco","standby"}},
    {"thermostatPresetZwt07",true,"preset",{"auto","manual","temporary","holiday","off"}},
    {"thermostatPresetZwt07Program",true,"preset",{"program","manual"}},
    {"thermostatPresetTervix",true,"preset",{"auto","manual","temporary","holiday","off"}},
    {"thermostatPresetTervixProgram",true,"preset",{"manual","program"}},
    {"thermostatPresetX5h",true,"preset",{"auto","manual","temporary","holiday","off"}},
    {"thermostatPresetX5hProgram",true,"preset",{"manual","program"}},
    {"thermostatPresetFloor",true,"preset",{"auto","manual","temporary","holiday","off"}},
    {"thermostatPresetFloorHeatAuto",true,"preset",{"heat","auto"}},
    {"thermostatPresetFloorManualAuto",true,"preset",{"manual","auto"}},
    {"temperatureSensorSelectTervix",true,"temperature_sensor_select",{"internal","external","both","floor"}},
    {"tempSensorSelectTervixInOut",true,"temperature_sensor_select",{"in","out"}},
    {"temperatureSensorSelectX5h",true,"temperature_sensor_select",{"internal","external","both","floor"}},
    {"temperatureSensorSelectX5hThree",true,"temperature_sensor_select",{"internal","external","both"}},
    {"workingDayTv02",true,"working_day",{"mon_fri","mon_sat","all_days"}},
    {"workingDayTv02ScheduleMode",true,"working_day",{"mon_sun","mon_fri_sat_sun","separate"}},
    {"workingDayX5h",true,"working_day",{"mon_fri","mon_sat","all_days"}},
    {"alarmVolumeGas",true,"alarm_volume",{"mute","low","medium","high"}},
    {"alarmVolumeHobeian",true,"alarm_volume",{"low","middle","high","mute"}},
    {"alarmVolumeSiren",true,"alarm_volume",{"mute","low","medium","high"}},
    {"alarmVolumeSirenYxzbsl",true,"volume",{"mute","low","middle","high"}},
    {"alarmVolumeSirenZa03",true,"volume",{"low","medium","high","mute"}},
    {"alarmVolumeWaterLeak",true,"alarm_volume",{"mute","low","medium","high"}},
    {"doorbellVolumeHobeian",true,"doorbell_volume",{"low","middle","high","mute"}},
    {"alarmMelodyGas",true,"alarm_melody",{"mute","beep","music","alarm"}},
    {"alarmMelodyGasFive",true,"alarm_ringtone",{"melody_1","melody_2","melody_3","melody_4","melody_5"}},
    {"alarmMelodySiren",true,"alarm_melody",{"mute","beep","music","alarm"}},
    {"alarmRingHobeian",true,"alarm_ring",{"mute","beep","music"}},
    {"alarmRingtoneSirenYxzbsl",true,"ringtone",{"melody1","melody2","melody3","melody4","melody5","melody6","melody7","melody8","door","water","temperature","entered","left"}},
    {"alarmRingtoneSirenZa03",true,"ringtone",{"ringtone_1","ringtone_2","ringtone_3","ringtone_4","ringtone_5","ringtone_6","ringtone_7","ringtone_8","ringtone_9","ringtone_10","ringtone_11","ringtone_12","ringtone_13","ringtone_14","ringtone_15","ringtone_16","ringtone_17","ringtone_18","ringtone_19","ringtone_20","ringtone_21","ringtone_22","ringtone_23","ringtone_24","ringtone_25","ringtone_26","ringtone_27","ringtone_28","ringtone_29","ringtone_30","ringtone_31","ringtone_32"}},
    {"doorbellSirenHobeian",true,"doorbell",{"off","on"}},
    {"openingStateContactTamper3State",false,"opening_state",{"open","closed","tilted"}},
    {"openingStateSenoroWinV23State",false,"opening_state",{"open","closed","tilted"}},
    {"fanModeSequenceAcController",true,"fan_mode_sequence",{"low_medium_high","low_high","on_auto"}},
    {"sensitivitySmoke288wzEnum",true,"sensitivity",{"low","medium","high"}},
    {"sensitivityGasZg225zEnum",true,"sensitivity",{"low","medium","high"}},
    {"sensitivityContactS8Enum",true,"sensitivity",{"off","low","medium","high","max"}},
    {"vibrationSensitivityZg103zEnum",true,"sensitivity",{"low","middle","high"}},
    {"garageStatusCountdownOpener",false,"garage_status",{"closed","opening","open","closing","stopped","fault"}},
    {"garageStatusCountdownOpenerAlarm",false,"garage_status",{"open_time_alarm","run_time_alarm","normal"}},
}
local text_rows = {
    {"deviceFault",false,"fault",256},
    {"meterId",false,"meter_id",256},
    {"thermostatScheduleFloor",true,"schedule",2048},
    {"thermostatScheduleBotR9v",true,"schedule",2048},
    {"thermostatSchedulePro900z",true,"schedule",2048},
    {"thermostatScheduleTv02",true,"schedule",2048},
    {"thermostatScheduleX5h",true,"schedule",2048},
}
return { numeric = build(numeric_rows, numeric), enum = build(enum_rows, enum), text = build(text_rows, text) }
