zigbeeManufacturer:
  - id: "fp_dd0417c062"
    manufacturer: "A-OK"
    model: "AM25"
    deviceProfileName: "covers-cover"
  - id: "fp_60c21949b2"
    manufacturer: "Alutech"
    model: "AM/R-Sm"
    deviceProfileName: "covers-cover"
  - id: "fp_ac63dbc4a3"
    manufacturer: "Binthen"
    model: "BCM100D"
    deviceProfileName: "covers-cover"
  - id: "fp_a69d8f06ab"
    manufacturer: "Binthen"
    model: "CV01A"
    deviceProfileName: "covers-cover"
  - id: "fp_222603f2c0"
    manufacturer: "HOBEIAN"
    model: "ZG-301Z-MOTO"
    deviceProfileName: "covers-cover"
  - id: "fp_2802a558e8"
    manufacturer: "HUARUI"
    model: "CMD900LE"
    deviceProfileName: "covers-cover"
  - id: "fp_d25efb9825"
    manufacturer: "Hiladuo"
    model: "B09M3R35GC"
    deviceProfileName: "covers-cover"
  - id: "fp_703132836d"
    manufacturer: "Homeetec"
    model: "37022173"
    deviceProfileName: "covers-cover-switch-2"
  - id: "fp_7269aaa8d9"
    manufacturer: "Homeetec"
    model: "37022483"
    deviceProfileName: "covers-cover"
  - id: "fp_9e7eeb3117"
    manufacturer: "Homeetec"
    model: "37022493"
    deviceProfileName: "covers-cover-switch-1"
  - id: "fp_de926cd6ed"
    manufacturer: "Larkkey"
    model: "ZSTY-SM-1SRZG-EU"
    deviceProfileName: "covers-cover"
  - id: "fp_fb1f33b4e9"
    manufacturer: "Moes"
    model: "AM43-0.45/40-ES-EB"
    deviceProfileName: "covers-cover"
  - id: "fp_c78c8dfde8"
    manufacturer: "Novato"
    model: "WPK"
    deviceProfileName: "covers-cover"
  - id: "fp_27b5ff904c"
    manufacturer: "Oz Smart Things"
    model: "ZM85EL-1Z"
    deviceProfileName: "covers-cover"
  - id: "fp_48f4e44549"
    manufacturer: "Quoya"
    model: "AT8510-TY"
    deviceProfileName: "covers-cover"
  - id: "fp_255a592766"
    manufacturer: "Roximo"
    model: "CRTZ01"
    deviceProfileName: "covers-cover"
  - id: "fp_c7aeb36f46"
    manufacturer: "Shaman"
    model: "25EB-1/30-TYZ"
    deviceProfileName: "covers-cover"
  - id: "fp_3bef4478bc"
    manufacturer: "Somgoms"
    model: "ZSTY-SM-1DMZG-US-W_1"
    deviceProfileName: "covers-cover"
  - id: "fp_9eb016b570"
    manufacturer: "Tuya"
    model: "DT82LEMA-1.2N"
    deviceProfileName: "covers-cover"
  - id: "fp_5366eb1be1"
    manufacturer: "Tuya"
    model: "M515EGZT"
    deviceProfileName: "covers-cover"
  - id: "fp_a77aa1fa84"
    manufacturer: "Tuya"
    model: "MYQ-RM25-1.3/25-BZ"
    deviceProfileName: "covers-cover"
  - id: "fp_e3b15be519"
    manufacturer: "Tuya"
    model: "ZD82TN"
    deviceProfileName: "covers-cover"
  - id: "fp_df213e62cb"
    manufacturer: "Yushun"
    model: "YS-MT750"
    deviceProfileName: "covers-cover"
  - id: "fp_2c463dadde"
    manufacturer: "Yushun"
    model: "YS-MT750L"
    deviceProfileName: "covers-cover"
  - id: "fp_2c99da42a4"
    manufacturer: "Zemismart"
    model: "AM43"
    deviceProfileName: "covers-cover"
  - id: "fp_2f1a5ba57b"
    manufacturer: "Zemismart"
    model: "M515EGB"
    deviceProfileName: "covers-cover"
  - id: "fp_f7532aa5f7"
    manufacturer: "Zemismart"
    model: "ZM16EL-03/33"
    deviceProfileName: "covers-cover"
  - id: "fp_af2242570c"
    manufacturer: "Zemismart"
    model: "ZM25EL"
    deviceProfileName: "covers-cover"
  - id: "fp_13d649fc06"
    manufacturer: "Zemismart"
    model: "ZM79E-DT"
    deviceProfileName: "covers-cover"
  - id: "fp_301a222e2f"
    manufacturer: "Zemismart"
    model: "ZM85EL-2Z"
    deviceProfileName: "covers-cover"
  - id: "fp_73957cd1d9"
    manufacturer: "Zemismart"
    model: "ZMS1-TYZ"
    deviceProfileName: "covers-cover"
  - id: "fp_41faa5e1fe"
    manufacturer: "_TZ3210_emqmwtym"
    model: "TS0601"
    deviceProfileName: "covers-cover-battery-epj-zb"
  - id: "fp_545918fa74"
    manufacturer: "_TZE200_1fuxihti"
    model: "TS0601"
    deviceProfileName: "covers-cover"
  - id: "fp_54f5ea2d05"
    manufacturer: "_TZE200_1vxgqfba"
    model: "TS0601"
    deviceProfileName: "covers-cover"
  - id: "fp_95c29a6be0"
    manufacturer: "_TZE200_2odrmqwq"
    model: "TS0601"
    deviceProfileName: "covers-cover"
  - id: "fp_0acdd749fd"
    manufacturer: "_TZE200_2vfxweng"
    model: "TS0601"
    deviceProfileName: "covers-cover"
  - id: "fp_4070f0677f"
    manufacturer: "_TZE200_3i3exuay"
    model: "TS0601"
    deviceProfileName: "covers-cover"
  - id: "fp_d1daf43443"
    manufacturer: "_TZE200_4vobcgd3"
    model: "TS0601"
    deviceProfileName: "covers-cover"
  - id: "fp_48ee8a92d2"
    manufacturer: "_TZE200_5nldle7w"
    model: "TS0601"
    deviceProfileName: "covers-cover-switch-2"
  - id: "fp_cf8e65f00b"
    manufacturer: "_TZE200_5sbebbzs"
    model: "TS0601"
    deviceProfileName: "covers-cover"
  - id: "fp_2ef7054dbd"
    manufacturer: "_TZE200_5zbp6j0u"
    model: "TS0601"
    deviceProfileName: "covers-cover"
  - id: "fp_73ea5768be"
    manufacturer: "_TZE200_68nvbi09"
    model: "TS0601"
    deviceProfileName: "covers-cover"
  - id: "fp_b0235b3e15"
    manufacturer: "_TZE200_68nvbio9"
    model: "TS0601"
    deviceProfileName: "covers-cover"
  - id: "fp_9a02426ee6"
    manufacturer: "_TZE200_7eue9vhc"
    model: "TS0601"
    deviceProfileName: "covers-cover"
  - id: "fp_d68f52565d"
    manufacturer: "_TZE200_9p5xmj5r"
    model: "TS0601"
    deviceProfileName: "covers-cover"
  - id: "fp_c128953f68"
    manufacturer: "_TZE200_9vpe3fl1"
    model: "TS0601"
    deviceProfileName: "covers-cover"
  - id: "fp_79d521222d"
    manufacturer: "_TZE200_a8z0g46u"
    model: "TS0601"
    deviceProfileName: "covers-cover"
  - id: "fp_a5cac0d296"
    manufacturer: "_TZE200_ax8a8ahx"
    model: "TS0601"
    deviceProfileName: "covers-cover-zm79e-dt"
  - id: "fp_0ea85e8cee"
    manufacturer: "_TZE200_axgvo9jh"
    model: "TS0601"
    deviceProfileName: "covers-cover"
  - id: "fp_d8f46ece06"
    manufacturer: "_TZE200_b2u1drdv"
    model: "TS0601"
    deviceProfileName: "covers-cover"
  - id: "fp_ca758ee8db"
    manufacturer: "_TZE200_ba69l9ol"
    model: "TS0601"
    deviceProfileName: "covers-cover"
  - id: "fp_c848cc5a85"
    manufacturer: "_TZE200_bdblidq3"
    model: "TS0601"
    deviceProfileName: "covers-cover"
  - id: "fp_a613010bb8"
    manufacturer: "_TZE200_bqcqqjpb"
    model: "TS0601"
    deviceProfileName: "covers-cover"
  - id: "fp_394980b013"
    manufacturer: "_TZE200_bv1jcqqu"
    model: "TS0601"
    deviceProfileName: "covers-cover"
  - id: "fp_f413317619"
    manufacturer: "_TZE200_cf1sl3tj"
    model: "TS0601"
    deviceProfileName: "covers-cover"
  - id: "fp_97a0ed03c1"
    manufacturer: "_TZE200_clm4gdw4"
    model: "TS0601"
    deviceProfileName: "covers-cover"
  - id: "fp_ebc22b835f"
    manufacturer: "_TZE200_cowvfni3"
    model: "TS0601"
    deviceProfileName: "covers-cover"
  - id: "fp_2ccd29f0f9"
    manufacturer: "_TZE200_cpbo62rn"
    model: "TS0601"
    deviceProfileName: "covers-cover"
  - id: "fp_7c79730b8b"
    manufacturer: "_TZE200_cxu0jkjk"
    model: "TS0601"
    deviceProfileName: "covers-cover"
  - id: "fp_c2a1b6fab6"
    manufacturer: "_TZE200_dng9fn0k"
    model: "TS0601"
    deviceProfileName: "covers-cover"
  - id: "fp_4230a877f0"
    manufacturer: "_TZE200_eegnwoyw"
    model: "TS0601"
    deviceProfileName: "covers-cover"
  - id: "fp_c1c203630f"
    manufacturer: "_TZE200_eevqq1uv"
    model: "TS0601"
    deviceProfileName: "covers-cover"
  - id: "fp_b13103b87c"
    manufacturer: "_TZE200_eqpaxqdv"
    model: "TS0601"
    deviceProfileName: "covers-cover-pims3028"
  - id: "fp_2461106beb"
    manufacturer: "_TZE200_ergbiejo"
    model: "TS0601"
    deviceProfileName: "covers-cover"
  - id: "fp_1d01515be1"
    manufacturer: "_TZE200_fctwhugx"
    model: "TS0601"
    deviceProfileName: "covers-cover"
  - id: "fp_2efa41fcfc"
    manufacturer: "_TZE200_fdtjuw7u"
    model: "TS0601"
    deviceProfileName: "covers-cover"
  - id: "fp_6f481deb43"
    manufacturer: "_TZE200_feolm6rk"
    model: "TS0601"
    deviceProfileName: "covers-cover"
  - id: "fp_9ec04a49c1"
    manufacturer: "_TZE200_fodv6bkr"
    model: "TS0601"
    deviceProfileName: "covers-cover-battery-rm28-le"
  - id: "fp_761dac31b2"
    manufacturer: "_TZE200_fzo2pocs"
    model: "TS0601"
    deviceProfileName: "covers-cover"
  - id: "fp_5543817f81"
    manufacturer: "_TZE200_g5xqosu7"
    model: "TS0601"
    deviceProfileName: "covers-cover"
  - id: "fp_de78ae4378"
    manufacturer: "_TZE200_gaj531w3"
    model: "TS0601"
    deviceProfileName: "covers-cover"
  - id: "fp_b6ca3eeb3b"
    manufacturer: "_TZE200_gnw1rril"
    model: "TS0601"
    deviceProfileName: "covers-cover"
  - id: "fp_70c8e77804"
    manufacturer: "_TZE200_gubdgai2"
    model: "TS0601"
    deviceProfileName: "covers-cover"
  - id: "fp_43b53e216a"
    manufacturer: "_TZE200_hojryzzd"
    model: "TS0601"
    deviceProfileName: "covers-cover"
  - id: "fp_d51c8a37d8"
    manufacturer: "_TZE200_hsgrhjpf"
    model: "TS0601"
    deviceProfileName: "covers-cover"
  - id: "fp_efd9e07823"
    manufacturer: "_TZE200_icka1clh"
    model: "TS0601"
    deviceProfileName: "covers-cover"
  - id: "fp_5d1af00cba"
    manufacturer: "_TZE200_iossyxra"
    model: "TS0601"
    deviceProfileName: "covers-cover"
  - id: "fp_1a25743462"
    manufacturer: "_TZE200_jhkttplm"
    model: "TS0601"
    deviceProfileName: "covers-cover-switch-1"
  - id: "fp_d28a66e6f5"
    manufacturer: "_TZE200_libht6ua"
    model: "TS0601"
    deviceProfileName: "covers-cover"
  - id: "fp_c4b3d3f7bb"
    manufacturer: "_TZE200_m6lwazh9"
    model: "TS0601"
    deviceProfileName: "covers-cover"
  - id: "fp_bef60ea2d7"
    manufacturer: "_TZE200_mlglxwp3"
    model: "TS0601"
    deviceProfileName: "covers-cover"
  - id: "fp_edeb5da3e4"
    manufacturer: "_TZE200_nhyj64w2"
    model: "TS0601"
    deviceProfileName: "covers-cover"
  - id: "fp_7c35012170"
    manufacturer: "_TZE200_nkoabg8w"
    model: "TS0601"
    deviceProfileName: "covers-cover"
  - id: "fp_a245691fca"
    manufacturer: "_TZE200_nogaemzt"
    model: "TS0601"
    deviceProfileName: "covers-cover"
  - id: "fp_793f495dcd"
    manufacturer: "_TZE200_nueqqe6k"
    model: "TS0601"
    deviceProfileName: "covers-cover"
  - id: "fp_6217e4aca0"
    manufacturer: "_TZE200_nw1r9hp6"
    model: "TS0601"
    deviceProfileName: "covers-cover"
  - id: "fp_e2fb3730c6"
    manufacturer: "_TZE200_ol5jlkkr"
    model: "TS0601"
    deviceProfileName: "covers-cover"
  - id: "fp_cf3b629362"
    manufacturer: "_TZE200_p2qzzazi"
    model: "TS0601"
    deviceProfileName: "covers-cover"
  - id: "fp_43204490df"
    manufacturer: "_TZE200_p6vz3wzt"
    model: "TS0601"
    deviceProfileName: "covers-cover"
  - id: "fp_52564b60d3"
    manufacturer: "_TZE200_pk0sfzvr"
    model: "TS0601"
    deviceProfileName: "covers-cover"
  - id: "fp_e0969425f8"
    manufacturer: "_TZE200_pw7mji0l"
    model: "TS0601"
    deviceProfileName: "covers-cover"
  - id: "fp_d4889f9571"
    manufacturer: "_TZE200_rddyvrci"
    model: "TS0601"
    deviceProfileName: "covers-cover"
  - id: "fp_c48b2e4363"
    manufacturer: "_TZE200_rmymn92d"
    model: "TS0601"
    deviceProfileName: "covers-cover"
  - id: "fp_f40d38ee5e"
    manufacturer: "_TZE200_sfqyhvpv"
    model: "TS0601"
    deviceProfileName: "covers-cover"
  - id: "fp_4dfdc1f16a"
    manufacturer: "_TZE200_sq6affpe"
    model: "TS0601"
    deviceProfileName: "covers-cover"
  - id: "fp_971c6296a5"
    manufacturer: "_TZE200_swlgvdlh"
    model: "TS0601"
    deviceProfileName: "covers-cover"
  - id: "fp_83e1c2448c"
    manufacturer: "_TZE200_tvrvdj6o"
    model: "TS0601"
    deviceProfileName: "covers-cover"
  - id: "fp_24ae0646b2"
    manufacturer: "_TZE200_vdiuwbkq"
    model: "TS0601"
    deviceProfileName: "covers-cover"
  - id: "fp_121259514a"
    manufacturer: "_TZE200_vexa5o82"
    model: "TS0601"
    deviceProfileName: "covers-cover"
  - id: "fp_8f451cced2"
    manufacturer: "_TZE200_wdfurkoa"
    model: "TS0601"
    deviceProfileName: "covers-cover"
  - id: "fp_8e2b5e2cae"
    manufacturer: "_TZE200_wehza30a"
    model: "TS0601"
    deviceProfileName: "covers-cover"
  - id: "fp_6190e9900e"
    manufacturer: "_TZE200_wmcdj3aq"
    model: "TS0601"
    deviceProfileName: "covers-cover"
  - id: "fp_ad0f7e48c3"
    manufacturer: "_TZE200_xaabybja"
    model: "TS0601"
    deviceProfileName: "covers-cover"
  - id: "fp_8e79f7796b"
    manufacturer: "_TZE200_xuzcvlku"
    model: "TS0601"
    deviceProfileName: "covers-cover"
  - id: "fp_3469f6d32a"
    manufacturer: "_TZE200_yenbr4om"
    model: "TS0601"
    deviceProfileName: "covers-cover"
  - id: "fp_6678ffc7b6"
    manufacturer: "_TZE200_zah67ekd"
    model: "TS0601"
    deviceProfileName: "covers-cover"
  - id: "fp_e365e2bc22"
    manufacturer: "_TZE200_zpzndjez"
    model: "TS0601"
    deviceProfileName: "covers-cover"
  - id: "fp_f151450cd4"
    manufacturer: "_TZE200_zuz7f94z"
    model: "TS0601"
    deviceProfileName: "covers-cover"
  - id: "fp_ae249669aa"
    manufacturer: "_TZE200_zvo63cmo"
    model: "TS0601"
    deviceProfileName: "covers-cover"
  - id: "fp_4191114930"
    manufacturer: "_TZE200_zxxfv8wi"
    model: "TS0601"
    deviceProfileName: "covers-cover"
  - id: "fp_732cbd6d56"
    manufacturer: "_TZE200_zyrdrmno"
    model: "TS0601"
    deviceProfileName: "covers-cover-zb-sm"
  - id: "fp_f7db3f7ab7"
    manufacturer: "_TZE204_1fuxihti"
    model: "TS0601"
    deviceProfileName: "covers-cover"
  - id: "fp_b0cfd9a3ed"
    manufacturer: "_TZE204_2rvvqjoa"
    model: "TS0601"
    deviceProfileName: "covers-cover-bx82-tyz1"
  - id: "fp_14189f1426"
    manufacturer: "_TZE204_57hjqelq"
    model: "TS0601"
    deviceProfileName: "covers-cover"
  - id: "fp_818bccf7a4"
    manufacturer: "_TZE204_a8z0g46u"
    model: "TS0601"
    deviceProfileName: "covers-cover"
  - id: "fp_be732a9fbc"
    manufacturer: "_TZE204_bdblidq3"
    model: "TS0601"
    deviceProfileName: "covers-cover"
  - id: "fp_f5271b2b74"
    manufacturer: "_TZE204_ejh6owwz"
    model: "TS0601"
    deviceProfileName: "covers-cover"
  - id: "fp_4981d0644a"
    manufacturer: "_TZE204_g5xqosu7"
    model: "TS0601"
    deviceProfileName: "covers-cover"
  - id: "fp_00913f89ab"
    manufacturer: "_TZE204_guvc7pdy"
    model: "TS0601"
    deviceProfileName: "covers-cover"
  - id: "fp_b16b01ab20"
    manufacturer: "_TZE204_lh3arisb"
    model: "TS0601"
    deviceProfileName: "covers-cover"
  - id: "fp_88e460c27d"
    manufacturer: "_TZE204_p6vz3wzt"
    model: "TS0601"
    deviceProfileName: "covers-cover"
  - id: "fp_75b35295a0"
    manufacturer: "_TZE204_r0jdjrvi"
    model: "TS0601"
    deviceProfileName: "covers-cover"
  - id: "fp_4925eeb724"
    manufacturer: "_TZE204_trwaxi57"
    model: "TS0601"
    deviceProfileName: "covers-cover-switch-2"
  - id: "fp_852c1b87ed"
    manufacturer: "_TZE204_vvvtcehj"
    model: "TS0601"
    deviceProfileName: "covers-cover"
  - id: "fp_0b3c5522a1"
    manufacturer: "_TZE204_xu4a5rhj"
    model: "TS0601"
    deviceProfileName: "covers-cover"
  - id: "fp_cff3be9fa1"
    manufacturer: "_TZE204_ycke4deo"
    model: "TS0601"
    deviceProfileName: "covers-cover"
  - id: "fp_9f36feb6f6"
    manufacturer: "_TZE204_zuq5xxib"
    model: "TS0601"
    deviceProfileName: "covers-cover"
  - id: "fp_f83d959e96"
    manufacturer: "_TZE210_inpjmc0h"
    model: "TS0301"
    deviceProfileName: "covers-cover-2"
  - id: "fp_8d827bcfca"
    manufacturer: "_TZE210_m6lwazh9"
    model: "TS0301"
    deviceProfileName: "covers-cover"
  - id: "fp_5d6f6f897b"
    manufacturer: "_TZE284_1fuxihti"
    model: "TS0601"
    deviceProfileName: "covers-cover"
  - id: "fp_05e699bd15"
    manufacturer: "_TZE284_2gi1hy8s"
    model: "TS0601"
    deviceProfileName: "covers-cover-battery-mb60l"
  - id: "fp_86fd5604e7"
    manufacturer: "_TZE284_3mzb0sdz"
    model: "TS0601"
    deviceProfileName: "covers-cover"
  - id: "fp_a89db34a79"
    manufacturer: "_TZE284_4vobcgd3"
    model: "TS0601"
    deviceProfileName: "covers-cover"
  - id: "fp_af1c2f87b5"
    manufacturer: "_TZE284_6fopvb6v"
    model: "TS0601"
    deviceProfileName: "covers-cover"
  - id: "fp_2ba3a7930c"
    manufacturer: "_TZE284_clm4gdw4"
    model: "TS0601"
    deviceProfileName: "covers-cover"
  - id: "fp_d24624c353"
    manufacturer: "_TZE284_fzo2pocs"
    model: "TS0601"
    deviceProfileName: "covers-cover"
  - id: "fp_e4cf5516a0"
    manufacturer: "_TZE284_gaj531w3"
    model: "TS0601"
    deviceProfileName: "covers-cover"
  - id: "fp_208d72c45d"
    manufacturer: "_TZE284_koxaopnk"
    model: "TS0601"
    deviceProfileName: "covers-cover"
  - id: "fp_9172ab34b3"
    manufacturer: "_TZE284_libht6ua"
    model: "TS0601"
    deviceProfileName: "covers-cover"
  - id: "fp_97da2896a3"
    manufacturer: "_TZE284_r3szw0xr"
    model: "TS0601"
    deviceProfileName: "covers-cover"
  - id: "fp_e431128ef1"
    manufacturer: "_TZE284_uqfph8ah"
    model: "TS0601"
    deviceProfileName: "covers-cover"
  - id: "fp_ced05ad6ae"
    manufacturer: "_TZE284_waa352qv"
    model: "TS0601"
    deviceProfileName: "covers-cover"
  - id: "fp_940577e921"
    manufacturer: "_TZE284_wdfurkoa"
    model: "TS0601"
    deviceProfileName: "covers-cover"
  - id: "fp_b652eb2d39"
    manufacturer: "_TZE600_ogyg1y6b"
    model: "TS0105"
    deviceProfileName: "covers-cover"
