zigbeeManufacturer:
  - id: "fp_68ef6690ca"
    manufacturer: "HOCH"
    model: "ZJSBL7-100Z"
    deviceProfileName: "din-rail-switch-power-energy-voltage-current-rcbo"
  - id: "fp_bcc98f906c"
    manufacturer: "Hiking"
    model: "DDS238-2"
    deviceProfileName: "din-rail-switch-power-energy-voltage-current-din1"
  - id: "fp_d5adb5cc34"
    manufacturer: "MatSee Plus"
    model: "DAC2161C"
    deviceProfileName: "din-rail-switch-power-energy-voltage-current-din2"
  - id: "fp_4834acb58f"
    manufacturer: "MatSee Plus"
    model: "PC321-Z-TY"
    deviceProfileName: "meters-power-energy-voltage-current-clamp3phase"
  - id: "fp_7d8f5b8720"
    manufacturer: "Nous"
    model: "D4Z"
    deviceProfileName: "meters-power-energy-voltage-current-sdm01"
  - id: "fp_d9dd6b86eb"
    manufacturer: "OWON"
    model: "PC321-Z-TY"
    deviceProfileName: "meters-power-energy-voltage-current-clamp3phase"
  - id: "fp_d527974cdf"
    manufacturer: "Ourtop"
    model: "ATMS100133Z"
    deviceProfileName: "meters-power-energy-atms10013z3"
  - id: "fp_e5ad9d32f8"
    manufacturer: "SUTON"
    model: "STB3L-125/ZJ"
    deviceProfileName: "din-rail-switch-power-energy-voltage-current"
  - id: "fp_24e30cf9e4"
    manufacturer: "TNCE"
    model: "RMDZB-1PNL63"
    deviceProfileName: "din-rail-switch-power-energy-voltage-current"
  - id: "fp_964d1716f1"
    manufacturer: "Tongou"
    model: "TOQCB2-80-2P"
    deviceProfileName: "din-rail-switch-power-energy-voltage-current-toqcb2"
  - id: "fp_1a3d2392d6"
    manufacturer: "Tongou"
    model: "TOSA1-01WXJAT2A"
    deviceProfileName: "meters-power-energy-voltage-current"
  - id: "fp_fbf5e4c5d2"
    manufacturer: "Tongou"
    model: "TOWSMR1-20A-AC"
    deviceProfileName: "din-rail-switch-power-energy-voltage-current-toqjzt"
  - id: "fp_0cb77c96f4"
    manufacturer: "Tongou"
    model: "TOWSMR1-40A-A"
    deviceProfileName: "din-rail-switch-power-energy-voltage-current-toqjzt"
  - id: "fp_e340aa8e42"
    manufacturer: "Tongou"
    model: "TOWSMR1-40A-AC"
    deviceProfileName: "din-rail-switch-power-energy-voltage-current-toqjzt"
  - id: "fp_2cda0814af"
    manufacturer: "Tuya"
    model: "PJ-1203-W"
    deviceProfileName: "meters-power-energy-voltage-current"
  - id: "fp_d17b921603"
    manufacturer: "Tuya"
    model: "RC-MCB"
    deviceProfileName: "din-rail-switch-power-energy-voltage-current-din1"
  - id: "fp_86019a4356"
    manufacturer: "WDYK"
    model: "ZJSBL7-100Z"
    deviceProfileName: "din-rail-switch-power-energy-voltage-current-rcbo"
  - id: "fp_98f8573a21"
    manufacturer: "XOCA"
    model: "DAC2161C"
    deviceProfileName: "din-rail-switch-power-energy-voltage-current-din3"
  - id: "fp_e50fb7534a"
    manufacturer: "_TZE200_78ioiaml"
    model: "TS0601"
    deviceProfileName: "meters-power-energy-2phase-sdm02v1"
  - id: "fp_e9c51cfe3c"
    manufacturer: "_TZE200_abatw3kj"
    model: "TS0601"
    deviceProfileName: "din-rail-switch-power-energy-voltage-current"
  - id: "fp_7f65e34478"
    manufacturer: "_TZE200_bcusnqt8"
    model: "TS0601"
    deviceProfileName: "meters-power-energy-voltage-current-bidirectional"
  - id: "fp_4db48c175a"
    manufacturer: "_TZE200_bkkmqmyo"
    model: "TS0601"
    deviceProfileName: "din-rail-switch-power-energy-voltage-current-din1"
  - id: "fp_f56276c075"
    manufacturer: "_TZE200_byzdayie"
    model: "TS0601"
    deviceProfileName: "din-rail-switch-power-energy-voltage-current"
  - id: "fp_472d2b289d"
    manufacturer: "_TZE200_d2zfgtij"
    model: "TS0601"
    deviceProfileName: "meters-power-energy-voltage-current-bidirectional"
  - id: "fp_4dfd56ae47"
    manufacturer: "_TZE200_dikb3dp6"
    model: "TS0601"
    deviceProfileName: "meters-power-energy-voltage-current-sdm01"
  - id: "fp_7ea9aea9a9"
    manufacturer: "_TZE200_eaac7dkw"
    model: "TS0601"
    deviceProfileName: "din-rail-switch-power-energy-voltage-current-din1"
  - id: "fp_1552f0ac3c"
    manufacturer: "_TZE200_ewxhg6o9"
    model: "TS0601"
    deviceProfileName: "din-rail-switch-power-energy-voltage-current"
  - id: "fp_2b9b5933c2"
    manufacturer: "_TZE200_fsb6zw01"
    model: "TS0601"
    deviceProfileName: "din-rail-switch-power-energy-voltage-current"
  - id: "fp_8893a7945e"
    manufacturer: "_TZE200_gomuk3dc"
    model: "TS0601"
    deviceProfileName: "meters-power-energy-voltage-current"
  - id: "fp_a59ce332c6"
    manufacturer: "_TZE200_hkdl5fmv"
    model: "TS0601"
    deviceProfileName: "din-rail-switch-power-energy-voltage-current-rcbo"
  - id: "fp_ecea9a71c3"
    manufacturer: "_TZE200_iwn0gpzz"
    model: "TS0601"
    deviceProfileName: "meters-power-energy-voltage-current-bidirectional"
  - id: "fp_1f38afa435"
    manufacturer: "_TZE200_lsanae15"
    model: "TS0601"
    deviceProfileName: "din-rail-switch-power-energy-voltage-current-din2"
  - id: "fp_5870ac9896"
    manufacturer: "_TZE200_nslr42tt"
    model: "TS0601"
    deviceProfileName: "meters-power-energy-voltage-current-clamp3phase"
  - id: "fp_ca03d12bc5"
    manufacturer: "_TZE200_ny94onlb"
    model: "TS0601"
    deviceProfileName: "meters-power-energy-voltage-current-sdm01"
  - id: "fp_988ead0996"
    manufacturer: "_TZE200_qhlxve78"
    model: "TS0601"
    deviceProfileName: "meters-power-energy-voltage-current-bidirectional"
  - id: "fp_24bfeaeed2"
    manufacturer: "_TZE200_rhblgy0z"
    model: "TS0601"
    deviceProfileName: "din-rail-switch-power-energy-voltage-current-din3"
  - id: "fp_da8767eeb7"
    manufacturer: "_TZE200_rks0sgb7"
    model: "TS0601"
    deviceProfileName: "meters-power-energy-voltage-current-pc311"
  - id: "fp_74114d9de6"
    manufacturer: "_TZE200_s4sa1mcx"
    model: "TS0601"
    deviceProfileName: "meters-power-energy-voltage-current-sdm01"
  - id: "fp_6ce497d9b3"
    manufacturer: "_TZE200_ugekduaj"
    model: "TS0601"
    deviceProfileName: "meters-power-energy-voltage-current-sdm01"
  - id: "fp_58ffad87c3"
    manufacturer: "_TZE200_v9hkz2yn"
    model: "TS0601"
    deviceProfileName: "meters-power-energy-voltage-current-sdm01"
  - id: "fp_0388b5e111"
    manufacturer: "_TZE200_ves1ycwx"
    model: "TS0601"
    deviceProfileName: "meters-power-energy-voltage-current-sdm01"
  - id: "fp_8c4e64f0a4"
    manufacturer: "_TZE200_wbhaespm"
    model: "TS0601"
    deviceProfileName: "din-rail-switch-power-energy-voltage-current"
  - id: "fp_79c139f51b"
    manufacturer: "_TZE200_wjk6rurm"
    model: "TS0601"
    deviceProfileName: "meters-power-energy-voltage-current-sdm01"
  - id: "fp_f7a45eacdf"
    manufacturer: "_TZE200_x8diwkqb"
    model: "TS0601"
    deviceProfileName: "meters-power-energy-2phase-sdm02v1"
  - id: "fp_f77622b29c"
    manufacturer: "_TZE200_x8fp01wi"
    model: "TS0601"
    deviceProfileName: "switch-power-energy"
  - id: "fp_3d85649805"
    manufacturer: "_TZE204_432zhuwe"
    model: "TS0601"
    deviceProfileName: "din-rail-switch-power-energy-voltage-current-toqjzt"
  - id: "fp_ecb3b81694"
    manufacturer: "_TZE204_4bjixefp"
    model: "TS0601"
    deviceProfileName: "din-rail-switch-power-energy-voltage-current"
  - id: "fp_e6cf6e66e6"
    manufacturer: "_TZE204_78ioiaml"
    model: "TS0601"
    deviceProfileName: "meters-power-energy-2phase-sdm02v1"
  - id: "fp_728bc5bc5d"
    manufacturer: "_TZE204_81yrt3lo"
    model: "TS0601"
    deviceProfileName: "meters-power-energy-voltage-current-pj1203a"
  - id: "fp_5142424d25"
    manufacturer: "_TZE204_ac0fhfiq"
    model: "TS0601"
    deviceProfileName: "meters-power-energy-voltage-current-bidirectional"
  - id: "fp_eeea88b560"
    manufacturer: "_TZE204_bkkmqmyo"
    model: "TS0601"
    deviceProfileName: "din-rail-switch-power-energy-voltage-current-din1"
  - id: "fp_161a7df4fa"
    manufacturer: "_TZE204_byzdayie"
    model: "TS0601"
    deviceProfileName: "din-rail-switch-power-energy-voltage-current"
  - id: "fp_7b1538faf2"
    manufacturer: "_TZE204_cjbofhxw"
    model: "TS0601"
    deviceProfileName: "meters-power-energy-voltage-current"
  - id: "fp_73576dbdca"
    manufacturer: "_TZE204_d2zfgtij"
    model: "TS0601"
    deviceProfileName: "meters-power-energy-voltage-current-bidirectional"
  - id: "fp_9032c85bed"
    manufacturer: "_TZE204_dhotiauw"
    model: "TS0601"
    deviceProfileName: "meters-power-energy-voltage-current-2ct"
  - id: "fp_e8a3c3a505"
    manufacturer: "_TZE204_dikb3dp6"
    model: "TS0601"
    deviceProfileName: "meters-power-energy-voltage-current-sdm01"
  - id: "fp_262b8ccf3c"
    manufacturer: "_TZE204_fhvdgeuh"
    model: "TS0601"
    deviceProfileName: "din-rail-switch-power-energy-voltage-current"
  - id: "fp_aa6dde225c"
    manufacturer: "_TZE204_gomuk3dc"
    model: "TS0601"
    deviceProfileName: "meters-power-energy-voltage-current"
  - id: "fp_21276173fe"
    manufacturer: "_TZE204_iwn0gpzz"
    model: "TS0601"
    deviceProfileName: "meters-power-energy-voltage-current-bidirectional"
  - id: "fp_37153c7038"
    manufacturer: "_TZE204_jcwbwckh"
    model: "TS0601"
    deviceProfileName: "din-rail-switch-power-energy-voltage-current"
  - id: "fp_e4fc92450f"
    manufacturer: "_TZE204_kobbcyum"
    model: "TS0601"
    deviceProfileName: "din-rail-switch-power-energy-voltage-current-toqjzt"
  - id: "fp_48ea2597c0"
    manufacturer: "_TZE204_l6llgoxq"
    model: "TS0601"
    deviceProfileName: "din-rail-switch-power-energy-voltage-current-din2"
  - id: "fp_a069d09ff7"
    manufacturer: "_TZE204_lb0fsvba"
    model: "TS0601"
    deviceProfileName: "din-rail-switch-power-energy-voltage-current"
  - id: "fp_d2163464d4"
    manufacturer: "_TZE204_loejka0i"
    model: "TS0601"
    deviceProfileName: "meters-power-energy-voltage-current-sdm01"
  - id: "fp_a1e8e6a15a"
    manufacturer: "_TZE204_lsanae15"
    model: "TS0601"
    deviceProfileName: "din-rail-switch-power-energy-voltage-current-din2"
  - id: "fp_65949066b6"
    manufacturer: "_TZE204_m64smti7"
    model: "TS0601"
    deviceProfileName: "din-rail-switch-power-energy-voltage-current"
  - id: "fp_5414c87cd5"
    manufacturer: "_TZE204_mrffaamu"
    model: "TS0601"
    deviceProfileName: "din-rail-switch-power-energy-voltage-current-toqcb2"
  - id: "fp_8fbc9a545b"
    manufacturer: "_TZE204_ny94onlb"
    model: "TS0601"
    deviceProfileName: "meters-power-energy-voltage-current-sdm01"
  - id: "fp_2fa660c083"
    manufacturer: "_TZE204_q22avxbv"
    model: "TS0601"
    deviceProfileName: "din-rail-switch-power-energy-voltage-current-toqcb2"
  - id: "fp_b9ae5e6695"
    manufacturer: "_TZE204_qhlxve78"
    model: "TS0601"
    deviceProfileName: "meters-power-energy-voltage-current-bidirectional"
  - id: "fp_3147a60e58"
    manufacturer: "_TZE204_rhblgy0z"
    model: "TS0601"
    deviceProfileName: "din-rail-switch-power-energy-voltage-current-din3"
  - id: "fp_83ea781fe7"
    manufacturer: "_TZE204_s4sa1mcx"
    model: "TS0601"
    deviceProfileName: "meters-power-energy-voltage-current-sdm01"
  - id: "fp_2d6a81ecaa"
    manufacturer: "_TZE204_tuhfx7tf"
    model: "TS0601"
    deviceProfileName: "din-rail-switch-power-energy-voltage-current-toqjzt"
  - id: "fp_846d7f0910"
    manufacturer: "_TZE204_tzreobvu"
    model: "TS0601"
    deviceProfileName: "din-rail-switch-power-energy-voltage-current-toqcb2"
  - id: "fp_d98dce8a87"
    manufacturer: "_TZE204_ugekduaj"
    model: "TS0601"
    deviceProfileName: "meters-power-energy-voltage-current-sdm01"
  - id: "fp_2ce6096b5f"
    manufacturer: "_TZE204_v9hkz2yn"
    model: "TS0601"
    deviceProfileName: "meters-power-energy-voltage-current-sdm01"
  - id: "fp_8ea4883ea8"
    manufacturer: "_TZE204_ves1ycwx"
    model: "TS0601"
    deviceProfileName: "meters-power-energy-voltage-current-sdm01"
  - id: "fp_00201f89de"
    manufacturer: "_TZE204_wbhaespm"
    model: "TS0601"
    deviceProfileName: "din-rail-switch-power-energy-voltage-current"
  - id: "fp_b520ece7f1"
    manufacturer: "_TZE204_wjk6rurm"
    model: "TS0601"
    deviceProfileName: "meters-power-energy-voltage-current-sdm01"
  - id: "fp_c75f510cdd"
    manufacturer: "_TZE204_x8diwkqb"
    model: "TS0601"
    deviceProfileName: "meters-power-energy-2phase-sdm02v1"
  - id: "fp_bf9e6c32e6"
    manufacturer: "_TZE204_x8fp01wi"
    model: "TS0601"
    deviceProfileName: "switch-power-energy"
  - id: "fp_9a0f40a85e"
    manufacturer: "_TZE284_432zhuwe"
    model: "TS0601"
    deviceProfileName: "din-rail-switch-power-energy-voltage-current-toqjzt"
  - id: "fp_7b94d45b2a"
    manufacturer: "_TZE284_4hdbt6rn"
    model: "TS0601"
    deviceProfileName: "meters-power-energy-voltage-current"
  - id: "fp_436f19ed44"
    manufacturer: "_TZE284_5m4nchbm"
    model: "TS0601"
    deviceProfileName: "din-rail-switch-power-energy-voltage-current-leakage-protector"
  - id: "fp_152f900a42"
    manufacturer: "_TZE284_6ocnqlhn"
    model: "TS0601"
    deviceProfileName: "din-rail-switch-power-energy-voltage-current-toqjzt"
  - id: "fp_747ec89d66"
    manufacturer: "_TZE284_78ioiaml"
    model: "TS0601"
    deviceProfileName: "meters-power-energy-2phase-sdm02v1"
  - id: "fp_82b97d3033"
    manufacturer: "_TZE284_81yrt3lo"
    model: "TS0601"
    deviceProfileName: "meters-power-energy-voltage-current-pj1203a"
  - id: "fp_a085be7b98"
    manufacturer: "_TZE284_9xstqowh"
    model: "TS0601"
    deviceProfileName: "din-rail-switch-power-energy-voltage-current-toqcb2"
  - id: "fp_d14b09e730"
    manufacturer: "_TZE284_a14rjslz"
    model: "TS0601"
    deviceProfileName: "meters-power-energy-atms10013z3"
  - id: "fp_87e4581b8b"
    manufacturer: "_TZE284_ac0fhfiq"
    model: "TS0601"
    deviceProfileName: "meters-power-energy-voltage-current-bidirectional"
  - id: "fp_f4c7d5ec93"
    manufacturer: "_TZE284_cjbofhxw"
    model: "TS0601"
    deviceProfileName: "meters-power-energy-voltage-current"
  - id: "fp_154d11aa31"
    manufacturer: "_TZE284_d2zfgtij"
    model: "TS0601"
    deviceProfileName: "meters-power-energy-voltage-current-bidirectional"
  - id: "fp_c7ca107b6b"
    manufacturer: "_TZE284_dikb3dp6"
    model: "TS0601"
    deviceProfileName: "meters-power-energy-voltage-current-sdm01"
  - id: "fp_3946c7b42b"
    manufacturer: "_TZE284_gomuk3dc"
    model: "TS0601"
    deviceProfileName: "meters-power-energy-voltage-current"
  - id: "fp_fdecda579f"
    manufacturer: "_TZE284_hecsejsb"
    model: "TS0601"
    deviceProfileName: "din-rail-switch-power-energy-voltage-current-toqjzt"
  - id: "fp_02610651c9"
    manufacturer: "_TZE284_iwn0gpzz"
    model: "TS0601"
    deviceProfileName: "meters-power-energy-voltage-current-bidirectional"
  - id: "fp_d1ba2d6b38"
    manufacturer: "_TZE284_kobbcyum"
    model: "TS0601"
    deviceProfileName: "din-rail-switch-power-energy-voltage-current-toqjzt"
  - id: "fp_6f6fd73ce0"
    manufacturer: "_TZE284_kv1nvirl"
    model: "TS0601"
    deviceProfileName: "din-rail-switch-power-energy-voltage-current-toqcb2"
  - id: "fp_2866efd63d"
    manufacturer: "_TZE284_loejka0i"
    model: "TS0601"
    deviceProfileName: "meters-power-energy-voltage-current-sdm01"
  - id: "fp_62c2177443"
    manufacturer: "_TZE284_mrffaamu"
    model: "TS0601"
    deviceProfileName: "din-rail-switch-power-energy-voltage-current-toqcb2"
  - id: "fp_6fd9649800"
    manufacturer: "_TZE284_ny94onlb"
    model: "TS0601"
    deviceProfileName: "meters-power-energy-voltage-current-sdm01"
  - id: "fp_bf7e8c8ba5"
    manufacturer: "_TZE284_pglpvdar"
    model: "TS0601"
    deviceProfileName: "meters-power-energy-voltage-current"
  - id: "fp_993a1e636b"
    manufacturer: "_TZE284_q22avxbv"
    model: "TS0601"
    deviceProfileName: "din-rail-switch-power-energy-voltage-current-toqcb2"
  - id: "fp_77458cb556"
    manufacturer: "_TZE284_qhlxve78"
    model: "TS0601"
    deviceProfileName: "meters-power-energy-voltage-current-bidirectional"
  - id: "fp_82bdfc57e4"
    manufacturer: "_TZE284_s4sa1mcx"
    model: "TS0601"
    deviceProfileName: "meters-power-energy-voltage-current-sdm01"
  - id: "fp_6f5e9c4700"
    manufacturer: "_TZE284_s5vuaadg"
    model: "TS0601"
    deviceProfileName: "din-rail-switch-power-energy-voltage-current-toqjzt"
  - id: "fp_a522a0e384"
    manufacturer: "_TZE284_tuhfx7tf"
    model: "TS0601"
    deviceProfileName: "din-rail-switch-power-energy-voltage-current-toqjzt"
  - id: "fp_7f10397965"
    manufacturer: "_TZE284_tzreobvu"
    model: "TS0601"
    deviceProfileName: "din-rail-switch-power-energy-voltage-current-toqcb2"
  - id: "fp_aa939dea2b"
    manufacturer: "_TZE284_v9hkz2yn"
    model: "TS0601"
    deviceProfileName: "meters-power-energy-voltage-current-sdm01"
  - id: "fp_9b00656eaa"
    manufacturer: "_TZE284_ves1ycwx"
    model: "TS0601"
    deviceProfileName: "meters-power-energy-voltage-current-sdm01"
  - id: "fp_7974a98e0d"
    manufacturer: "_TZE284_wbhaespm"
    model: "TS0601"
    deviceProfileName: "din-rail-switch-power-energy-voltage-current"
  - id: "fp_093d707bfb"
    manufacturer: "_TZE284_wjk6rurm"
    model: "TS0601"
    deviceProfileName: "meters-power-energy-voltage-current-sdm01"
  - id: "fp_8b74ba2735"
    manufacturer: "_TZE284_x8diwkqb"
    model: "TS0601"
    deviceProfileName: "meters-power-energy-2phase-sdm02v1"
  - id: "fp_58c0851770"
    manufacturer: "_TZE28C1000000_81yrt3lo"
    model: "TS0601"
    deviceProfileName: "meters-power-energy-voltage-current-pj1203a"
