zigbeeManufacturer:
  - id: fp_1868aa466d
    manufacturer: "AIRPRS1"
    model: "Excellux"
    deviceProfileName: "sensors-wave16-excellux-airprs1"
  - id: fp_03a3c44655
    manufacturer: "EZ500FL"
    model: "Excellux"
    deviceProfileName: "sensors-wave16-excellux-ez500fl"
  - id: fp_b0dcb20459
    manufacturer: "EZ500FS"
    model: "Excellux"
    deviceProfileName: "sensors-wave16-excellux-ez500fs"
  - id: fp_66ab49282d
    manufacturer: "_TZE204_fpwtjlfh"
    model: "TS0601"
    deviceProfileName: "sensors-wave16-lincukoo-ezcp04"
  - id: fp_c6fafd6b9b
    manufacturer: "_TZE204_hyt4iucb"
    model: "TS0601"
    deviceProfileName: "sensors-wave16-lincukoo-e02c-z10t"
  - id: fp_5da1332419
    manufacturer: "_TZE204_isvlaage"
    model: "TS0601"
    deviceProfileName: "sensors-wave16-lincukoo-ezc04"
  - id: fp_fc460cd078
    manufacturer: "_TZE204_pkpfn9hc"
    model: "TS0601"
    deviceProfileName: "sensors-aq-co2-temp-humidity"
  - id: fp_2212b7f63c
    manufacturer: "_TZE2841000000_qf5mzewi"
    model: "TS0601"
    deviceProfileName: "sensors-temp-humidity-battery-alarm-onenuo-th05z"
