-- Generated by source/tools/build_dist.py. Source catalog remains in source/src/core.
local custom_capabilities = {}
local function range(value)
if type(value) ~= "table" then return nil end
return { minimum = value[1], maximum = value[2], step = value[3], unit = value[4], allowed_values = value[5] }
end
local function numeric(row)
return { kind = "numeric", emit_name = row[1], range_key = row[2], capability_id = row[3], attribute_name = row[4], range_attribute_name = row[5], command_name = row[6], argument_name = row[7], mapping_name = row[8], label = row[9], default_range = range(row[10]), event_minimum = row[11], event_maximum = row[12], event_unit = row[13] }
end
local function enum(row)
return { kind = "enum", emit_name = row[1], range_key = row[2], capability_id = row[3], attribute_name = row[4], supported_attribute_name = row[5], command_name = row[6], argument_name = row[7], mapping_name = row[8], label = row[9], supported_values = row[10], default_range = { allowed_values = row[10] } }
end
local function text(row)
return { kind = "text", emit_name = row[1], capability_id = row[2], attribute_name = row[3], command_name = row[4], argument_name = row[5], mapping_name = row[6], label = row[7], maximum_length = row[8] }
end
local function build(rows, factory)
local out = {}
for _, row in ipairs(rows) do out[#out + 1] = factory(row) end
return out
end
custom_capabilities.numeric = build({ { "power_poll_interval", "power_poll_interval", "concertmirror08464.powerPollIntervalV2", "powerPollInterval", "powerPollIntervalRange", "setPowerPollInterval", "powerPollInterval", "power_poll_interval", "Power poll interval", { 5, 3600, 5, "s", nil }, 5, 3600, "s" }, { "countdown_timer", "countdown_timer", "concertmirror08464.countdownTimer", "countdownTimer", "countdownTimerRange", "setCountdownTimer", "countdownTimer", "countdown_timer", "Countdown timer", { 0, 43200, 1, "s", nil }, 0, 43200, "s" }, { "min_brightness", "min_brightness", "concertmirror08464.minimumBrightness", "minBrightness", "minBrightnessRange", "setMinBrightness", "minBrightness", "min_brightness", "Minimum brightness", { 1, 1000, 1, nil, nil }, 1, 1000, nil }, { "max_brightness", "max_brightness", "concertmirror08464.maximumBrightness", "maxBrightness", "maxBrightnessRange", "setMaxBrightness", "maxBrightness", "max_brightness", "Maximum brightness", { 1, 1000, 1, nil, nil }, 1, 1000, nil }, { "countdownTsOneTenHours", nil, "concertmirror08464.countdownTsOneTenHours", "countdownTsOneTenHours", nil, "setCountdownTsOneTenHours", "countdownTsOneTenHours", "countdown_timer", "Countdown Ts One Ten Hours", { 0, 43200, 1, "s", nil }, nil, nil, "s" }, { "minBrightnessTs0601", nil, "concertmirror08464.minBrightnessTs0601", "minBrightTsZeroSixZeroOne", nil, "setMinBrightTsZeroSixZeroOne", "minBrightTsZeroSixZeroOne", "min_brightness", "Min Brightness Ts0601", { 0, 100, 1, nil, nil }, nil, nil, nil }, { "maxBrightnessTs0601", nil, "concertmirror08464.maxBrightnessTs0601", "maxBrightTsZeroSixZeroOne", nil, "setMaxBrightTsZeroSixZeroOne", "maxBrightTsZeroSixZeroOne", "max_brightness", "Max Brightness Ts0601", { 0, 100, 1, nil, nil }, nil, nil, nil } }, numeric)
custom_capabilities.enum = build({ { "indicator_mode", "indicator_mode", "concertmirror08464.indicatorMode", "indicatorMode", "supportedIndicatorModes", "setIndicatorMode", "indicatorMode", "indicator_mode", "Indicator mode", { "off", "off/on", "on/off", "on" } }, { "power_on_behavior", "power_on_behavior", "concertmirror08464.powerOnBehavior", "powerOnBehavior", "supportedPowerOnBehaviors", "setPowerOnBehavior", "powerOnBehavior", "power_on_behavior", "Power on behavior", { "off", "on", "previous" } }, { "switch_type", "switch_type", "concertmirror08464.switchType", "switchType", "supportedSwitchTypes", "setSwitchType", "switchType", "switch_type", "Switch type", { "toggle", "state", "momentary" } }, { "light_type", "light_type", "concertmirror08464.lightType", "lightType", "supportedLightTypes", "setLightType", "lightType", "light_type", "Light type", { "led", "incandescent", "halogen" } } }, enum)
custom_capabilities.text = build({ { "last_power_response_time", "concertmirror08464.lastPowerResponseTime", "lastPowerResponseTime", nil, nil, nil, "Last power response time", 64 } }, text)
custom_capabilities.driver_message = { ["attribute_name"] = "driverMessage", ["capability_id"] = "concertmirror08464.driverMessage", ["emit_name"] = "driver_message", ["label"] = "Driver message", ["maximum_length"] = 512 }
custom_capabilities.by_range_key = {}
custom_capabilities.by_emit_name = {}
custom_capabilities.by_capability_id = {}
local function index_metadata(definitions)
for _, metadata in ipairs(definitions) do
custom_capabilities.by_emit_name[metadata.emit_name] = metadata
if type(metadata.capability_id) == "string" and metadata.capability_id ~= "" then custom_capabilities.by_capability_id[metadata.capability_id] = metadata end
if type(metadata.range_key) == "string" and metadata.range_key ~= "" then custom_capabilities.by_range_key[metadata.range_key] = metadata end
end
end
index_metadata(custom_capabilities.numeric)
index_metadata(custom_capabilities.enum)
index_metadata(custom_capabilities.text)
custom_capabilities.by_emit_name[custom_capabilities.driver_message.emit_name] = custom_capabilities.driver_message
custom_capabilities.by_capability_id[custom_capabilities.driver_message.capability_id] = custom_capabilities.driver_message
local function clone_allowed_values(allowed_values)
if type(allowed_values) ~= "table" then return nil end
local copied = {}
for index, value in ipairs(allowed_values) do copied[index] = value end
return copied
end
function custom_capabilities.resolve_range(definition, metadata)
if type(metadata) ~= "table" then return nil end
local default_range = type(metadata.default_range) == "table" and metadata.default_range or nil
local ranges = type(definition) == "table" and definition.presence_capability_ranges or nil
local resolved = type(ranges) == "table" and ranges[metadata.range_key] or nil
if type(resolved) ~= "table" then resolved = default_range end
if type(resolved) ~= "table" then return nil end
return {
minimum = type(resolved.minimum) == "number" and resolved.minimum or (default_range and default_range.minimum or nil),
maximum = type(resolved.maximum) == "number" and resolved.maximum or (default_range and default_range.maximum or nil),
step = type(resolved.step) == "number" and resolved.step or (default_range and default_range.step or nil),
unit = type(resolved.unit) == "string" and resolved.unit or (default_range and default_range.unit or nil),
allowed_values = type(resolved.allowed_values) == "table" and clone_allowed_values(resolved.allowed_values) or clone_allowed_values(default_range and default_range.allowed_values or nil),
}
end
return custom_capabilities
