name: lights-dimmer-2-zdms16-2
components:
  - id: main
    capabilities:
      - {id: switch, version: 1}
      - {id: switchLevel, version: 1}
      - {id: concertmirror08464.zdmsTwoMinimumBrightness, version: 1}
      - {id: concertmirror08464.zdmsTwoMaximumBrightness, version: 1}
      - {id: concertmirror08464.zdmsTwoCountdown, version: 1}
      - {id: concertmirror08464.zdmsTwoSwitchType, version: 1}
      - {id: concertmirror08464.zdmsTwoPowerOnBehavior, version: 1}
      - {id: refresh, version: 1}
    categories: [{name: Light}]
  - id: switch2
    capabilities:
      - {id: switch, version: 1}
      - {id: switchLevel, version: 1}
      - {id: concertmirror08464.zdmsTwoMinimumBrightness, version: 1}
      - {id: concertmirror08464.zdmsTwoMaximumBrightness, version: 1}
      - {id: concertmirror08464.zdmsTwoCountdown, version: 1}
      - {id: concertmirror08464.zdmsTwoSwitchType, version: 1}
    categories: [{name: Light}]
