zigbeeManufacturer:
  - id: "fp_479ab2caf5"
    manufacturer: "HOBEIAN"
    model: "CK-BL702-MWS-01(7016)"
    deviceProfileName: "safety-presence-zg205za-illuminance"
  - id: "fp_4d17d6eaca"
    manufacturer: "QA"
    model: "QASZ24R"
    deviceProfileName: "safety-presence-mtg075-entry-controls-illuminance"
  - id: "fp_e206fa1e57"
    manufacturer: "Tuya"
    model: "MTG035-ZB-RL"
    deviceProfileName: "safety-presence-mtg075-entry-controls-illuminance"
  - id: "fp_8e8eb4b08c"
    manufacturer: "Tuya"
    model: "MTG235-ZB-RL"
    deviceProfileName: "safety-presence-mtg075-entry-controls-illuminance"
  - id: "fp_a05383e86f"
    manufacturer: "Tuya"
    model: "MTG275-ZB-RL"
    deviceProfileName: "safety-presence-mtg075-entry-controls-illuminance"
  - id: "fp_122a2ec4ec"
    manufacturer: "ZGAF-205L"
    model: "CK-BL702-MWS-01(7016)"
    deviceProfileName: "safety-presence-zg205zl-illuminance"
  - id: "fp_caf75bae5a"
    manufacturer: "_TZ321C_4slreunp"
    model: "TS0225"
    deviceProfileName: "safety-presence-mtd085-entry-range-illuminance"
  - id: "fp_ee96937f94"
    manufacturer: "_TZ321C_fkzihax8"
    model: "TS0225"
    deviceProfileName: "safety-presence-mtd085-entry-range-illuminance"
  - id: "fp_180cce3bd5"
    manufacturer: "_TZE200_clrdrnya"
    model: "TS0601"
    deviceProfileName: "safety-presence-mtg075-entry-controls-illuminance"
  - id: "fp_99906d20eb"
    manufacturer: "_TZE200_crq3r3la"
    model: "CK-BL702-MWS-01(7016)"
    deviceProfileName: "safety-presence-zg205za-illuminance"
  - id: "fp_1582263b13"
    manufacturer: "_TZE200_crq3r3la"
    model: "TS0225"
    deviceProfileName: "safety-presence-zg205za-illuminance"
  - id: "fp_61ee1180d5"
    manufacturer: "_TZE200_gkfbdvyx"
    model: "TS0601"
    deviceProfileName: "safety-presence-zym10024gv3-move-range-illuminance"
  - id: "fp_da8371cd87"
    manufacturer: "_TZE200_hl0ss9oa"
    model: "TS0225"
    deviceProfileName: "safety-presence-zg205zl-illuminance"
  - id: "fp_3d028d7138"
    manufacturer: "_TZE200_mp902om5"
    model: "TS0601"
    deviceProfileName: "safety-presence-mtg075-entry-controls-illuminance"
  - id: "fp_f09b3f9d05"
    manufacturer: "_TZE200_sbyx0lm6"
    model: "TS0601"
    deviceProfileName: "safety-presence-mtg075-entry-controls-illuminance"
  - id: "fp_6ecd1e5d6a"
    manufacturer: "_TZE200_y4mdop0b"
    model: "TS0225"
    deviceProfileName: "safety-presence-zg205zl-illuminance"
  - id: "fp_df81207f37"
    manufacturer: "_TZE200_ya4ft0w4"
    model: "TS0601"
    deviceProfileName: "safety-presence-zym10024gv3-move-range-illuminance"
  - id: "fp_a957286681"
    manufacturer: "_TZE204_7gclukjs"
    model: "TS0601"
    deviceProfileName: "safety-presence-zym10024gv2-move-range-illuminance"
  - id: "fp_7928f58f92"
    manufacturer: "_TZE204_clrdrnya"
    model: "TS0601"
    deviceProfileName: "safety-presence-mtg075-entry-controls-illuminance"
  - id: "fp_98245c293c"
    manufacturer: "_TZE204_dapwryy7"
    model: "TS0601"
    deviceProfileName: "safety-presence-zg205z-illuminance"
  - id: "fp_dd17c824cb"
    manufacturer: "_TZE204_dtzziy1e"
    model: "TS0601"
    deviceProfileName: "safety-presence-mtg075-entry-controls-illuminance"
  - id: "fp_2aac727cd8"
    manufacturer: "_TZE204_e9ajs4ft"
    model: "TS0601"
    deviceProfileName: "safety-presence-ctlr1-threshold-min-delay-illuminance"
  - id: "fp_9272e76e94"
    manufacturer: "_TZE204_gkfbdvyx"
    model: "TS0601"
    deviceProfileName: "safety-presence-zym10024gv3-move-range-illuminance"
  - id: "fp_5f1cb2aa71"
    manufacturer: "_TZE204_iaeejhvf"
    model: "TS0601"
    deviceProfileName: "safety-presence-mtg075-entry-controls-illuminance"
  - id: "fp_4afa46ab26"
    manufacturer: "_TZE204_ijxvkhd0"
    model: "TS0601"
    deviceProfileName: "safety-presence-zym10024g-move-threshold-min-illuminance"
  - id: "fp_132ba06b73"
    manufacturer: "_TZE204_mtoaryre"
    model: "TS0601"
    deviceProfileName: "safety-presence-mtg075-entry-controls-illuminance"
  - id: "fp_e08affeb55"
    manufacturer: "_TZE204_nbkshs6k"
    model: "TS0601"
    deviceProfileName: "safety-presence-zym100s3-keep-illuminance"
  - id: "fp_5d80a9c064"
    manufacturer: "_TZE204_oqtpvx51"
    model: "TS0601"
    deviceProfileName: "safety-presence-yxzbrb58-range-delay-scene-illuminance"
  - id: "fp_c7e2a23651"
    manufacturer: "_TZE204_pfayrzcw"
    model: "TS0601"
    deviceProfileName: "safety-presence-mtg075-entry-controls-illuminance"
  - id: "fp_5757a1b640"
    manufacturer: "_TZE204_sbyx0lm6"
    model: "TS0601"
    deviceProfileName: "safety-presence-mtg075-entry-controls-illuminance"
  - id: "fp_c3a0cc9655"
    manufacturer: "_TZE204_sooucan5"
    model: "TS0601"
    deviceProfileName: "safety-presence-yxzbrb58-range-delay-scene-illuminance"
  - id: "fp_9133417e2e"
    manufacturer: "_TZE204_uxllnywp"
    model: "TS0601"
    deviceProfileName: "safety-presence-rtzcz03z-range-illuminance"
  - id: "fp_9cdd027f82"
    manufacturer: "_TZE204_ya4ft0w4"
    model: "TS0601"
    deviceProfileName: "safety-presence-zym10024gv3-move-range-illuminance"
  - id: "fp_8c6774ef4c"
    manufacturer: "_TZE284_4qznlkbu"
    model: "TS0601"
    deviceProfileName: "safety-presence-mtg075-entry-controls-illuminance"
