name: meters-power-energy-voltage-current-toqsa1
components:
  - id: main
    capabilities:
      - id: powerMeter
        version: 1
      - id: energyMeter
        version: 1
      - id: voltageMeasurement
        version: 1
      - id: currentMeasurement
        version: 1
      - id: temperatureMeasurement
        version: 1
      - id: concertmirror08464.toqsa1AcFrequency
        version: 1
      - id: concertmirror08464.toqsa1PowerFactor
        version: 1
      - id: concertmirror08464.toqsa1Event
        version: 1
      - id: concertmirror08464.toqsa1OverVoltageSetting
        version: 1
      - id: concertmirror08464.toqsa1OverVoltageThreshold
        version: 1
      - id: concertmirror08464.toqsa1UnderVoltageSetting
        version: 1
      - id: concertmirror08464.toqsa1UnderVoltageThreshold
        version: 1
      - id: concertmirror08464.toqsa1OverCurrentSetting
        version: 1
      - id: concertmirror08464.toqsa1OverCurrentThreshold
        version: 1
      - id: concertmirror08464.toqsa1OverPowerSetting
        version: 1
      - id: concertmirror08464.toqsa1OverPowerThreshold
        version: 1
      - id: concertmirror08464.toqsa1TemperatureSetting
        version: 1
      - id: concertmirror08464.toqsa1TemperatureThreshold
        version: 1
      - id: refresh
        version: 1
    categories:
      - name: CurbPowerMeter
deviceConfig:
  dashboard:
    states:
      - component: main
        capability: powerMeter
        version: 1
        group: main
    actions: []
    basicPlus: []
  detailView:
    - component: main
      capability: powerMeter
      version: 1
    - component: main
      capability: energyMeter
      version: 1
    - component: main
      capability: voltageMeasurement
      version: 1
    - component: main
      capability: currentMeasurement
      version: 1
    - component: main
      capability: temperatureMeasurement
      version: 1
    - component: main
      capability: concertmirror08464.toqsa1AcFrequency
      version: 1
    - component: main
      capability: concertmirror08464.toqsa1PowerFactor
      version: 1
    - component: main
      capability: concertmirror08464.toqsa1Event
      version: 1
    - component: main
      capability: concertmirror08464.toqsa1OverVoltageSetting
      version: 1
    - component: main
      capability: concertmirror08464.toqsa1OverVoltageThreshold
      version: 1
    - component: main
      capability: concertmirror08464.toqsa1UnderVoltageSetting
      version: 1
    - component: main
      capability: concertmirror08464.toqsa1UnderVoltageThreshold
      version: 1
    - component: main
      capability: concertmirror08464.toqsa1OverCurrentSetting
      version: 1
    - component: main
      capability: concertmirror08464.toqsa1OverCurrentThreshold
      version: 1
    - component: main
      capability: concertmirror08464.toqsa1OverPowerSetting
      version: 1
    - component: main
      capability: concertmirror08464.toqsa1OverPowerThreshold
      version: 1
    - component: main
      capability: concertmirror08464.toqsa1TemperatureSetting
      version: 1
    - component: main
      capability: concertmirror08464.toqsa1TemperatureThreshold
      version: 1
    - component: main
      capability: refresh
      version: 1
  automation:
    conditions:
      - component: main
        capability: powerMeter
        version: 1
      - component: main
        capability: energyMeter
        version: 1
      - component: main
        capability: voltageMeasurement
        version: 1
      - component: main
        capability: currentMeasurement
        version: 1
      - component: main
        capability: temperatureMeasurement
        version: 1
      - component: main
        capability: concertmirror08464.toqsa1AcFrequency
        version: 1
      - component: main
        capability: concertmirror08464.toqsa1PowerFactor
        version: 1
      - component: main
        capability: concertmirror08464.toqsa1Event
        version: 1
      - component: main
        capability: concertmirror08464.toqsa1OverVoltageSetting
        version: 1
      - component: main
        capability: concertmirror08464.toqsa1OverVoltageThreshold
        version: 1
      - component: main
        capability: concertmirror08464.toqsa1UnderVoltageSetting
        version: 1
      - component: main
        capability: concertmirror08464.toqsa1UnderVoltageThreshold
        version: 1
      - component: main
        capability: concertmirror08464.toqsa1OverCurrentSetting
        version: 1
      - component: main
        capability: concertmirror08464.toqsa1OverCurrentThreshold
        version: 1
      - component: main
        capability: concertmirror08464.toqsa1OverPowerSetting
        version: 1
      - component: main
        capability: concertmirror08464.toqsa1OverPowerThreshold
        version: 1
      - component: main
        capability: concertmirror08464.toqsa1TemperatureSetting
        version: 1
      - component: main
        capability: concertmirror08464.toqsa1TemperatureThreshold
        version: 1
    actions:
      - component: main
        capability: concertmirror08464.toqsa1OverVoltageSetting
        version: 1
      - component: main
        capability: concertmirror08464.toqsa1OverVoltageThreshold
        version: 1
      - component: main
        capability: concertmirror08464.toqsa1UnderVoltageSetting
        version: 1
      - component: main
        capability: concertmirror08464.toqsa1UnderVoltageThreshold
        version: 1
      - component: main
        capability: concertmirror08464.toqsa1OverCurrentSetting
        version: 1
      - component: main
        capability: concertmirror08464.toqsa1OverCurrentThreshold
        version: 1
      - component: main
        capability: concertmirror08464.toqsa1OverPowerSetting
        version: 1
      - component: main
        capability: concertmirror08464.toqsa1OverPowerThreshold
        version: 1
      - component: main
        capability: concertmirror08464.toqsa1TemperatureSetting
        version: 1
      - component: main
        capability: concertmirror08464.toqsa1TemperatureThreshold
        version: 1
