name: meters-power-energy-voltage-current-pj1203a
components:
  - id: main
    capabilities:
      - id: voltageMeasurement
        version: 1
      - id: concertmirror08464.pj1203aAcFrequency
        version: 1
      - id: concertmirror08464.updateFrequencyPj1203aSeconds60
        version: 1
      - id: concertmirror08464.powerPollIntervalV2
        version: 1
      - id: concertmirror08464.lastPowerResponseTime
        version: 1
      - id: firmwareUpdate
        version: 1
      - id: refresh
        version: 1
    categories:
      - name: CurbPowerMeter
  - id: ct1
    label: CT1
    capabilities:
      - id: powerMeter
        version: 1
      - id: currentMeasurement
        version: 1
      - id: energyMeter
        version: 1
      - id: concertmirror08464.pj1203aPowerFactor
        version: 1
      - id: concertmirror08464.pj1203aProducedEnergy
        version: 1
    categories:
      - name: CurbPowerMeter
  - id: ct2
    label: CT2
    capabilities:
      - id: powerMeter
        version: 1
      - id: currentMeasurement
        version: 1
      - id: energyMeter
        version: 1
      - id: concertmirror08464.pj1203aPowerFactor
        version: 1
      - id: concertmirror08464.pj1203aProducedEnergy
        version: 1
    categories:
      - name: CurbPowerMeter
deviceConfig:
  dashboard:
    states:
      - component: main
        capability: voltageMeasurement
        version: 1
        group: main
    actions: []
    basicPlus: []
  detailView:
    - component: main
      capability: voltageMeasurement
      version: 1
    - component: main
      capability: concertmirror08464.pj1203aAcFrequency
      version: 1
    - component: main
      capability: concertmirror08464.updateFrequencyPj1203aSeconds60
      version: 1
    - component: main
      capability: concertmirror08464.powerPollIntervalV2
      version: 1
    - component: main
      capability: concertmirror08464.lastPowerResponseTime
      version: 1
    - component: ct1
      capability: powerMeter
      version: 1
    - component: ct1
      capability: currentMeasurement
      version: 1
    - component: ct1
      capability: energyMeter
      version: 1
    - component: ct1
      capability: concertmirror08464.pj1203aPowerFactor
      version: 1
    - component: ct1
      capability: concertmirror08464.pj1203aProducedEnergy
      version: 1
    - component: ct2
      capability: powerMeter
      version: 1
    - component: ct2
      capability: currentMeasurement
      version: 1
    - component: ct2
      capability: energyMeter
      version: 1
    - component: ct2
      capability: concertmirror08464.pj1203aPowerFactor
      version: 1
    - component: ct2
      capability: concertmirror08464.pj1203aProducedEnergy
      version: 1
    - component: main
      capability: refresh
      version: 1
  automation:
    conditions:
      - component: main
        capability: voltageMeasurement
        version: 1
      - component: main
        capability: concertmirror08464.pj1203aAcFrequency
        version: 1
      - component: main
        capability: concertmirror08464.updateFrequencyPj1203aSeconds60
        version: 1
      - component: main
        capability: concertmirror08464.powerPollIntervalV2
        version: 1
      - component: main
        capability: concertmirror08464.lastPowerResponseTime
        version: 1
    actions:
      - component: main
        capability: concertmirror08464.updateFrequencyPj1203aSeconds60
        version: 1
      - component: main
        capability: concertmirror08464.powerPollIntervalV2
        version: 1
