name: meters-energy-3phase-nous-d4z
components:
  - id: main
    capabilities:
      - id: powerMeter
        version: 1
      - id: energyMeter
        version: 1
      - id: concertmirror08464.nousD4zProducedEnergy
        version: 1
      - id: concertmirror08464.nousD4zAcFrequency
        version: 1
      - id: concertmirror08464.nousD4zPowerFactor
        version: 1
      - id: concertmirror08464.nousD4zFaults
        version: 1
      - id: concertmirror08464.nousD4zEnergyReset
        version: 1
      - id: refresh
        version: 1
    categories:
      - name: CurbPowerMeter
  - id: l1
    label: L1
    capabilities:
      - id: voltageMeasurement
        version: 1
      - id: currentMeasurement
        version: 1
      - id: powerMeter
        version: 1
      - id: energyMeter
        version: 1
    categories:
      - name: CurbPowerMeter
  - id: l2
    label: L2
    capabilities:
      - id: voltageMeasurement
        version: 1
      - id: currentMeasurement
        version: 1
      - id: powerMeter
        version: 1
      - id: energyMeter
        version: 1
    categories:
      - name: CurbPowerMeter
  - id: l3
    label: L3
    capabilities:
      - id: voltageMeasurement
        version: 1
      - id: currentMeasurement
        version: 1
      - id: powerMeter
        version: 1
      - id: energyMeter
        version: 1
    categories:
      - name: CurbPowerMeter
deviceConfig:
  dashboard:
    states:
      - component: main
        capability: powerMeter
        version: 1
        group: main
    actions: []
    basicPlus: []
  detailView:
    - component: main
      capability: powerMeter
      version: 1
    - component: main
      capability: energyMeter
      version: 1
    - component: main
      capability: concertmirror08464.nousD4zProducedEnergy
      version: 1
    - component: main
      capability: concertmirror08464.nousD4zAcFrequency
      version: 1
    - component: main
      capability: concertmirror08464.nousD4zPowerFactor
      version: 1
    - component: main
      capability: concertmirror08464.nousD4zFaults
      version: 1
    - component: main
      capability: concertmirror08464.nousD4zEnergyReset
      version: 1
    - component: l1
      capability: voltageMeasurement
      version: 1
    - component: l1
      capability: currentMeasurement
      version: 1
    - component: l1
      capability: powerMeter
      version: 1
    - component: l1
      capability: energyMeter
      version: 1
    - component: l2
      capability: voltageMeasurement
      version: 1
    - component: l2
      capability: currentMeasurement
      version: 1
    - component: l2
      capability: powerMeter
      version: 1
    - component: l2
      capability: energyMeter
      version: 1
    - component: l3
      capability: voltageMeasurement
      version: 1
    - component: l3
      capability: currentMeasurement
      version: 1
    - component: l3
      capability: powerMeter
      version: 1
    - component: l3
      capability: energyMeter
      version: 1
    - component: main
      capability: refresh
      version: 1
  automation:
    conditions:
      - component: main
        capability: powerMeter
        version: 1
      - component: main
        capability: energyMeter
        version: 1
      - component: main
        capability: concertmirror08464.nousD4zFaults
        version: 1
    actions:
      - component: main
        capability: concertmirror08464.nousD4zEnergyReset
        version: 1
