zigbeeManufacturer:
  - id: "fp_e4394f9ffa"
    manufacturer: "AOYAN"
    model: "AY-204ZX"
    deviceProfileName: "safety-presence-battery-zg204zk"
  - id: "fp_a1dd0118de"
    manufacturer: "B3876M9"
    model: "ZP-301Z"
    deviceProfileName: "safety-presence-zp301z-time-cycle-illuminance-battery"
  - id: "fp_4667c009da"
    manufacturer: "C6B7KM9"
    model: "Excellux"
    deviceProfileName: "safety-presence-illuminance-battery"
  - id: "fp_c3f8f53d5b"
    manufacturer: "HOBEIAN"
    model: "ZG-204ZE"
    deviceProfileName: "safety-presence-zg204ze-dedicated-illuminance-battery"
  - id: "fp_8e1b531541"
    manufacturer: "HOBEIAN"
    model: "ZG-204ZH"
    deviceProfileName: "safety-presence-zg204zh-dedicated-mode-illuminance-temp-humidity-battery"
  - id: "fp_914c10b6e4"
    manufacturer: "HOBEIAN"
    model: "ZG-204ZK"
    deviceProfileName: "safety-presence-zg204zk-dedicated-illuminance-battery"
  - id: "fp_290756be03"
    manufacturer: "HOBEIAN"
    model: "ZG-204ZQ"
    deviceProfileName: "safety-presence-zg204zq-illuminance-temp-humidity-battery"
  - id: "fp_42906ed8a5"
    manufacturer: "HOBEIAN"
    model: "ZG-204ZV"
    deviceProfileName: "safety-presence-zg204zv-dedicated-illuminance-temp-humidity-battery"
  - id: "fp_15be1c84b5"
    manufacturer: "HOBEIAN"
    model: "ZG-204ZX"
    deviceProfileName: "safety-presence-illuminance-temp-humidity-battery-zg204zx"
  - id: "fp_3b4b1911f5"
    manufacturer: "Moes"
    model: "ZSS-QY-HP"
    deviceProfileName: "safety-presence-zym100l-fixed-illuminance"
  - id: "fp_8876184c8d"
    manufacturer: "Nova Digital"
    model: "ZTS-MM"
    deviceProfileName: "safety-presence-zy-hps01-illuminance"
  - id: "fp_d58a315800"
    manufacturer: "Tuya"
    model: "ZT24"
    deviceProfileName: "safety-presence-zf24-move-illuminance"
  - id: "fp_4bba0f1037"
    manufacturer: "Tuya"
    model: "ZX24"
    deviceProfileName: "safety-presence-zf24-move-illuminance"
  - id: "fp_da009be743"
    manufacturer: "Tuya"
    model: "ZY-M100-L"
    deviceProfileName: "safety-presence-zym100l-fixed-illuminance"
  - id: "fp_d1c6d826f6"
    manufacturer: "Wenzhi"
    model: "WZ-M100-W"
    deviceProfileName: "safety-presence-zym100s1-range-delay-illuminance"
  - id: "fp_c9c1c042d9"
    manufacturer: "ZG-204ZE"
    model: "CK-BL702-MWS-01(7016)"
    deviceProfileName: "safety-presence-zg204ze-dedicated-illuminance-battery"
  - id: "fp_3e9d3975ec"
    manufacturer: "_TZE200_0u3bj3rc"
    model: "TS0601"
    deviceProfileName: "safety-presence-basic"
  - id: "fp_0119b4c3e1"
    manufacturer: "_TZE200_2aaelwxk"
    model: "TS0225"
    deviceProfileName: "safety-presence-zg204zm-dedicated-mode-illuminance-battery"
  - id: "fp_c0ddaaeb2c"
    manufacturer: "_TZE200_2aaelwxk"
    model: "TS0601"
    deviceProfileName: "safety-presence-zg204zm-dedicated-mode-illuminance-battery"
  - id: "fp_d08d12f6d3"
    manufacturer: "_TZE200_4pm4pekt"
    model: "TS0601"
    deviceProfileName: "safety-presence-zg204ze-dedicated-illuminance-battery"
  - id: "fp_92398be434"
    manufacturer: "_TZE200_cq8lu23i"
    model: "TS0601"
    deviceProfileName: "safety-presence-zg204ze-dedicated-illuminance-battery"
  - id: "fp_8a81952af0"
    manufacturer: "_TZE200_grgol3xp"
    model: "TS0601"
    deviceProfileName: "safety-presence-zg204zv-dedicated-illuminance-temp-humidity-battery"
  - id: "fp_e9fa987681"
    manufacturer: "_TZE200_hdih4foa"
    model: "TS0601"
    deviceProfileName: "safety-presence-zg204zh-dedicated-mode-illuminance-temp-humidity-battery"
  - id: "fp_da32acef49"
    manufacturer: "_TZE200_holel4dk"
    model: "TS0601"
    deviceProfileName: "safety-presence-zym100l-fixed-illuminance"
  - id: "fp_a7d2037033"
    manufacturer: "_TZE200_hyhl5y36"
    model: "TS0601"
    deviceProfileName: "safety-presence-msa201-illuminance"
  - id: "fp_d48a752b56"
    manufacturer: "_TZE200_ikvncluo"
    model: "TS0601"
    deviceProfileName: "safety-presence-zym100l-fixed-illuminance"
  - id: "fp_e16538df7b"
    manufacturer: "_TZE200_jkbljri7"
    model: "TS0601"
    deviceProfileName: "safety-presence-mir-fall-illuminance"
  - id: "fp_d62f7a34b8"
    manufacturer: "_TZE200_juzago6i"
    model: "TS0601"
    deviceProfileName: "safety-presence-pir24g-dedicated-illuminance-battery"
  - id: "fp_aa29e4c8bc"
    manufacturer: "_TZE200_jva8ink8"
    model: "TS0601"
    deviceProfileName: "safety-presence-zym100l-fixed-illuminance"
  - id: "fp_da7441a9e9"
    manufacturer: "_TZE200_ka8l86iu"
    model: "TS0601"
    deviceProfileName: "safety-presence-zg204zk-dedicated-illuminance-battery"
  - id: "fp_f2c45b36bb"
    manufacturer: "_TZE200_kb5noeto"
    model: "TS0601"
    deviceProfileName: "safety-presence-zg204zm-dedicated-mode-illuminance-battery"
  - id: "fp_3662aa8190"
    manufacturer: "_TZE200_lu01t0zl"
    model: "TS0601"
    deviceProfileName: "safety-presence-mir-fall-illuminance"
  - id: "fp_3e48c067af"
    manufacturer: "_TZE200_lyetpprm"
    model: "TS0601"
    deviceProfileName: "safety-presence-zym100l-fixed-illuminance"
  - id: "fp_42cb4a08a8"
    manufacturer: "_TZE200_mgxy2d9f"
    model: "TS0601"
    deviceProfileName: "safety-motion-tamper-battery"
  - id: "fp_cf095db716"
    manufacturer: "_TZE200_mx6u6l4y"
    model: "TS0601"
    deviceProfileName: "safety-presence-basic"
  - id: "fp_03fc4697a5"
    manufacturer: "_TZE200_p9zbdqgs"
    model: "TS0601"
    deviceProfileName: "safety-presence-zg204zq-illuminance-temp-humidity-battery"
  - id: "fp_e8b05a4d13"
    manufacturer: "_TZE200_qasjif9e"
    model: "TS0601"
    deviceProfileName: "safety-presence-zym100s2-range-delay-illuminance"
  - id: "fp_217c7f2543"
    manufacturer: "_TZE200_rhgsbacq"
    model: "TS0601"
    deviceProfileName: "safety-presence-zg204zv-dedicated-illuminance-temp-humidity-battery"
  - id: "fp_5a4948b6f1"
    manufacturer: "_TZE200_sgpeacqp"
    model: "TS0601"
    deviceProfileName: "safety-presence-zym100l-fixed-illuminance"
  - id: "fp_aaa9c0cd0b"
    manufacturer: "_TZE200_tyffvoij"
    model: "TS0601"
    deviceProfileName: "safety-presence-zg204zm-dedicated-mode-illuminance-battery"
  - id: "fp_a1ce595d80"
    manufacturer: "_TZE200_uli8wasj"
    model: "TS0601"
    deviceProfileName: "safety-presence-zg204zv-dedicated-illuminance-temp-humidity-battery"
  - id: "fp_b939071276"
    manufacturer: "_TZE200_v6ossqfy"
    model: "TS0601"
    deviceProfileName: "safety-presence-basic"
  - id: "fp_e6fb4b611d"
    manufacturer: "_TZE200_vrfecyku"
    model: "TS0601"
    deviceProfileName: "safety-presence-mir-fall-illuminance"
  - id: "fp_886f6b8403"
    manufacturer: "_TZE200_vuqzj1ej"
    model: "TS0601"
    deviceProfileName: "safety-presence-zg204zh-dedicated-mode-illuminance-temp-humidity-battery"
  - id: "fp_a26ad4ab35"
    manufacturer: "_TZE200_w0ap83qu"
    model: "TS0601"
    deviceProfileName: "safety-presence-illuminance-temp-humidity-battery-zg204zx"
  - id: "fp_ebbcece44b"
    manufacturer: "_TZE200_wukb7rhc"
    model: "TS0601"
    deviceProfileName: "safety-presence-zym100l-fixed-illuminance"
  - id: "fp_205aa153a1"
    manufacturer: "_TZE200_xpq2rzhq"
    model: "TS0601"
    deviceProfileName: "safety-presence-zym100l-fixed-illuminance"
  - id: "fp_6977979d13"
    manufacturer: "_TZE200_y8jijhba"
    model: "TS0601"
    deviceProfileName: "safety-presence-zg204zv-dedicated-illuminance-temp-humidity-battery"
  - id: "fp_287d6392ff"
    manufacturer: "_TZE200_yflzeeqj"
    model: "TS0601"
    deviceProfileName: "safety-presence-zg204zm-dedicated-mode-illuminance-battery"
  - id: "fp_a08d56dfb7"
    manufacturer: "_TZE200_ypprdwsl"
    model: "TS0601"
    deviceProfileName: "safety-presence-mir-fall-illuminance"
  - id: "fp_65e1a2d138"
    manufacturer: "_TZE200_zbfmvj13"
    model: "TS0601"
    deviceProfileName: "safety-presence-zg204zk-dedicated-illuminance-battery"
  - id: "fp_b124294369"
    manufacturer: "_TZE200_ztc6ggyl"
    model: "TS0601"
    deviceProfileName: "safety-presence-zym100l-fixed-illuminance"
  - id: "fp_5d612a8500"
    manufacturer: "_TZE204_aai5grix"
    model: "TS0601"
    deviceProfileName: "safety-presence-illuminance"
  - id: "fp_2e41c841d3"
    manufacturer: "_TZE204_bmdsp6bs"
    model: "TS0601"
    deviceProfileName: "safety-presence-y1in-dedicated-illuminance"
  - id: "fp_482fde187d"
    manufacturer: "_TZE204_bvfld3xc"
    model: "TS0601"
    deviceProfileName: "safety-presence-mir-fall-illuminance"
  - id: "fp_0dbdd00869"
    manufacturer: "_TZE204_debczeci"
    model: "TS0601"
    deviceProfileName: "safety-presence-basic-delay-battery"
  - id: "fp_0a0e58fdc1"
    manufacturer: "_TZE204_e5m9c5hl"
    model: "TS0601"
    deviceProfileName: "safety-presence-zym100s1-range-delay-illuminance"
  - id: "fp_805c37cee9"
    manufacturer: "_TZE204_eaulras5"
    model: "TS0601"
    deviceProfileName: "safety-presence-illuminance"
  - id: "fp_04241f6d7d"
    manufacturer: "_TZE204_ex3rcdha"
    model: "TS0601"
    deviceProfileName: "safety-presence-zy-hps01-illuminance"
  - id: "fp_0bbba1eea6"
    manufacturer: "_TZE204_fwondbzy"
    model: "TS0601"
    deviceProfileName: "safety-presence-zym100l-fixed-illuminance"
  - id: "fp_23b1eb27c4"
    manufacturer: "_TZE204_iadro9bf"
    model: "TS0601"
    deviceProfileName: "safety-presence-zym100s2-range-delay-illuminance"
  - id: "fp_a20b714db7"
    manufacturer: "_TZE204_kyhbrfyl"
    model: "TS0601"
    deviceProfileName: "safety-presence-range-illuminance"
  - id: "fp_38254f9980"
    manufacturer: "_TZE204_laokfqwu"
    model: "TS0601"
    deviceProfileName: "safety-presence-wzm100-range-delay-illuminance"
  - id: "fp_02ec79353d"
    manufacturer: "_TZE204_lbbg34rj"
    model: "TS0601"
    deviceProfileName: "safety-presence-zy-hps01-illuminance"
  - id: "fp_38f17783e3"
    manufacturer: "_TZE204_mhxn2jso"
    model: "TS0601"
    deviceProfileName: "safety-presence-range-delay-illuminance"
  - id: "fp_016b53edf7"
    manufacturer: "_TZE204_muvkrjr5"
    model: "TS0601"
    deviceProfileName: "safety-presence"
  - id: "fp_aa8424cd6b"
    manufacturer: "_TZE204_no6qtgtl"
    model: "TS0601"
    deviceProfileName: "safety-presence-range-illuminance"
  - id: "fp_1c6027c7f6"
    manufacturer: "_TZE204_qasjif9e"
    model: "TS0601"
    deviceProfileName: "safety-presence-zym100s2-range-delay-illuminance"
  - id: "fp_ae74b8dc76"
    manufacturer: "_TZE204_sxm7l9xa"
    model: "TS0601"
    deviceProfileName: "safety-presence-zym100s1-range-delay-illuminance"
  - id: "fp_195f1f22e3"
    manufacturer: "_TZE204_xpq2rzhq"
    model: "TS0601"
    deviceProfileName: "safety-presence-zym100l-fixed-illuminance"
  - id: "fp_e0e990c447"
    manufacturer: "_TZE204_xsm7l9xa"
    model: "TS0601"
    deviceProfileName: "safety-presence-zym100l-fixed-illuminance"
  - id: "fp_911da43abf"
    manufacturer: "_TZE204_ztc6ggyl"
    model: "TS0601"
    deviceProfileName: "safety-presence-zym100l-fixed-illuminance"
  - id: "fp_6aaf7eb341"
    manufacturer: "_TZE204_ztqnh5cg"
    model: "TS0601"
    deviceProfileName: "safety-presence-zym100s2-range-delay-illuminance"
  - id: "fp_207011ef20"
    manufacturer: "_TZE284_1lvln0x6"
    model: "TS0601"
    deviceProfileName: "safety-presence-basic-delay-battery"
  - id: "fp_8af1f2f69e"
    manufacturer: "_TZE284_aai5grix"
    model: "TS0601"
    deviceProfileName: "safety-presence-illuminance"
  - id: "fp_084eb08c22"
    manufacturer: "_TZE284_ajuasrmx"
    model: "TS0601"
    deviceProfileName: "safety-presence-msa201-illuminance"
  - id: "fp_5c013fb400"
    manufacturer: "_TZE284_bw4ayyeh"
    model: "TS0601"
    deviceProfileName: "safety-presence-illuminance-battery"
  - id: "fp_fe207cf911"
    manufacturer: "_TZE284_d4h8j2n6"
    model: "ZP-301Z"
    deviceProfileName: "safety-presence-zp301z-time-cycle-illuminance-battery"
  - id: "fp_5aae260531"
    manufacturer: "_TZE284_debczeci"
    model: "TS0601"
    deviceProfileName: "safety-presence-basic-delay-battery"
  - id: "fp_dfa98dab7a"
    manufacturer: "_TZE284_fwondbzy"
    model: "TS0601"
    deviceProfileName: "safety-presence-zym100l-fixed-illuminance"
  - id: "fp_04ee75df31"
    manufacturer: "_TZE284_gnpflcoq"
    model: "TS0601"
    deviceProfileName: "safety-presence-gnpflcoq-illuminance-temp-humidity-battery"
  - id: "fp_87378b4402"
    manufacturer: "_TZE284_hgeqeyuv"
    model: "TS0601"
    deviceProfileName: "safety-presence-zf24-move-illuminance"
  - id: "fp_d015318462"
    manufacturer: "_TZE284_iadro9bf"
    model: "TS0601"
    deviceProfileName: "safety-presence-zym100s2-range-delay-illuminance"
  - id: "fp_50d11cba27"
    manufacturer: "_TZE284_ozf4e02o"
    model: "TS0601"
    deviceProfileName: "safety-presence-msa201-illuminance"
  - id: "fp_3736e46c54"
    manufacturer: "_TZE284_pzm3wab5"
    model: "TS0601"
    deviceProfileName: "safety-presence-zf24-move-illuminance"
  - id: "fp_a2fc2f7cda"
    manufacturer: "_TZE284_twybxdzl"
    model: "TS0601"
    deviceProfileName: "safety-presence-zf24-move-illuminance"
  - id: "fp_4f9867ea14"
    manufacturer: "_TZE284_vceqncho"
    model: "TS0601"
    deviceProfileName: "safety-presence-zis01p-illuminance-battery"
  - id: "fp_17642d2ef0"
    manufacturer: "_TZE284_who1jxwd"
    model: "TS0601"
    deviceProfileName: "safety-presence-zis01p-illuminance-battery"
  - id: "fp_4f1fc093fa"
    manufacturer: "_TZE284_xpq2rzhq"
    model: "TS0601"
    deviceProfileName: "safety-presence-zym100l-fixed-illuminance"
  - id: "fp_12bead2206"
    manufacturer: "iHseno"
    model: "TY_24G_Sensor_V2"
    deviceProfileName: "safety-presence-zym100s2-range-delay-illuminance"
