local tuya=require "protocol.tuya"
local emit=require "capabilities.events.all"
local device_helpers=require "contracts.helpers.family"
local converter=tuya.converter
local device_definitions,register_device_definition=device_helpers.definition_registry()
local power_meter_model_zwpm16={
profile="meters-zwpm16",
package_group="meters",
tuya.dp_current(18,{
emit=emit.current(),converter=converter.signed_number_pair(1000),signed=true,read_only=true,
}),
tuya.dp_power(19,{
emit=emit.power(),converter=converter.signed_number_pair(10),signed=true,read_only=true,
}),
tuya.dp_voltage(20,{
emit=emit.voltage(),converter=converter.signed_number_pair(10),signed=true,read_only=true,
}),
tuya.dp_energy(104,{
emit=emit.energy(),converter=converter.signed_number_pair(1000),signed=true,read_only=true,
}),
tuya.dp_numeric(105,{
name="daily_energy",
converter=converter.signed_number_pair(1000),
signed=true,
read_only=true,
emit=emit.zwpm16DailyEnergy(),
}),
query_on_configure=false,
time_start="off",
}
register_device_definition(power_meter_model_zwpm16,device_helpers.create_fingerprints("TS0601",{
"_TZE204_goecjd1t",
}))
local power_meter_model_zwpm16_2={
profile="meters-zwpm16-2",
package_group="meters",
tuya.dp_power(105,{
name="power_l1",component="main",emit=emit.power(),
converter=converter.signed_number_pair(10),signed=true,read_only=true,
}),
tuya.dp_current(106,{
name="current_l1",component="main",emit=emit.current(),
converter=converter.signed_number_pair(1000),signed=true,read_only=true,
}),
tuya.dp_voltage(107,{
name="voltage_l1",component="main",emit=emit.voltage(),
converter=converter.signed_number_pair(10),signed=true,read_only=true,
}),
tuya.dp_energy(108,{
name="energy_l1",component="main",emit=emit.energy(),
converter=converter.signed_number_pair(1000),signed=true,read_only=true,
}),
tuya.dp_numeric(109,{
name="daily_energy_l1",
component="main",
converter=converter.signed_number_pair(1000),
signed=true,
read_only=true,
emit=emit.zwpm16TwoDailyEnergyL1(),
}),
tuya.dp_power(115,{
name="power_l2",component="l2",emit=emit.power(),
converter=converter.signed_number_pair(10),signed=true,read_only=true,
}),
tuya.dp_current(116,{
name="current_l2",component="l2",emit=emit.current(),
converter=converter.signed_number_pair(1000),signed=true,read_only=true,
}),
tuya.dp_voltage(117,{
name="voltage_l2",component="l2",emit=emit.voltage(),
converter=converter.signed_number_pair(10),signed=true,read_only=true,
}),
tuya.dp_energy(118,{
name="energy_l2",component="l2",emit=emit.energy(),
converter=converter.signed_number_pair(1000),signed=true,read_only=true,
}),
tuya.dp_numeric(119,{
name="daily_energy_l2",
component="l2",
converter=converter.signed_number_pair(1000),
signed=true,
read_only=true,
emit=emit.zwpm16TwoDailyEnergyL2(),
}),
query_on_configure=false,
time_start="off",
}
register_device_definition(power_meter_model_zwpm16_2,device_helpers.create_fingerprints("TS0601",{
"_TZE204_jrcfsaa3",
}))
return{
id="ef00.din_rail.meters.z2m_absorption",
registrations=device_definitions,
}
